// @vyre/ui: the one UI package. Tokens in, components out. Nothing outside this folder may import a UI library
// (react-native-reusables, @rn-primitives, @tanstack/react-table, @dnd-kit): scripts/check-ui-imports.mjs fails the build if one does.
export { ThemeProvider, useUiTheme, useAppearance, PHONE_MAX } from "./theme";
export type { SpaceTheme, PersonTheme, Resolved } from "./theme";
export { cn } from "./lib/cn";
export { Text } from "./components/Text";
export { Markdown, openOutside } from "./components/Markdown";
export { CodeBlock } from "./components/CodeBlock";
export { Icon, ICON_NAMES } from "./components/Icon";
export type { IconName } from "./components/Icon";
export { Button, IconButton } from "./components/Button";
export { Chip } from "./components/Chip";
export { ProviderBadge } from "./components/ProviderBadge";
export { providerName, providerOfModel } from "./marks/provider.js";
export { Fab } from "./components/Fab";
export { Card, Divider } from "./components/Card";
export { SectionLabel } from "./components/SectionLabel";
export { SpaceSwitcherTitle } from "./components/SpaceSwitcherTitle";
export type { SwitcherSpace } from "./components/SpaceSwitcherTitle";
export { Row } from "./components/Row";
export { Banner } from "./components/Banner";
export { Field } from "./components/Field";
export { Composer } from "./components/Composer";
export { Switch } from "./components/Switch";
export { Segmented } from "./components/Segmented";
export { Tabs } from "./components/Tabs";
export { Avatar, AvatarStack, SpaceMark, kindOf, badgePx } from "./components/Avatar";
export type { AvatarKind, AvatarRef, AvatarSize } from "./components/Avatar";
export type AvatarFamily = import("./components/Avatar").AvatarKind;
export { markRef, spaceRef } from "./marks/useMark";
export { IconTile } from "./components/IconTile";
export { AskCard } from "./components/AskCard";
export { Sheet } from "./components/Sheet";
export { Menu } from "./components/Menu";
export type { MenuItem } from "./components/Menu";
export { showToast, comingSoon, ToastHost } from "./components/Toast";
export { Table } from "./components/Table";
export type { Column, TableProps } from "./components/Table";
export { Board } from "./components/Board";
export type { BoardColumn, BoardProps } from "./components/BoardStacked";
export { StageSteps, StageMini } from "./components/StageSteps";
export { PageHeader } from "./components/PageHeader";
export { glass, tint } from "./lib/glass";
export { TimelineItem } from "./components/TimelineItem";
export { EmptyState, ErrorState, LoadingState } from "./components/States";
export { motion, SPRING, useReducedMotion, PressableScale, Appear, Stagger, Skeleton, SkeletonRows, SkeletonPage, Pulse, haptic, SwipeActions, LargeTitleScreen } from "./motion";
export type { PressableScaleProps, HapticName, SwipeAction, SwipeSet } from "./motion";
export { useStore, useStoreQuery, setStore, allowsMock } from "./store";
export type { Store, Query } from "./store";
export { Shell } from "./shell/Shell";
export type { NavItem, NavDef, ShellSpace, ShellProps } from "./shell/Shell";
export { FilterPills } from "./components/FilterPills";
export { ActorMark } from "./tasks/ActorMark";
export { TaskCard } from "./tasks/TaskCard";
export { TaskDetail } from "./tasks/TaskDetail";
export { taskHeader, projectHeader, faceOf } from "./tasks/headers";
export { TaskFacts, DraftBlock } from "./tasks/TaskFacts";
export { NowView } from "./tasks/NowView";
export { NeedsPage, DoingPage } from "./tasks/NowPages";
export { ProjectView } from "./tasks/ProjectView";
export { ProjectsList, NewMenu } from "./tasks/ProjectsList";
export { useTaskActions } from "./tasks/TaskActions";
export { usePlayScenario } from "./tasks/scenario";
export { useWorld, useProject, useWork } from "./tasks/useWorld";
export type { World } from "./tasks/model";
export { nowCount } from "./tasks/model";
// Field renderers (one display and one edit per kind) and the views generated from type definitions (records).
export { Select } from "./components/Select";
export { renderField, editField, registry as fieldRegistry, KINDS as FIELD_KINDS, filterOps, matches, sortKey, sortRows, kindLabel } from "./fields/registry";
export type { FieldEnv, FieldProps, FieldMode } from "./fields/types";
export { BoardView, CalendarView, DashboardView, RecordPage, useRecordsWorld, useRecordEvents, useFieldEnv, viewsOf, viewDefOf, storedViewsOf, viewRows, filterWords, isHiddenType, fieldStates, titleOf, urnParam } from "./views";
export type { RecordsWorld } from "./views";
export { SealedMask } from "./fields/Sealed";
export { Ring } from "./components/Ring";
export { FlowCanvas } from "./canvas/FlowCanvas";
export type { CanvasNode, CanvasEdge, NodeState } from "./canvas/FlowCanvas";
export { Meter } from "./components/Meter";

// The design language: a resolved screen drawn from blocks (lib/views/blocks.js).
export { BlockScreen, ChatCard, DRAWN_TYPES, registerBlock } from "./blocks";
export type { Screen as BlockScreenData, Handlers as BlockHandlers } from "./blocks";
