// @vyre/ui: the one UI package. Tokens in, components out. Nothing outside this folder may import a UI library
// (react-native-reusables, @rn-primitives, @tanstack/react-table, @dnd-kit): scripts/check-ui-imports.mjs fails the build if one does.
export { ThemeProvider, useUiTheme, useAppearance, PHONE_MAX } from "./theme";
export type { SpaceTheme, PersonTheme, Resolved } from "./theme";
export { cn } from "./lib/cn";
export { Text } from "./components/Text";
export { Icon } from "./components/Icon";
export type { IconName } from "./components/Icon";
export { Button, IconButton } from "./components/Button";
export { Chip } from "./components/Chip";
export { Card, Divider } from "./components/Card";
export { Row } from "./components/Row";
export { Banner } from "./components/Banner";
export { Field } from "./components/Field";
export { Switch } from "./components/Switch";
export { Segmented } from "./components/Segmented";
export { Tabs } from "./components/Tabs";
export { Avatar } from "./components/Avatar";
export type { AvatarFamily } from "./components/Avatar";
export { AskCard } from "./components/AskCard";
export { Sheet } from "./components/Sheet";
export { Menu } from "./components/Menu";
export type { MenuItem } from "./components/Menu";
export { showToast, ToastHost } from "./components/Toast";
export { Table } from "./components/Table";
export type { Column } from "./components/Table";
export { Board } from "./components/Board";
export type { BoardColumn, BoardProps } from "./components/BoardStacked";
export { StageSteps } from "./components/StageSteps";
export { TimelineItem } from "./components/TimelineItem";
export { EmptyState, ErrorState } from "./components/States";
export { useStore, useStoreQuery, setStore } from "./store";
export type { Store, Query } from "./store";
export { Shell } from "./shell/Shell";
export type { NavItem, NavDef, ShellSpace, ShellProps } from "./shell/Shell";
export { FilterPills } from "./components/FilterPills";
export { ActorMark } from "./tasks/ActorMark";
export { TaskCard } from "./tasks/TaskCard";
export { TaskDetail } from "./tasks/TaskDetail";
export { TaskFacts, DraftBlock } from "./tasks/TaskFacts";
export { NowView } from "./tasks/NowView";
export { ProjectView } from "./tasks/ProjectView";
export { ProjectsList } from "./tasks/ProjectsList";
export { useTaskActions } from "./tasks/TaskActions";
export { usePlayScenario } from "./tasks/scenario";
export { useWorld, useProject, useWork } from "./tasks/useWorld";
export type { World } from "./tasks/model";
// Field renderers (one display and one edit per kind) and the views generated from type definitions (records).
export { Select } from "./components/Select";
export { renderField, editField, registry as fieldRegistry, KINDS as FIELD_KINDS, filterOps, matches, sortKey, sortRows, kindLabel } from "./fields/registry";
export type { FieldEnv, FieldProps, FieldMode } from "./fields/types";
export { ListView, BoardView, CalendarView, RecordPage, HowMade, useRecordsWorld, useRecordEvents, useFieldEnv, viewsOf, viewDefOf, titleOf, urnParam } from "./views";
export type { RecordsWorld } from "./views";
export { Ring } from "./components/Ring";
export { FlowCanvas } from "./canvas/FlowCanvas";
export type { CanvasNode, CanvasEdge, NodeState } from "./canvas/FlowCanvas";
export { Meter } from "./components/Meter";
