// The Vyre palette, copied verbatim from docs/design/TOKENS.md: keys are the CSS names without `--`.
// THEME_COLORS holds the values per theme, THEME_USE says what each token is for. No dependencies.

export const THEME_COLORS = {
  dark: {
    "graphite": "#0E0D0C",
    "carbon": "#161513",
    "raised": "#1E1C1A",
    "rule": "#2B2926",
    "rule-strong": "#3A3733",
    "ash": "#8C877D",
    "stone": "#B3AEA4",
    "bone": "#F1EEE6",
    "signal": "#C6F36B",
    "signal-hover": "#D4F88A",
    "signal-ink": "#0E0D0C",
    "signal-wash": "rgba(198,243,107,0.12)",
    "recall": "#EBC76B",
    "recall-wash": "rgba(235,199,107,0.10)",
    "beacon": "#FF7A59",
    "beacon-wash": "rgba(255,122,89,0.12)",
  },
  light: {
    "paper": "#F4F1EA",
    "paper-raised": "#FBFAF6",
    "paper-rule": "#DCD7CC",
    "paper-rule-strong": "#C9C3B7",
    "ink": "#141311",
    "ink-2": "#4A463F",
    "ink-3": "#6B665D",
    "signal-deep": "#46700C",
    "recall-deep": "#7E5B0C",
    "beacon-deep": "#C2411F",
  },
};

export const THEME_USE = {
  "graphite": "Page ground. Warm graphite black.",
  "carbon": "Panels, windows, app-icon tile. One step up from ground.",
  "raised": "Hover rows, popovers, tab strips. Use rarely.",
  "rule": "Hairline rules and dividers (1px). The default separator.",
  "rule-strong": "Input borders, swatch outlines, vertical rules in lockups.",
  "ash": "Engraved labels, captions, placeholders. 5.4:1 on graphite. Smallest text colour allowed.",
  "stone": "Secondary text. 9:1 on graphite.",
  "bone": "Primary text, the wire in the mark.",
  "signal": "Focus and the one primary action per view. The mark's dot. Never decoration, never a large fill.",
  "signal-hover": "Hover on signal-filled buttons.",
  "signal-ink": "Text on a signal fill.",
  "signal-wash": "Selected row / focus ring fill.",
  "recall": "Came from your memory; no model was used. Only where memory surfaces: recalled facts, enrichment lines, memory-graph nodes.",
  "recall-wash": "Background behind a recalled block.",
  "beacon": "Needs you. Held tool calls, approvals, the menu-bar dot. Nothing else.",
  "beacon-wash": "Background behind a held item.",
  "paper": "Ground",
  "paper-raised": "Panels",
  "paper-rule": "Hairlines",
  "paper-rule-strong": "Input borders",
  "ink": "Primary text, mark",
  "ink-2": "Secondary text",
  "ink-3": "Labels (5.0:1 on paper)",
  "signal-deep": "Signal on paper: focus rings, primary text links. Primary buttons on paper stay --ink fill with --paper text.",
  "recall-deep": "Recall on paper",
  "beacon-deep": "Beacon on paper (text); #E5532F for the dot graphic",
};
