#!/bin/sh
# make-pins: write vyre-sudo-check for one architecture, from scripts/install-mac-server.sh, at build time.
#
#   sh scripts/mac-app/make-pins.sh <aarch64|x86_64> <out file>
#
# vyre-sudo runs sudo, so it must run exactly the installer's one root step and nothing else. That step is
# `/bin/sh -c "$ROOT_SH" vyre-root <node sha> <release dir> <node.tgz> <RELEASE_KEY> <VERIFY_JS> install ...`. The check pins
# the text of ROOT_SH and VERIFY_JS (by sha256), the Node checksum for this architecture, the release key, the word vyre-root and
# the verb install. A different script, a different checksum or key, or another verb is refused before sudo is asked for.
set -eu
arch="$1"; out="$2"
here="$(cd "$(dirname "$0")" && pwd)"
installer="$here/../install-mac-server.sh"
case "$arch" in aarch64) pin=NODE_SHA256_ARM64 ;; x86_64) pin=NODE_SHA256_X64 ;; *) echo "unknown architecture $arch" >&2; exit 2 ;; esac
node_sha="$(sed -n "s/^$pin=//p" "$installer" | head -1)"
key="$(sed -n 's/^RELEASE_KEY=//p' "$installer" | head -1)"
[ -n "$node_sha" ] && [ -n "$key" ] || { echo "no pinned Node or release key in $installer" >&2; exit 1; }
# The sha256 of the value of one single-quoted literal in the installer, as the shell reads it (its '"'"' quoting included): the assignment's own
# lines are handed to sh and the variable is printed, so the bytes hashed are the bytes the installer passes to sudo.
lit() {
  python3 - "$installer" "$1" <<'PY'
import subprocess, sys
name = sys.argv[2]
lines = open(sys.argv[1]).read().split("\n")
start = next((i for i, l in enumerate(lines) if l.startswith(name + "='")), None)
if start is None:
    sys.exit("no literal " + name)
end = next((i for i in range(start, len(lines)) if lines[i].endswith("'") and not lines[i].endswith("'\"'\"'") and (i > start or len(lines[i]) > len(name) + 2)), None)
if end is None:
    sys.exit("the literal " + name + " does not end")
assign = "\n".join(lines[start:end + 1])
r = subprocess.run(["/bin/sh", "-c", assign + '\nprintf %s "$' + name + '"'], capture_output=True)
if r.returncode != 0 or not r.stdout:
    sys.exit("could not read the literal " + name)
import hashlib
print(hashlib.sha256(r.stdout).hexdigest())
PY
}
root_sha="$(lit ROOT_SH)" || exit 1
verify_sha="$(lit VERIFY_JS)" || exit 1
{
  echo '#!/bin/sh'
  echo '# vyre-sudo-check: generated by scripts/mac-app/make-pins.sh. Refuses anything but the installer root step, pinned.'
  echo "want_root=$root_sha"
  echo "want_verify=$verify_sha"
  echo "want_node=$node_sha"
  echo "want_key='$key'"
  cat <<'CHECK'
sha() { printf %s "$1" | /usr/bin/shasum -a 256 | cut -d' ' -f1; }
refuse() { echo "vyre-sudo: refused: it runs only the installer's root step ($1)" >&2; exit 126; }
[ "$#" -ge 10 ] || refuse "wrong shape"
[ "$1" = /bin/sh ] && [ "$2" = -c ] || refuse "not sh -c"
[ "$(sha "$3")" = "$want_root" ] || refuse "not the installer's root script"
[ "$4" = vyre-root ] || refuse "wrong name"
[ "$5" = "$want_node" ] || refuse "wrong Node checksum"
[ "$8" = "$want_key" ] || refuse "wrong release key"
[ "$(sha "$9")" = "$want_verify" ] || refuse "wrong verify script"
[ "${10}" = install ] || refuse "wrong verb"
exit 0
CHECK
} > "$out"
chmod 755 "$out"
