// @ts-check
// Presence with an RSA (RS256) device key, as Windows Hello's KeyCredential makes one. Every key
// here is generated by the test; no real device material.

import "../../scripts/mac-test-guard.mjs";
import { test } from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import path from "node:path";
import { Presence, inputHash } from "./index.js";
import { bcryptRsaToJwk, normalizePublicKey } from "./keys.js";
import { verifyAssertion } from "./webauthn.js";
import { open } from "../store/index.js";
import { tempHome } from "../../test/helpers.js";

const APPROVE = { tool: "gate.approve", input: { id: "a1" } };
const WHO = "tailnet:alex@example.com";
const spkiOf = k => k.export({ format: "der", type: "spki" }).toString("base64url");
const rsaPair = (modulusLength = 2048, publicExponent = 65537) => crypto.generateKeyPairSync("rsa", { modulusLength, publicExponent });

function setup(t) {
  const db = open(path.join(tempHome(t), "vyre.db"));
  t.after(() => db.close());
  let clock = 1_000_000;
  const p = new Presence({ db, platform: "linux", touchid: null, webauthn: null, now: () => clock });
  return { p, db, now: () => clock };
}

const message = (tool, input, ts, nonce) => Buffer.from(`vyre-presence-v1\n${tool}\n${inputHash(input)}\n${ts}\n${nonce}`);

/** An RSA device key enrolled, and a signer that produces RS256 over the same bytes the EC path signs. */
function rsaDevice(p, pair = rsaPair()) {
  const k = p.enroll({ kind: "device", name: "alex-laptop", public_key: spkiOf(pair.publicKey), alg: -257 });
  const sign = (tool, input, ts, nonce = crypto.randomBytes(12).toString("base64url")) => ({
    method: "device", key: k.id, ts: String(ts), nonce,
    sig: crypto.sign("sha256", message(tool, input, ts, nonce), pair.privateKey).toString("base64url"),
  });
  return { ...k, sign, pair };
}

/** A BCRYPT_RSAKEY_BLOB public key, built the way Windows lays it out. */
function bcryptBlob(publicKey) {
  const j = publicKey.export({ format: "jwk" });
  const e = Buffer.from(j.e, "base64url"), n = Buffer.from(j.n, "base64url");
  const h = Buffer.alloc(24);
  h.writeUInt32LE(0x31415352, 0); h.writeUInt32LE(n.length * 8, 4); h.writeUInt32LE(e.length, 8); h.writeUInt32LE(n.length, 12);
  return Buffer.concat([h, e, n]);
}

test("presence rsa: an RS256 device key enrolls and proves a call once", async t => {
  const { p, db, now } = setup(t);
  const k = rsaDevice(p);
  assert.deepEqual(await p.verify({ ...APPROVE, caller: WHO, proof: k.sign(APPROVE.tool, APPROVE.input, now()) }), { ok: true, method: "device", keyId: k.id });
  assert.deepEqual({ ...db.prepare("SELECT kind, alg FROM presence_keys WHERE id = ?").get(k.id) }, { kind: "device", alg: -257 });
  assert.ok(p.keys().some(r => r.id === k.id && r.kind === "device"));
  assert.throws(() => p.enroll({ kind: "device", name: "again", public_key: spkiOf(k.pair.publicKey), alg: -257 }), /already enrolled/);
});

test("presence rsa: a wrong signature, a tampered call and a replayed nonce are refused", async t => {
  const { p, now } = setup(t);
  const k = rsaDevice(p);
  const other = rsaPair().privateKey;
  const nonce = crypto.randomBytes(12).toString("base64url");
  const ts = now();
  const forged = { ...k.sign(APPROVE.tool, APPROVE.input, ts, nonce), sig: crypto.sign("sha256", message(APPROVE.tool, APPROVE.input, ts, nonce), other).toString("base64url") };
  assert.match((await p.verify({ ...APPROVE, caller: WHO, proof: forged })).message, /does not check out/);
  // A signature for a1 does not approve b2, and a flipped signature bit fails.
  assert.equal((await p.verify({ tool: "gate.approve", input: { id: "b2" }, caller: WHO, proof: k.sign(APPROVE.tool, APPROVE.input, now()) })).ok, false);
  const good = k.sign(APPROVE.tool, APPROVE.input, now());
  const sig = Buffer.from(good.sig, "base64url"); sig[0] ^= 1;
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: { ...good, sig: sig.toString("base64url") } })).ok, false);
  // The failed tries above spent nothing: the honest proof still works once, then its nonce is spent.
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: good })).ok, true);
  assert.match((await p.verify({ ...APPROVE, caller: WHO, proof: good })).message, /nonce was already used/);
  assert.match((await p.verify({ ...APPROVE, caller: WHO, proof: k.sign(APPROVE.tool, APPROVE.input, now() - 61_000) })).message, /too old/);
});

test("presence rsa: an EC key never verifies as RSA, nor an RSA key as EC", async t => {
  const { p, db, now } = setup(t);
  const ec = crypto.generateKeyPairSync("ec", { namedCurve: "P-256" });
  // Enrollment refuses the mismatch both ways.
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spkiOf(ec.publicKey), alg: -257 }), /RSA/);
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spkiOf(rsaPair().publicKey), alg: -7 }), /P-256/);
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spkiOf(rsaPair().publicKey) }), /alg/);
  // Even a row whose stored alg was changed under it verifies nothing: the stored alg and key must agree.
  const e = p.enroll({ kind: "device", name: "phone", public_key: spkiOf(ec.publicKey), alg: -7 });
  const ts = now(), nonce = "nonce-ec-0001";
  const sigEc = crypto.sign("sha256", message(APPROVE.tool, APPROVE.input, ts, nonce), { key: ec.privateKey, dsaEncoding: "der" }).toString("base64url");
  db.prepare("UPDATE presence_keys SET alg = -257 WHERE id = ?").run(e.id);
  assert.match((await p.verify({ ...APPROVE, caller: WHO, proof: { method: "device", key: e.id, ts: String(ts), nonce, sig: sigEc } })).message, /does not check out/);
  const r = rsaDevice(p);
  db.prepare("UPDATE presence_keys SET alg = -7 WHERE id = ?").run(r.id);
  assert.match((await p.verify({ ...APPROVE, caller: WHO, proof: r.sign(APPROVE.tool, APPROVE.input, now()) })).message, /does not check out/);
});

test("presence rsa: under 2048 bits and an exponent other than 65537 are refused", async t => {
  const { p } = setup(t);
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spkiOf(rsaPair(1024).publicKey), alg: -257 }), /2048/);
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spkiOf(rsaPair(2048, 3).publicKey), alg: -257 }), /65537/);
  assert.throws(() => p.enroll({ kind: "passkey", name: "x", public_key: spkiOf(rsaPair(1024).publicKey), alg: -257, rp_id: "example.com", credential_id: "credential-small" }), /2048/);
  assert.equal(p.keys().length, 0);
  // A 1024-bit key that got into the table anyway still verifies nothing.
  const small = rsaPair(1024);
  const q = setup(t);
  q.db.prepare("INSERT INTO presence_keys (id, kind, name, public_key, alg, created) VALUES ('small','device','x',?,-257,1)").run(spkiOf(small.publicKey));
  const ts = q.now(), nonce = "nonce-small-01";
  const sig = crypto.sign("sha256", message(APPROVE.tool, APPROVE.input, ts, nonce), small.privateKey).toString("base64url");
  assert.match((await q.p.verify({ ...APPROVE, caller: WHO, proof: { method: "device", key: "small", ts: String(ts), nonce, sig } })).message, /does not check out/);
});

test("presence rsa: a JWK and a Windows BCRYPT blob enroll as the same key as its SPKI", async t => {
  const pair = rsaPair();
  const spki = spkiOf(pair.publicKey);
  assert.equal(normalizePublicKey(pair.publicKey.export({ format: "jwk" })), spki, "JWK object");
  assert.equal(normalizePublicKey(JSON.stringify(pair.publicKey.export({ format: "jwk" }))), spki, "JWK text");
  const blob = bcryptBlob(pair.publicKey);
  assert.deepEqual(bcryptRsaToJwk(blob), { kty: "RSA", e: "AQAB", n: pair.publicKey.export({ format: "jwk" }).n });
  assert.equal(normalizePublicKey(blob.toString("base64")), spki, "blob, base64");
  assert.equal(normalizePublicKey(blob.toString("base64url")), spki, "blob, base64url");
  assert.equal(normalizePublicKey(spki), spki, "SPKI is left as sent");

  const { p, now } = setup(t);
  const k = p.enroll({ kind: "device", name: "alex-laptop", public_key: blob.toString("base64"), alg: -257 });
  const ts = now(), nonce = "nonce-blob-001";
  const sig = crypto.sign("sha256", message(APPROVE.tool, APPROVE.input, ts, nonce), pair.privateKey).toString("base64url");
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: { method: "device", key: k.id, ts: String(ts), nonce, sig } })).ok, true);
  assert.throws(() => p.enroll({ kind: "device", name: "same", public_key: JSON.stringify(pair.publicKey.export({ format: "jwk" })), alg: -257 }), /already enrolled/);
});

test("presence rsa: private material and malformed blobs are refused", () => {
  const pair = rsaPair();
  const priv = pair.privateKey.export({ format: "jwk" });
  assert.throws(() => normalizePublicKey(priv), /private key material/);
  const blob = bcryptBlob(pair.publicKey);
  const withPrimes = Buffer.from(blob); withPrimes.writeUInt32LE(128, 16);
  assert.throws(() => bcryptRsaToJwk(withPrimes), /private/);
  assert.throws(() => bcryptRsaToJwk(blob.subarray(0, blob.length - 1)), /lengths/);
  const badBits = Buffer.from(blob); badBits.writeUInt32LE(2040, 4);
  assert.throws(() => bcryptRsaToJwk(badBits), /bit length/);
  assert.throws(() => normalizePublicKey({ kty: "oct", k: "AAAA" }), /kty/);
});

test("presence rsa: enrolling through Presence takes no alg none and no unknown alg", t => {
  const { p } = setup(t);
  for (const alg of [0, -65535, 1, "none"]) assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spkiOf(rsaPair().publicKey), alg: /** @type {any} */ (alg) }), /alg/, String(alg));
});

test("presence rsa: a passkey assertion never verifies as another algorithm than its key's", () => {
  const rsa = rsaPair(), ec = crypto.generateKeyPairSync("ec", { namedCurve: "P-256" });
  const RP = "vyre.example.com", challenge = crypto.randomBytes(32).toString("base64url");
  const ad = Buffer.alloc(37); crypto.createHash("sha256").update(RP).digest().copy(ad, 0); ad[32] = 0x05; ad.writeUInt32BE(1, 33);
  const cd = Buffer.from(JSON.stringify({ type: "webauthn.get", challenge, origin: "https://vyre.example.com" }));
  const signed = Buffer.concat([ad, crypto.createHash("sha256").update(cd).digest()]);
  const base = { rpId: RP, challenge, authenticatorData: ad.toString("base64url"), clientDataJSON: cd.toString("base64url") };
  const rs = crypto.sign("sha256", signed, rsa.privateKey).toString("base64url");
  const es = crypto.sign("sha256", signed, { key: ec.privateKey, dsaEncoding: "der" }).toString("base64url");
  assert.equal(verifyAssertion({ ...base, publicKey: spkiOf(rsa.publicKey), alg: -257, signature: rs }).ok, true);
  assert.equal(verifyAssertion({ ...base, publicKey: spkiOf(ec.publicKey), alg: -7, signature: es }).ok, true);
  assert.deepEqual(verifyAssertion({ ...base, publicKey: spkiOf(ec.publicKey), alg: -257, signature: es }), { ok: false, reason: "alg does not match the enrolled key" });
  assert.deepEqual(verifyAssertion({ ...base, publicKey: spkiOf(rsa.publicKey), alg: -7, signature: rs }), { ok: false, reason: "alg does not match the enrolled key" });
  assert.equal(verifyAssertion({ ...base, publicKey: spkiOf(rsa.publicKey), alg: 0, signature: rs }).ok, false);
});
