// Clipboard: the watcher that feeds ClipStore, and the provider that lists clips in the box.
//
// macOS has no pasteboard notification, so ClipWatcher polls NSPasteboard.changeCount, one
// integer read, every `interval` on the main queue, with a third of that as timer leeway so the
// system can coalesce the wakeups. It is the one thing in the Capsule that runs while it is
// hidden (the user copies things while the Capsule is closed; that is the point of a history),
// so a tick that finds no change does nothing else: no read of the contents, no allocation. Only
// when the count moves does it read the new item, once. The provider's warm() also polls once, so
// a copy made a moment before the Capsule opened is there on the first keystroke.
//
// 750 ms is the Electron helper's interval, kept: two copies in under a second are the one case a
// slower poll loses, and the cost of this rate was measured (the lead's docs/work/capsule.md
// carries the number): about 80 wakeups a minute of one integer read each.
//
// Never recorded, and never even read past its type list: items marked concealed, transient or
// auto-generated (nspasteboard.org), 1Password's marker, Universal Clipboard items from another
// device (reading one makes macOS fetch it over the air), anything copied while a password manager
// is the front app, and the Capsule's own writes, which carry ownType. write() also moves the
// watcher past its own count, so a pick never comes back as a new item.
//
// Tests pass a private named board ("vyre-test-<pid>"); nothing here needs the general one to be
// testable.

import AppKit
import Foundation
import UniformTypeIdentifiers

public enum ClipRead {
    public static let ownType = NSPasteboard.PasteboardType("run.vyre.clip")
    public static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.apple.is-remote-clipboard", "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type", "net.antelle.keeweb",
    ]
    public static let skipApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx", "com.bitwarden.desktop",
        "com.apple.keychainaccess", "com.apple.Passwords", "org.keepassxc.keepassxc", "com.lastpass.LastPass",
        "in.sinew.Enpass-Desktop", "com.dashlane.dashlanephonefinal", "com.nordpass.macos.NordPass",
    ]

    /// The item on `pb` as the watcher records it, or nil and why it was skipped.
    public static func read(_ pb: NSPasteboard, appBundle: String?, appName: String?) -> (ClipItem?, String) {
        let types = (pb.types ?? []).map(\.rawValue)
        if types.isEmpty { return (nil, "empty") }
        if types.contains(ownType.rawValue) { return (nil, "own") }
        if types.contains(where: { skipTypes.contains($0) }) { return (nil, "marked") }
        if let b = appBundle, skipApps.contains(b) { return (nil, "app") }
        var item = ClipItem(count: pb.changeCount, at: Date().timeIntervalSince1970 * 1000, app: (appName?.isEmpty ?? true) ? nil : appName)
        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue),
           let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            item.files = urls.prefix(50).map(\.path)
        } else if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            item.text = s.count > ClipText.TEXT_MAX ? String(s.prefix(ClipText.TEXT_MAX)) : s
        } else if types.contains(where: { UTType($0)?.conforms(to: .image) ?? false }) {
            item.image = true
        } else {
            return (nil, "unsupported")
        }
        return (item, "")
    }

    /// The user's pick, written to the pasteboard with the Capsule's own marker. Answers the new
    /// change count.
    public static func write(_ c: Clip, to pb: NSPasteboard) -> Result<Int, ClipWriteError> {
        let files = (c.files ?? []).filter { $0.hasPrefix("/") && FileManager.default.fileExists(atPath: $0) }
        let text = c.text ?? ""
        if c.kind == .files && files.isEmpty { return .failure(.init("the files are gone")) }
        if c.kind == .text && text.isEmpty { return .failure(.init("nothing to write")) }
        pb.clearContents()
        let ok = c.kind == .files ? pb.writeObjects(files.map { URL(fileURLWithPath: $0) as NSURL }) : pb.setString(text, forType: .string)
        if !ok { return .failure(.init("the pasteboard refused it")) }
        pb.setData(Data(), forType: ownType)
        return .success(pb.changeCount)
    }
}

/// Polls the pasteboard's change count and hands new items to the store. Main queue only.
@MainActor
public final class ClipWatcher {
    public let board: NSPasteboard
    public let store: ClipStore
    public let interval: TimeInterval
    private var timer: DispatchSourceTimer?
    private var seen = 0
    /// Ticks that found a change, for the CPU measurement.
    public private(set) var reads = 0
    public private(set) var ticks = 0
    /// Who is in front, asked only when the count moved. Tests pass a fixed answer.
    let front: () -> (bundle: String?, name: String?)

    nonisolated public static let defaultInterval: TimeInterval = 0.75

    public init(store: ClipStore, board: NSPasteboard = .general, interval: TimeInterval = ClipWatcher.defaultInterval,
                front: @escaping () -> (bundle: String?, name: String?) = {
                    let a = NSWorkspace.shared.frontmostApplication
                    return (a?.bundleIdentifier, a?.localizedName)
                }) {
        self.store = store; self.board = board; self.interval = min(max(interval, 0.1), 5); self.front = front
    }

    public var isWatching: Bool { timer != nil }

    /// Start watching. What is already on the pasteboard when watching starts is not new.
    public func start() {
        stop()
        seen = board.changeCount
        let ms = Int(interval * 1000)
        let t = DispatchSource.makeTimerSource(queue: .main)
        t.schedule(deadline: .now() + .milliseconds(ms), repeating: .milliseconds(ms), leeway: .milliseconds(ms / 3))
        t.setEventHandler { [weak self] in MainActor.assumeIsolated { self?.tick() } }
        t.resume()
        timer = t
    }

    public func stop() {
        timer?.cancel()
        timer = nil
    }

    /// One look at the change count; reads the item only when it moved.
    public func tick() {
        ticks += 1
        let n = board.changeCount
        if n == seen { return }
        seen = n
        reads += 1
        let f = front()
        let (item, _) = autoreleasepool { ClipRead.read(board, appBundle: f.bundle, appName: f.name) }
        if let item { store.add(item) }
    }

    /// Put a clip back on the pasteboard, and move past our own write.
    public func write(_ c: Clip) -> Result<Int, ClipWriteError> {
        let r = ClipRead.write(c, to: board)
        if case .success(let n) = r { seen = n }
        return r
    }
}

/// Clips in the box. Quick: the store is in memory.
public final class ClipboardProvider: ResultProvider, @unchecked Sendable {
    public let id = "clipboard"
    public let speed = Speed.quick
    public let store: ClipStore
    let watcher: ClipWatcher

    @MainActor
    public init(store: ClipStore, watcher: ClipWatcher) { self.store = store; self.watcher = watcher }

    /// A copy made a moment before the Capsule opened is there on the first keystroke.
    public func warm() { onMainActor { [watcher] in if watcher.isWatching { watcher.tick() } } }
    /// Nothing to stop: the watcher runs while hidden on purpose (see the header); the store flushes.
    public func cool() { store.flush() }

    public func results(for query: Query) async -> [ResultItem] {
        let hits = store.search(query.text, limit: 6)
        var out = hits.map(row)
        if ClipStore.listing(query.text) {
            let n = store.list().count
            out.append(ResultItem(id: "clipclear", kind: "clipclear", title: "Clear clipboard history",
                                  subtitle: n > 0 ? "\(n) items, on this Mac only" : "nothing kept", icon: .symbol("trash", .ash),
                                  section: .clipboard, score: 0.01, actions: [
                                    ResultAction(id: "clear", title: "Clear clipboard history", symbol: "trash", shortcut: KeyShortcut("return"),
                                                 confirm: "Forget every clip?") { [store] _, _ in
                                        store.clear(); return .said("Clipboard history cleared.")
                                    },
                                  ]))
        }
        return out
    }

    func row(_ hit: ClipHit) -> ResultItem {
        let c = hit.clip
        let when = ClipText.age(Date().timeIntervalSince1970 * 1000 - c.t)
        let icon: IconSpec
        switch c.kind {
        case .text: icon = .symbol("doc.plaintext", .stone)
        case .files: icon = .file(c.files?.first ?? "")
        case .image: icon = .symbol("photo", .stone)
        }
        let id = "clip:" + c.h
        let store = self.store, watcher = self.watcher
        return ResultItem(id: id, kind: "clip", title: ClipText.label(c), subtitle: c.app.map { "\($0) · \(when)" } ?? when, icon: icon,
                          section: .clipboard, score: hit.score, actions: Paster.actions(noun: c.kind == .files ? "files" : c.kind == .image ? "image" : "clip") {
                                await MainActor.run {
                                    switch store.pick(id, write: { watcher.write($0) }) {
                                    case .success: return nil
                                    case .failure(let e): return e.message
                                    }
                                }
                            } + [
                            ResultAction(id: "forget", title: "Forget this clip", symbol: "minus.circle",
                                         shortcut: KeyShortcut("delete", command: true)) { _, _ in
                                store.remove(id) ? .said("Forgotten") : .failed("That clip is gone.")
                            },
                          ], fileURL: c.kind == .files ? c.files.flatMap { $0.first }.map { URL(fileURLWithPath: $0) } : nil,
                          copyText: c.kind == .text ? c.text : nil)
    }
}
