// @ts-check
// Ratchets and allowlists that may only shrink, and the one check that makes it so: a list that GREW against the merge base needs a `[ratchet +N: why]` in a commit message of the branch (like K1 for
// the kernel), so a reviewer sees every blessing. A list regenerated by an environment switch (PROVIDER_ALLOW_WRITE, UPDATE_DESCRIPTION_BASELINE) is the same file grown, and is caught the same way.
// The guards that read these lists only check the tree against them; nothing compared the lists themselves to the base ref until here.

/** The lists, by file. `kind` says how to read it: "json" is measured by entries and numeric mass, "cap" is a number in a source file named by `pattern`. */
export const RATCHETS = Object.freeze([
  { file: "test/provider-adapters.allow.json", kind: "json", what: "provider names outside their adapter" },
  { file: "test/description-baseline.json", kind: "json", what: "tool descriptions over the word limit" },
  { file: "test/no-" + "tail" + "scale.ratchet.json", kind: "json", what: "files that still name another VPN product" },
  { file: "test/reach-anyone.json", kind: "json", what: "tools declared reach anyone" },
  { file: "test/reach-allowlist.json", kind: "json", what: "tools with no explicit reach" },
  { file: "test/reach-person-only.json", kind: "json", what: "person-only reach exceptions" },
  { file: "test/reach-computed-calls.json", kind: "json", what: "calls whose reach is computed" },
  { file: "test/one-person-surfaces.json", kind: "json", what: "files that name person surfaces" },
  { file: "test/model-is-never-person.json", kind: "json", what: "files that test a model label as the person" },
  { file: "test/plain-session-writes.json", kind: "json", what: "tools a bare session may reach" },
  { file: "test/file-size.json", kind: "json", what: "source files over 2,000 lines, by size" },
  { file: "kernel/golden/allow.json", kind: "json", what: "tools the golden set lets run for a model" },
  { file: "kernel/size.test.js", kind: "cap", pattern: /\bconst CAP = (\d+)/, what: "the kernel's size cap" },
]);

/**
 * @param {unknown} v the parsed JSON @returns {{ entries: number, mass: number }} the number of leaf entries, and the sum of the positive numbers among them
 */
export function weigh(v) {
  let entries = 0, mass = 0;
  const walk = (/** @type {unknown} */ x, /** @type {string} */ key) => {
    if (x && typeof x === "object") { for (const [k, y] of Object.entries(x)) walk(y, k); return; }
    if (key.startsWith("_")) return;   // _comment and the like
    entries++;
    if (typeof x === "number" && x > 0) mass += x;
  };
  walk(v, "");
  return { entries, mass };
}

/**
 * How a list grew from `before` to `after` (their texts), or an empty list. A missing `before` is a new file and not growth: the list is born with its reasons.
 * @param {{ file: string, kind: string, pattern?: RegExp }} r @param {string | null} before @param {string} after @returns {string[]}
 */
export function growth(r, before, after) {
  if (before === null) return [];
  if (r.kind === "cap") {
    const a = Number(r.pattern && r.pattern.exec(before)?.[1]), b = Number(r.pattern && r.pattern.exec(after)?.[1]);
    return Number.isFinite(a) && Number.isFinite(b) && b > a ? [`${r.file}: ${a} -> ${b}`] : [];
  }
  let x, y;
  try { x = weigh(JSON.parse(before)); y = weigh(JSON.parse(after)); } catch { return [`${r.file}: not valid JSON before or after`]; }
  const out = [];
  if (y.entries > x.entries) out.push(`${r.file}: ${x.entries} -> ${y.entries} entries`);
  if (y.mass > x.mass) out.push(`${r.file}: counts ${x.mass} -> ${y.mass}`);
  return out;
}

/** Is growth ruled? A commit message of the branch carries `[ratchet +N: why]`. @param {string} bodies */
export const ruled = bodies => /\[ratchet \+\d+:\s*[^\s\]]/i.test(bodies);
