// @ts-check
// Per-Space provisioning of Twenty (spec 3.7, R5-15): one Twenty per Space with its own Postgres,
// Redis and secrets; no published port; an internal network with no way out; a service user and one
// API key made by script, no browser; the instance admin credential used here and kept out of the
// running gateway; the front end replaced by an empty directory.
//
// Everything that touches the machine goes through a `runner` (docker, files), so the whole thing is
// tested without Docker. testbox runs it for real (stores/twenty/live).

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { execFile } from "node:child_process";

export const TWENTY_IMAGE = "twentycrm/twenty";
/** The release this build was tested against. Upgrades are explicit. */
export const TWENTY_TESTED_TAG = "v2.44.0";
export const POSTGRES_IMAGE = "postgres:16";
export const REDIS_IMAGE = "redis:7";

/** @param {string} space */
export const SPACE_RE = /^[a-z][a-z0-9-]{0,30}$/;
const need = (/** @type {string} */ space) => { if (!SPACE_RE.test(space)) throw new Error(`A space name is lowercase letters, digits and dashes: ${space}`); };

/** The names a Space's Twenty uses on the machine. @param {string} space */
export function names(space) {
  need(space);
  return { project: `vyre-${space}-twenty`, network: `vyre-${space}-twenty_store`, serverAlias: `twenty-${space}`, gatewayAlias: `vyre-${space}`, volumes: { db: `vyre-${space}-twenty_db-data`, files: `vyre-${space}-twenty_server-data` } };
}

/**
 * The compose file for one Space. Pure. Nothing here publishes a port; the network is internal.
 * @param {{ space: string, tag?: string, hookPort?: number }} o
 */
export function composeFile(o) {
  const n = names(o.space);
  const tag = o.tag ?? TWENTY_TESTED_TAG;
  const env = [
    "NODE_PORT: 3000",
    "PG_DATABASE_URL: postgres://postgres:${PG_PASSWORD}@db:5432/default",
    "REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379",
    `SERVER_URL: http://${n.serverAlias}:3000`,
    "APP_SECRET: ${APP_SECRET}",
    "ENCRYPTION_KEY: ${ENCRYPTION_KEY}",
    `OUTBOUND_HTTP_ALLOWED_INTERNAL_HOSTS: ${n.gatewayAlias}`,
    'API_RATE_LIMITING_SHORT_LIMIT: "2000"',
    'API_RATE_LIMITING_LONG_LIMIT: "100000"',
    'DISABLE_CRON_JOBS_REGISTRATION: "true"',
    'IS_EMAIL_VERIFICATION_REQUIRED: "false"',
    'IS_MULTIWORKSPACE_ENABLED: "false"',
  ];
  const envBlock = (extra = []) => [...env, ...extra].map((l) => `      ${l}`).join("\n");
  return `# Generated by Vyre for the space "${o.space}". Do not edit: provisioning rewrites this file.
name: ${n.project}
services:
  server:
    image: ${TWENTY_IMAGE}:\${TWENTY_TAG:-${tag}}
    restart: unless-stopped
    networks:
      store:
        aliases: [${n.serverAlias}]
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
      - ./empty-front:/app/packages/twenty-server/dist/front:ro
    environment:
${envBlock()}
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    healthcheck: { test: "curl --fail http://localhost:3000/healthz", interval: 5s, timeout: 5s, retries: 80 }
  worker:
    image: ${TWENTY_IMAGE}:\${TWENTY_TAG:-${tag}}
    restart: unless-stopped
    command: ["yarn", "worker:prod"]
    networks: [store]
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
    environment:
${envBlock(['DISABLE_DB_MIGRATIONS: "true"'])}
    depends_on:
      server: { condition: service_healthy }
  db:
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    networks: [store]
    volumes: [db-data:/var/lib/postgresql/data]
    environment: { POSTGRES_DB: default, POSTGRES_USER: postgres, POSTGRES_PASSWORD: "\${PG_PASSWORD}" }
    healthcheck: { test: "pg_isready -U postgres -h localhost -d default", interval: 5s, timeout: 5s, retries: 20 }
  redis:
    image: ${REDIS_IMAGE}
    restart: unless-stopped
    networks: [store]
    command: ["redis-server", "--maxmemory-policy", "noeviction", "--requirepass", "\${REDIS_PASSWORD}"]
    healthcheck: { test: ["CMD-SHELL", "redis-cli -a \\"$$REDIS_PASSWORD\\" ping | grep PONG"], interval: 5s, timeout: 5s, retries: 20 }
    environment: { REDIS_PASSWORD: "\${REDIS_PASSWORD}" }
networks:
  store:
    internal: true
volumes:
  db-data:
    name: ${n.volumes.db}
  server-data:
    name: ${n.volumes.files}
`;
}

/**
 * The firewall rules the box applies for this Space (an owner-based rule: agent uids cannot open a
 * connection to the store network). Returned as text for the box's own firewall step; the provisioning
 * test only checks they are generated, since applying them needs root on the box.
 * @param {{ space: string, subnet: string, agentUidMin?: number }} o
 */
export function firewallRules(o) {
  need(o.space);
  if (!/^\d+\.\d+\.\d+\.\d+\/\d+$/.test(o.subnet)) throw new Error("subnet looks like 172.30.4.0/24");
  const min = o.agentUidMin ?? 2000;
  return [
    `# vyre ${o.space}: agents cannot reach this Space's Twenty, and Twenty cannot reach out`,
    `iptables -I OUTPUT -d ${o.subnet} -m owner --uid-owner ${min}-4294967294 -j REJECT`,
    `iptables -I DOCKER-USER -s ${o.subnet} ! -d ${o.subnet} -j DROP`,
    `iptables -I DOCKER-USER -d ${o.subnet} -m owner --uid-owner ${min}-4294967294 -j REJECT`,
  ].join("\n") + "\n";
}

/**
 * @typedef {{ exec: (cmd: string, args: string[], opts?: { cwd?: string, input?: string }) => Promise<{ stdout: string, stderr: string }>,
 *   fetch: typeof fetch, sleep: (ms: number) => Promise<void> }} Runner
 */
/** The real runner: docker on this machine. @returns {Runner} */
export function realRunner() {
  return {
    exec: (cmd, args, opts = {}) => new Promise((resolve, reject) => {
      const p = execFile(cmd, args, { cwd: opts.cwd, maxBuffer: 64 * 1024 * 1024 }, (err, stdout, stderr) => (err ? reject(Object.assign(new Error(`${cmd} ${args.slice(0, 3).join(" ")} failed: ${String(stderr || err.message).slice(0, 400)}`), { stdout, stderr })) : resolve({ stdout, stderr })));
      if (opts.input) p.stdin?.end(opts.input);
    }),
    fetch,
    sleep: (ms) => new Promise((r) => setTimeout(r, ms)),
  };
}

const secret = (/** @type {number} */ n) => crypto.randomBytes(n).toString("hex");
/** @param {string} file @param {string} text */
const writePrivate = (file, text) => { fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 }); fs.writeFileSync(file, text, { mode: 0o600 }); fs.chmodSync(file, 0o600); };

/** Where a Space's Twenty keeps its files. @param {string} home @param {string} space */
export function spaceDir(home, space) { need(space); return path.join(home, "spaces", space, "twenty"); }

/**
 * @typedef {{ home: string, space: string, runner?: Runner, tag?: string, gatewayContainer?: string | null,
 *   reach?: "alias" | "ip", log?: (line: string) => void }} ProvisionOptions
 * @typedef {{ space: string, dir: string, url: string, origin: string, keyFile: string, workspaceId: string, network: string,
 *   serverAlias: string, gatewayAlias: string, webhookSecretFile: string, tag: string }} Provisioned
 */

/**
 * Bring a Space's Twenty up and make its one service credential. Idempotent on a Space that is already
 * provisioned (returns what is on disk). The instance admin credential lives in admin.secret (0600), read
 * only by provisioning and upgrade, never by the gateway.
 * @param {ProvisionOptions} o @returns {Promise<Provisioned>}
 */
export async function provisionSpace(o) {
  const n = names(o.space);
  const runner = o.runner ?? realRunner();
  const log = o.log ?? (() => {});
  const dir = spaceDir(o.home, o.space);
  const tag = o.tag ?? TWENTY_TESTED_TAG;
  const keyFile = path.join(dir, "service.key");
  const origin = `http://${n.serverAlias}:3000`;
  const base = { space: o.space, dir, origin, keyFile, network: n.network, serverAlias: n.serverAlias, gatewayAlias: n.gatewayAlias, webhookSecretFile: path.join(dir, "webhook.secret"), tag };
  if (fs.existsSync(keyFile) && fs.existsSync(path.join(dir, "workspace.id"))) {
    const url = await reachUrl(o, runner, n, origin);
    return { ...base, url, workspaceId: fs.readFileSync(path.join(dir, "workspace.id"), "utf8").trim() };
  }
  fs.mkdirSync(path.join(dir, "empty-front"), { recursive: true, mode: 0o700 });
  fs.mkdirSync(path.join(dir, "state"), { recursive: true, mode: 0o700 });
  fs.mkdirSync(path.join(dir, "backups"), { recursive: true, mode: 0o700 });
  writePrivate(path.join(dir, ".env"), `TWENTY_TAG=${tag}\nPG_PASSWORD=${secret(16)}\nREDIS_PASSWORD=${secret(16)}\nAPP_SECRET=${secret(32)}\nENCRYPTION_KEY=${secret(32)}\n`);
  writePrivate(path.join(dir, "compose.yml"), composeFile({ space: o.space, tag }));
  writePrivate(path.join(dir, "webhook.secret"), secret(24));
  log("starting Twenty");
  await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "up", "-d", "--wait"], { cwd: dir });
  if (o.gatewayContainer) await runner.exec("docker", ["network", "connect", "--alias", n.gatewayAlias, n.network, o.gatewayContainer]).catch((e) => { if (!/already exists/i.test(String(e.message))) throw e; });
  const url = await reachUrl(o, runner, n, origin);
  await waitHealthy(runner, url);
  log("creating the service user, workspace and key");
  const adminPass = secret(24);
  const adminEmail = `service@${o.space}.vyre.invalid`;
  writePrivate(path.join(dir, "admin.secret"), JSON.stringify({ email: adminEmail, password: adminPass }));
  const r = await bootstrap({ runner, url, origin, email: adminEmail, password: adminPass, displayName: o.space });
  writePrivate(keyFile, r.apiKey);
  writePrivate(path.join(dir, "workspace.id"), r.workspaceId);
  return { ...base, url, workspaceId: r.workspaceId };
}

/** @param {ProvisionOptions} o @param {Runner} runner @param {ReturnType<typeof names>} n @param {string} origin */
async function reachUrl(o, runner, n, origin) {
  if ((o.reach ?? "alias") === "alias") return origin;
  const out = await runner.exec("docker", ["inspect", "-f", `{{(index .NetworkSettings.Networks "${n.network}").IPAddress}}`, `${n.project}-server-1`]);
  const ip = out.stdout.trim();
  if (!/^\d+\.\d+\.\d+\.\d+$/.test(ip)) throw new Error("Could not find the Twenty server's address on its network");
  return `http://${ip}:3000`;
}

/** @param {Runner} runner @param {string} url */
async function waitHealthy(runner, url, tries = 90) {
  for (let i = 0; i < tries; i++) {
    try { const r = await runner.fetch(`${url}/healthz`); if (r.ok) return; } catch { /* not up yet */ }
    await runner.sleep(2000);
  }
  throw new Error("Twenty did not become healthy in time");
}

/**
 * Create the service user, the workspace and the API key, headlessly (spike 2026-10-03: 8 s).
 * The user's password is the "instance admin credential" and is returned to the caller to keep out of the gateway.
 * @param {{ runner: Runner, url: string, origin: string, email: string, password: string, displayName: string }} o
 */
export async function bootstrap(o) {
  const gq = async (/** @type {string} */ query, /** @type {string | undefined} */ token) => {
    const res = await o.runner.fetch(`${o.url}/metadata`, { method: "POST", headers: { "content-type": "application/json", origin: o.origin, ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ query }) });
    const j = /** @type {any} */ (await res.json());
    if (j.errors) throw new Error(`Twenty bootstrap failed: ${String(j.errors[0]?.message).slice(0, 200)}`);
    return j.data;
  };
  const q = (/** @type {string} */ s) => JSON.stringify(s);
  let signUp;
  try { signUp = (await gq(`mutation Boot_signUp { signUp(email: ${q(o.email)}, password: ${q(o.password)}) { tokens { accessOrWorkspaceAgnosticToken { token } } } }`)).signUp; }
  catch { signUp = (await gq(`mutation Boot_signIn { signIn(email: ${q(o.email)}, password: ${q(o.password)}) { tokens { accessOrWorkspaceAgnosticToken { token } } } }`)).signIn; }
  const agnostic = signUp.tokens.accessOrWorkspaceAgnosticToken.token;
  const nw = (await gq(`mutation Boot_workspace { signUpInNewWorkspace(input: { displayName: ${q(o.displayName)} }) { loginToken { token } workspace { id } } }`, agnostic)).signUpInNewWorkspace;
  const tk = await gq(`mutation Boot_login { getAuthTokensFromLoginToken(loginToken: ${q(nw.loginToken.token)}, origin: ${q(o.origin)}) { tokens { accessOrWorkspaceAgnosticToken { token } } } }`);
  const access = tk.getAuthTokensFromLoginToken.tokens.accessOrWorkspaceAgnosticToken.token;
  await gq("mutation Boot_activate { activateWorkspace(data: {}) { id } }", access);
  const roles = await gq("query Boot_roles { getRoles { id label } }", access);
  const role = roles.getRoles.find((/** @type {any} */ r) => r.label === "Admin") ?? roles.getRoles[0];
  const exp = new Date(Date.now() + 365 * 864e5).toISOString();
  const ak = await gq(`mutation Boot_key { createApiKey(input: { name: "vyre-gateway", expiresAt: ${q(exp)}, roleId: ${q(role.id)} }) { id } }`, access);
  const tok = await gq(`mutation Boot_token { generateApiKeyToken(apiKeyId: ${q(ak.createApiKey.id)}, expiresAt: ${q(exp)}) { token } }`, access);
  await gq("mutation Boot_close { updateWorkspace(data: { isPasswordAuthEnabled: false }) { id } }", access).catch(() => {});
  return { workspaceId: nw.workspace.id, apiKey: tok.generateApiKeyToken.token, apiKeyId: ak.createApiKey.id };
}

/**
 * Upgrade a Space's Twenty: back up the database, change the image, wait until healthy, then run
 * `verify` (the conformance and isolation tests) before the store reopens. A failure restores the
 * dump and the old image together and re-runs verify.
 * @param {ProvisionOptions & { toTag: string, verify: () => Promise<void> }} o
 * @returns {Promise<{ ok: boolean, from: string, to: string, backup: string, rolledBack: boolean, seconds: number }>}
 */
export async function upgradeSpace(o) {
  const n = names(o.space); const runner = o.runner ?? realRunner(); const dir = spaceDir(o.home, o.space);
  const envFile = path.join(dir, ".env");
  const env = fs.readFileSync(envFile, "utf8");
  const from = /^TWENTY_TAG=(.*)$/m.exec(env)?.[1] ?? "";
  const t0 = Date.now();
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backup = path.join(dir, "backups", `pre-${o.toTag}-${stamp}.dump`);
  const dump = await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "exec", "-T", "db", "pg_dump", "-U", "postgres", "--clean", "--if-exists", "--no-owner", "default"], { cwd: dir });
  writePrivate(backup, dump.stdout);
  const setTag = (/** @type {string} */ t) => writePrivate(envFile, env.replace(/^TWENTY_TAG=.*$/m, `TWENTY_TAG=${t}`));
  setTag(o.toTag);
  try {
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "up", "-d", "--wait"], { cwd: dir });
    await o.verify();
    return { ok: true, from, to: o.toTag, backup, rolledBack: false, seconds: Math.round((Date.now() - t0) / 1000) };
  } catch (e) {
    setTag(from);
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "stop", "server", "worker"], { cwd: dir });
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "exec", "-T", "db", "psql", "-U", "postgres", "-d", "postgres", "-c", "DROP DATABASE default WITH (FORCE)", "-c", "CREATE DATABASE default"], { cwd: dir });
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "exec", "-T", "db", "psql", "-U", "postgres", "-d", "default", "-v", "ON_ERROR_STOP=1"], { cwd: dir, input: dump.stdout });
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "up", "-d", "--wait"], { cwd: dir });
    await o.verify();
    return { ok: false, from, to: o.toTag, backup, rolledBack: true, seconds: Math.round((Date.now() - t0) / 1000) };
  }
}
