// @ts-check
// Per-Space provisioning of Twenty (spec 3.7, R5-15): one Twenty per Space with its own Postgres,
// Redis and secrets; no published port; an internal network with no way out; a service user and one
// API key made by script, no browser; the instance admin credential used here and kept out of the
// running gateway; the front end replaced by an empty directory.
//
// Everything that touches the machine goes through a `runner` (docker, files), so the whole thing is
// tested without Docker. testbox runs it for real (stores/twenty/live).

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { execFile } from "node:child_process";

export const TWENTY_IMAGE = "twentycrm/twenty";
/** The release this build was tested against. Upgrades are explicit. */
export const TWENTY_TESTED_TAG = "v2.44.0";
export const POSTGRES_IMAGE = "postgres:16";
export const REDIS_IMAGE = "redis:7";

/** @param {string} space */
export const SPACE_RE = /^[a-z][a-z0-9-]{0,30}$/;
const need = (/** @type {string} */ space) => { if (!SPACE_RE.test(space)) throw new Error(`A space name is lowercase letters, digits and dashes: ${space}`); };

/** The names a Space's Twenty uses on the machine. @param {string} space */
export function names(space) {
  need(space);
  return { project: `vyre-${space}-twenty`, network: `vyre-${space}-twenty_store`, serverAlias: `twenty-${space}`, gatewayAlias: `vyre-${space}`, volumes: { db: `vyre-${space}-twenty_db-data`, files: `vyre-${space}-twenty_server-data` } };
}

/**
 * Memory limits in MB for one Space's four containers. `small` is for a Space on a small box (a few people, a few thousand
 * records): it is measured, not guessed (see docs/work/records.md for the runs). `standard` leaves Docker's default (none).
 * A caller may give its own numbers.
 */
export const MEMORY_PROFILES = Object.freeze({
  small: Object.freeze({ server: 1536, worker: 1024, db: 256, redis: 96 }),
  standard: null,
});
/** @param {string | { server: number, worker: number, db: number, redis: number } | null | undefined} m */
export function memoryOf(m) {
  if (m === undefined || m === null) return null;
  if (typeof m === "string") { if (!(m in MEMORY_PROFILES)) throw new Error(`memory is one of ${Object.keys(MEMORY_PROFILES).join(", ")} or four numbers`); return /** @type {any} */ (MEMORY_PROFILES)[m]; }
  for (const k of ["server", "worker", "db", "redis"]) if (!Number.isInteger(/** @type {any} */ (m)[k]) || /** @type {any} */ (m)[k] < 32) throw new Error(`memory.${k} is whole megabytes, at least 32`);
  return m;
}

/**
 * The compose file for one Space. Pure. Nothing here publishes a port; the network is internal.
 * `memory` caps each container (a Node heap is set below its container's limit so it collects before the kernel kills it).
 * @param {{ space: string, tag?: string, hookPort?: number, memory?: Parameters<typeof memoryOf>[0] }} o
 */
export function composeFile(o) {
  const n = names(o.space);
  const tag = o.tag ?? TWENTY_TESTED_TAG;
  const env = [
    "NODE_PORT: 3000",
    "PG_DATABASE_URL: postgres://postgres:${PG_PASSWORD}@db:5432/default",
    "REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379",
    `SERVER_URL: http://${n.serverAlias}:3000`,
    "APP_SECRET: ${APP_SECRET}",
    "ENCRYPTION_KEY: ${ENCRYPTION_KEY}",
    `OUTBOUND_HTTP_ALLOWED_INTERNAL_HOSTS: ${n.gatewayAlias}`,
    'API_RATE_LIMITING_SHORT_LIMIT: "2000"',
    'API_RATE_LIMITING_LONG_LIMIT: "100000"',
    'DISABLE_CRON_JOBS_REGISTRATION: "true"',
    'IS_EMAIL_VERIFICATION_REQUIRED: "false"',
    'IS_MULTIWORKSPACE_ENABLED: "false"',
  ];
  const mem = memoryOf(o.memory);
  const heap = (/** @type {number} */ mb) => `NODE_OPTIONS: "--max-old-space-size=${Math.max(96, Math.floor(mb * 0.7))}"`;
  const envBlock = (extra = [], /** @type {number | undefined} */ mb = undefined) => [...env, ...(mem && mb ? [heap(mb)] : []), ...extra].map((l) => `      ${l}`).join("\n");
  const cap = (/** @type {number | undefined} */ mb) => (mem && mb ? `\n    mem_limit: ${mb}m\n    memswap_limit: ${mb}m` : "");
  return `# Generated by Vyre for the space "${o.space}". Do not edit: provisioning rewrites this file.
name: ${n.project}
services:
  server:
    image: ${TWENTY_IMAGE}:\${TWENTY_TAG:-${tag}}
    restart: unless-stopped${cap(mem?.server)}
    networks:
      store:
        aliases: [${n.serverAlias}]
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
      - ./empty-front:/app/packages/twenty-server/dist/front:ro
    environment:
${envBlock([], mem?.server)}
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    healthcheck: { test: "curl --fail http://localhost:3000/healthz", interval: 5s, timeout: 5s, retries: 80 }
  worker:
    image: ${TWENTY_IMAGE}:\${TWENTY_TAG:-${tag}}
    restart: unless-stopped
    command: ["yarn", "worker:prod"]${cap(mem?.worker)}
    networks: [store]
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
    environment:
${envBlock(['DISABLE_DB_MIGRATIONS: "true"'], mem?.worker)}
    depends_on:
      server: { condition: service_healthy }
  db:
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped${cap(mem?.db)}${mem ? `\n    command: ["postgres", "-c", "shared_buffers=${Math.floor(mem.db / 4)}MB", "-c", "max_connections=60", "-c", "work_mem=4MB"]` : ""}
    networks: [store]
    volumes: [db-data:/var/lib/postgresql/data]
    environment: { POSTGRES_DB: default, POSTGRES_USER: postgres, POSTGRES_PASSWORD: "\${PG_PASSWORD}" }
    healthcheck: { test: "pg_isready -U postgres -h localhost -d default", interval: 5s, timeout: 5s, retries: 20 }
  redis:
    image: ${REDIS_IMAGE}
    restart: unless-stopped${cap(mem?.redis)}
    networks: [store]
    command: ["redis-server", "--maxmemory-policy", "noeviction"${mem ? `, "--maxmemory", "${Math.floor(mem.redis * 0.75)}mb"` : ""}, "--requirepass", "\${REDIS_PASSWORD}"]
    healthcheck: { test: ["CMD-SHELL", "redis-cli -a \\"$$REDIS_PASSWORD\\" ping | grep PONG"], interval: 5s, timeout: 5s, retries: 20 }
    environment: { REDIS_PASSWORD: "\${REDIS_PASSWORD}" }
networks:
  store:
    internal: true
volumes:
  db-data:
    name: ${n.volumes.db}
  server-data:
    name: ${n.volumes.files}
`;
}

/**
 * The firewall rules the box applies for this Space (an owner-based rule: agent uids cannot open a
 * connection to the store network). Returned as text for the box's own firewall step; the provisioning
 * test only checks they are generated, since applying them needs root on the box.
 * @param {{ space: string, subnet: string, agentUidMin?: number }} o
 */
export function firewallRules(o) {
  need(o.space);
  if (!/^\d+\.\d+\.\d+\.\d+\/\d+$/.test(o.subnet)) throw new Error("subnet looks like 172.30.4.0/24");
  const min = o.agentUidMin ?? 2000;
  return [
    `# vyre ${o.space}: agents cannot reach this Space's Twenty, and Twenty cannot reach out`,
    `iptables -I OUTPUT -d ${o.subnet} -m owner --uid-owner ${min}-4294967294 -j REJECT`,
    `iptables -I DOCKER-USER -s ${o.subnet} ! -d ${o.subnet} -j DROP`,
    `iptables -I DOCKER-USER -d ${o.subnet} -m owner --uid-owner ${min}-4294967294 -j REJECT`,
  ].join("\n") + "\n";
}

/**
 * @typedef {{ exec: (cmd: string, args: string[], opts?: { cwd?: string, input?: string }) => Promise<{ stdout: string, stderr: string }>,
 *   fetch: typeof fetch, sleep: (ms: number) => Promise<void> }} Runner
 */
/** The real runner: docker on this machine. @returns {Runner} */
export function realRunner() {
  return {
    exec: (cmd, args, opts = {}) => new Promise((resolve, reject) => {
      const p = execFile(cmd, args, { cwd: opts.cwd, maxBuffer: 64 * 1024 * 1024 }, (err, stdout, stderr) => (err ? reject(Object.assign(new Error(`${cmd} ${args.slice(0, 3).join(" ")} failed: ${String(stderr || err.message).slice(0, 400)}`), { stdout, stderr })) : resolve({ stdout, stderr })));
      if (opts.input) p.stdin?.end(opts.input);
    }),
    fetch,
    sleep: (ms) => new Promise((r) => setTimeout(r, ms)),
  };
}

const secret = (/** @type {number} */ n) => crypto.randomBytes(n).toString("hex");
/** @param {string} file @param {string} text */
const writePrivate = (file, text) => { fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 }); fs.writeFileSync(file, text, { mode: 0o600 }); fs.chmodSync(file, 0o600); };

/** Where a Space's Twenty keeps its files. @param {string} home @param {string} space */
export function spaceDir(home, space) { need(space); return path.join(home, "spaces", space, "twenty"); }

/**
 * @typedef {{ home: string, space: string, runner?: Runner, tag?: string, gatewayContainer?: string | null,
 *   reach?: "alias" | "ip", memory?: Parameters<typeof memoryOf>[0], log?: (line: string) => void }} ProvisionOptions
 * @typedef {{ space: string, dir: string, url: string, origin: string, keyFile: string, workspaceId: string, network: string,
 *   serverAlias: string, gatewayAlias: string, webhookSecretFile: string, tag: string }} Provisioned
 */

/**
 * Bring a Space's Twenty up and make its one service credential. Idempotent on a Space that is already
 * provisioned (returns what is on disk). The instance admin credential lives in admin.secret (0600), read
 * only by provisioning and upgrade, never by the gateway.
 * @param {ProvisionOptions} o @returns {Promise<Provisioned>}
 */
export async function provisionSpace(o) {
  const n = names(o.space);
  const runner = o.runner ?? realRunner();
  const log = o.log ?? (() => {});
  const dir = spaceDir(o.home, o.space);
  const tag = o.tag ?? TWENTY_TESTED_TAG;
  const keyFile = path.join(dir, "service.key");
  const origin = `http://${n.serverAlias}:3000`;
  const base = { space: o.space, dir, origin, keyFile, network: n.network, serverAlias: n.serverAlias, gatewayAlias: n.gatewayAlias, webhookSecretFile: path.join(dir, "webhook.secret"), tag };
  if (fs.existsSync(keyFile) && fs.existsSync(path.join(dir, "workspace.id"))) {
    const url = await reachUrl(o, runner, n, origin);
    return { ...base, url, workspaceId: fs.readFileSync(path.join(dir, "workspace.id"), "utf8").trim() };
  }
  fs.mkdirSync(path.join(dir, "empty-front"), { recursive: true, mode: 0o700 });
  fs.mkdirSync(path.join(dir, "state"), { recursive: true, mode: 0o700 });
  fs.mkdirSync(path.join(dir, "backups"), { recursive: true, mode: 0o700 });
  writePrivate(path.join(dir, ".env"), `TWENTY_TAG=${tag}\nPG_PASSWORD=${secret(16)}\nREDIS_PASSWORD=${secret(16)}\nAPP_SECRET=${secret(32)}\nENCRYPTION_KEY=${secret(32)}\n`);
  writePrivate(path.join(dir, "compose.yml"), composeFile({ space: o.space, tag, memory: o.memory }));
  if (o.memory !== undefined) writePrivate(path.join(dir, "memory.json"), JSON.stringify(o.memory));
  writePrivate(path.join(dir, "webhook.secret"), secret(24));
  // Each phase is timed and logged, so a slow create says which part is slow (the screen that waits on this shows the same phases).
  const phase = async (/** @type {string} */ name, /** @type {() => Promise<any>} */ fn) => { const t = Date.now(); const r = await fn(); log(`phase ${name}: ${((Date.now() - t) / 1000).toFixed(1)}s`); return r; };
  await phase("pull images", () => runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "pull", "--quiet"], { cwd: dir }));
  await phase("start database and cache", () => runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "up", "-d", "--wait", "db", "redis"], { cwd: dir }));
  await phase("start Records (migrations, first healthy answer)", () => runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "up", "-d", "--wait"], { cwd: dir }));
  if (o.gatewayContainer) await runner.exec("docker", ["network", "connect", "--alias", n.gatewayAlias, n.network, o.gatewayContainer]).catch((e) => { if (!/already exists/i.test(String(e.message))) throw e; });
  const url = await reachUrl(o, runner, n, origin);
  await waitHealthy(runner, url);
  log("creating the service user, workspace and key");
  const adminPass = secret(24);
  const adminEmail = `service@${o.space}.vyre.invalid`;
  writePrivate(path.join(dir, "admin.secret"), JSON.stringify({ email: adminEmail, password: adminPass }));
  const r = await phase("workspace and key", () => bootstrap({ runner, url, origin, email: adminEmail, password: adminPass, displayName: o.space }));
  writePrivate(keyFile, r.apiKey);
  writePrivate(path.join(dir, "key.json"), JSON.stringify({ apiKeyId: r.apiKeyId, expiresAt: r.expiresAt, createdAt: new Date().toISOString() }));
  writePrivate(path.join(dir, "workspace.id"), r.workspaceId);
  return { ...base, url, workspaceId: r.workspaceId };
}

/** @param {ProvisionOptions} o @param {Runner} runner @param {ReturnType<typeof names>} n @param {string} origin */
async function reachUrl(o, runner, n, origin) {
  if ((o.reach ?? "alias") === "alias") return origin;
  const out = await runner.exec("docker", ["inspect", "-f", `{{(index .NetworkSettings.Networks "${n.network}").IPAddress}}`, `${n.project}-server-1`]);
  const ip = out.stdout.trim();
  if (!/^\d+\.\d+\.\d+\.\d+$/.test(ip)) throw new Error("Could not find the Records server's address on its network");
  return `http://${ip}:3000`;
}

/** @param {Runner} runner @param {string} url */
async function waitHealthy(runner, url, tries = 90) {
  for (let i = 0; i < tries; i++) {
    try { const r = await runner.fetch(`${url}/healthz`); if (r.ok) return; } catch { /* not up yet */ }
    await runner.sleep(2000);
  }
  throw new Error("Records did not become healthy in time");
}

/**
 * Create the service user, the workspace and the API key, headlessly (spike 2026-10-03: 8 s).
 * The user's password is the "instance admin credential" and is returned to the caller to keep out of the gateway.
 * @param {{ runner: Runner, url: string, origin: string, email: string, password: string, displayName: string }} o
 */
export async function bootstrap(o) {
  const gq = async (/** @type {string} */ query, /** @type {string | undefined} */ token) => {
    const res = await o.runner.fetch(`${o.url}/metadata`, { method: "POST", headers: { "content-type": "application/json", origin: o.origin, ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ query }) });
    const j = /** @type {any} */ (await res.json());
    if (j.errors) throw new Error(`Records bootstrap failed: ${String(j.errors[0]?.message).slice(0, 200)}`);
    return j.data;
  };
  const q = (/** @type {string} */ s) => JSON.stringify(s);
  let signUp;
  try { signUp = (await gq(`mutation Boot_signUp { signUp(email: ${q(o.email)}, password: ${q(o.password)}) { tokens { accessOrWorkspaceAgnosticToken { token } } } }`)).signUp; }
  catch { signUp = (await gq(`mutation Boot_signIn { signIn(email: ${q(o.email)}, password: ${q(o.password)}) { tokens { accessOrWorkspaceAgnosticToken { token } } } }`)).signIn; }
  const agnostic = signUp.tokens.accessOrWorkspaceAgnosticToken.token;
  const nw = (await gq(`mutation Boot_workspace { signUpInNewWorkspace(input: { displayName: ${q(o.displayName)} }) { loginToken { token } workspace { id } } }`, agnostic)).signUpInNewWorkspace;
  const tk = await gq(`mutation Boot_login { getAuthTokensFromLoginToken(loginToken: ${q(nw.loginToken.token)}, origin: ${q(o.origin)}) { tokens { accessOrWorkspaceAgnosticToken { token } } } }`);
  const access = tk.getAuthTokensFromLoginToken.tokens.accessOrWorkspaceAgnosticToken.token;
  await gq("mutation Boot_activate { activateWorkspace(data: {}) { id } }", access);
  const roles = await gq("query Boot_roles { getRoles { id label } }", access);
  const role = roles.getRoles.find((/** @type {any} */ r) => r.label === "Admin") ?? roles.getRoles[0];
  const exp = new Date(Date.now() + 365 * 864e5).toISOString();
  const ak = await gq(`mutation Boot_key { createApiKey(input: { name: "vyre-gateway", expiresAt: ${q(exp)}, roleId: ${q(role.id)} }) { id } }`, access);
  const tok = await gq(`mutation Boot_token { generateApiKeyToken(apiKeyId: ${q(ak.createApiKey.id)}, expiresAt: ${q(exp)}) { token } }`, access);
  await gq("mutation Boot_close { updateWorkspace(data: { isPasswordAuthEnabled: false }) { id } }", access).catch(() => {});
  return { workspaceId: nw.workspace.id, apiKey: tok.generateApiKeyToken.token, apiKeyId: ak.createApiKey.id, expiresAt: exp };
}

/**
 * Upgrade a Space's Twenty: back up the database, change the image, wait until healthy, then run
 * `verify` (the conformance and isolation tests) before the store reopens. A failure restores the
 * dump and the old image together and re-runs verify.
 * @param {ProvisionOptions & { toTag: string, verify: () => Promise<void> }} o
 * @returns {Promise<{ ok: boolean, from: string, to: string, backup: string, rolledBack: boolean, seconds: number }>}
 */
export async function upgradeSpace(o) {
  const n = names(o.space); const runner = o.runner ?? realRunner(); const dir = spaceDir(o.home, o.space);
  const envFile = path.join(dir, ".env");
  const env = fs.readFileSync(envFile, "utf8");
  const from = /^TWENTY_TAG=(.*)$/m.exec(env)?.[1] ?? "";
  const t0 = Date.now();
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backup = path.join(dir, "backups", `pre-${o.toTag}-${stamp}.dump`);
  const dump = await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "exec", "-T", "db", "pg_dump", "-U", "postgres", "--clean", "--if-exists", "--no-owner", "default"], { cwd: dir });
  writePrivate(backup, dump.stdout);
  const setTag = (/** @type {string} */ t) => writePrivate(envFile, env.replace(/^TWENTY_TAG=.*$/m, `TWENTY_TAG=${t}`));
  setTag(o.toTag);
  try {
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "up", "-d", "--wait"], { cwd: dir });
    await o.verify();
    return { ok: true, from, to: o.toTag, backup, rolledBack: false, seconds: Math.round((Date.now() - t0) / 1000) };
  } catch (e) {
    setTag(from);
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "stop", "server", "worker"], { cwd: dir });
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "exec", "-T", "db", "psql", "-U", "postgres", "-d", "postgres", "-c", "DROP DATABASE default WITH (FORCE)", "-c", "CREATE DATABASE default"], { cwd: dir });
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "exec", "-T", "db", "psql", "-U", "postgres", "-d", "default", "-v", "ON_ERROR_STOP=1"], { cwd: dir, input: dump.stdout });
    await runner.exec("docker", ["compose", "-f", "compose.yml", "--env-file", ".env", "up", "-d", "--wait"], { cwd: dir });
    await o.verify();
    return { ok: false, from, to: o.toTag, backup, rolledBack: true, seconds: Math.round((Date.now() - t0) / 1000) };
  }
}

const compose = (/** @type {string[]} */ ...a) => ["compose", "-f", "compose.yml", "--env-file", ".env", ...a];
const sha = (/** @type {Buffer | string} */ b) => crypto.createHash("sha256").update(b).digest("hex");

/**
 * A backup of one Space's Twenty and nothing else: the database (a plain SQL dump), the file volume, and the Space's folder
 * (compose file, secrets, the store's state). One folder, a manifest with a checksum of each part, mode 0600. It holds the
 * Space's secrets in the clear, so a caller encrypts it before it leaves the machine (the continuity bundle's age step).
 * The Space keeps running: pg_dump is a consistent snapshot, and the file volume is read-only.
 * @param {{ home: string, space: string, runner?: Runner, outDir?: string, log?: (line: string) => void }} o
 * @returns {Promise<{ dir: string, manifest: any, seconds: number }>}
 */
export async function backupSpace(o) {
  const n = names(o.space); const runner = o.runner ?? realRunner(); const dir = spaceDir(o.home, o.space); const log = o.log ?? (() => {});
  const t0 = Date.now();
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const out = path.join(o.outDir ?? path.join(dir, "backups"), `space-${o.space}-${stamp}`);
  fs.mkdirSync(out, { recursive: true, mode: 0o700 });
  const dump = await runner.exec("docker", compose("exec", "-T", "db", "pg_dump", "-U", "postgres", "--clean", "--if-exists", "--no-owner", "default"), { cwd: dir });
  writePrivate(path.join(out, "db.sql"), dump.stdout);
  log(`database dumped (${dump.stdout.length} bytes)`);
  const uid = typeof process.getuid === "function" ? `${process.getuid()}:${process.getgid?.() ?? 0}` : "0:0";
  await runner.exec("docker", ["run", "--rm", "-v", `${n.volumes.files}:/data:ro`, "-v", `${path.resolve(out)}:/out`, "alpine", "sh", "-c", `tar -C /data -czf /out/files.tgz . && chown ${uid} /out/files.tgz`], {});
  fs.chmodSync(path.join(out, "files.tgz"), 0o600);
  // the Space's own folder, without the backups folder and the empty front end
  const keep = ["compose.yml", ".env", "webhook.secret", "service.key", "workspace.id", "admin.secret", "memory.json"].filter((f) => fs.existsSync(path.join(dir, f)));
  /** @type {Record<string, string>} */ const folder = {};
  for (const f of keep) folder[f] = fs.readFileSync(path.join(dir, f), "utf8");
  const stateDir = path.join(dir, "state");
  /** @type {Record<string, string>} */ const state = {};
  if (fs.existsSync(stateDir)) for (const f of fs.readdirSync(stateDir)) { const p = path.join(stateDir, f); if (fs.statSync(p).isFile()) state[f] = fs.readFileSync(p, "utf8"); }
  writePrivate(path.join(out, "space.json"), JSON.stringify({ folder, state }));
  const tag = /^TWENTY_TAG=(.*)$/m.exec(folder[".env"] ?? "")?.[1] ?? TWENTY_TESTED_TAG;
  const manifest = { format: 1, space: o.space, tag, created_at: new Date().toISOString(), parts: Object.fromEntries(["db.sql", "files.tgz", "space.json"].map((f) => [f, { bytes: fs.statSync(path.join(out, f)).size, sha256: sha(fs.readFileSync(path.join(out, f))) }])) };
  writePrivate(path.join(out, "manifest.json"), JSON.stringify(manifest, null, 2));
  return { dir: out, manifest, seconds: Math.round((Date.now() - t0) / 100) / 10 };
}

/**
 * Bring a backup up as a Space on this machine: the same box after a loss, or another one (a move). `space` may be a new name:
 * the compose file is rewritten for it and the secrets are kept, so the service key still works (it is signed with the Space's
 * own APP_SECRET). Checks every part's checksum before it touches anything. Refuses a Space that is already provisioned here.
 * @param {{ home: string, space: string, from: string, runner?: Runner, reach?: "alias" | "ip", log?: (line: string) => void }} o
 * @returns {Promise<Provisioned & { seconds: number }>}
 */
export async function restoreSpace(o) {
  const n = names(o.space); const runner = o.runner ?? realRunner(); const dir = spaceDir(o.home, o.space); const log = o.log ?? (() => {});
  const t0 = Date.now();
  const manifest = JSON.parse(fs.readFileSync(path.join(o.from, "manifest.json"), "utf8"));
  for (const [f, m] of Object.entries(/** @type {Record<string, any>} */ (manifest.parts))) {
    if (sha(fs.readFileSync(path.join(o.from, f))) !== m.sha256) throw new Error(`The backup is damaged: ${f} does not match its checksum`);
  }
  if (fs.existsSync(path.join(dir, "service.key"))) throw new Error(`Space ${o.space} is already provisioned here; remove it first`);
  const sp = JSON.parse(fs.readFileSync(path.join(o.from, "space.json"), "utf8"));
  fs.mkdirSync(path.join(dir, "empty-front"), { recursive: true, mode: 0o700 });
  fs.mkdirSync(path.join(dir, "state"), { recursive: true, mode: 0o700 });
  fs.mkdirSync(path.join(dir, "backups"), { recursive: true, mode: 0o700 });
  for (const [f, text] of Object.entries(/** @type {Record<string, string>} */ (sp.folder))) if (f !== "compose.yml") writePrivate(path.join(dir, f), text);
  for (const [f, text] of Object.entries(/** @type {Record<string, string>} */ (sp.state))) writePrivate(path.join(dir, "state", f), text);
  const memory = fs.existsSync(path.join(dir, "memory.json")) ? JSON.parse(fs.readFileSync(path.join(dir, "memory.json"), "utf8")) : undefined;
  writePrivate(path.join(dir, "compose.yml"), composeFile({ space: o.space, tag: manifest.tag, memory }));
  log("starting the database");
  await runner.exec("docker", compose("up", "-d", "--wait", "db"), { cwd: dir });
  await runner.exec("docker", compose("exec", "-T", "db", "psql", "-U", "postgres", "-d", "default", "-v", "ON_ERROR_STOP=1"), { cwd: dir, input: fs.readFileSync(path.join(o.from, "db.sql"), "utf8") });
  log("database restored");
  const filesTgz = path.join(o.from, "files.tgz");
  if (fs.statSync(filesTgz).size > 0) {
    await runner.exec("docker", ["run", "--rm", "-v", `${n.volumes.files}:/data`, "-v", `${path.resolve(o.from)}:/in:ro`, "alpine", "tar", "-C", "/data", "-xzf", "/in/files.tgz"], {});
  }
  await runner.exec("docker", compose("up", "-d", "--wait"), { cwd: dir });
  const origin = `http://${n.serverAlias}:3000`;
  const url = await reachUrl({ home: o.home, space: o.space, reach: o.reach }, runner, n, origin);
  await waitHealthy(runner, url);
  const base = { space: o.space, dir, origin, keyFile: path.join(dir, "service.key"), network: n.network, serverAlias: n.serverAlias, gatewayAlias: n.gatewayAlias, webhookSecretFile: path.join(dir, "webhook.secret"), tag: manifest.tag };
  return { ...base, url, workspaceId: fs.readFileSync(path.join(dir, "workspace.id"), "utf8").trim(), seconds: Math.round((Date.now() - t0) / 100) / 10 };
}


// ---- the Space's API key: one year of life, rotated well before it ends --------------------------------------------------------------------------------
export const KEY_LIFE_DAYS = 365;
/** Rotate when fewer than this many days are left; warn loudly when fewer than WARN_DAYS are left and rotation has not worked. */
export const KEY_ROTATE_WITHIN_DAYS = 90;
export const KEY_WARN_DAYS = 30;

/** The expiry of a JWT-shaped key, in ms, or null. @param {string} token */
export function keyExpiry(token) {
  try { const exp = JSON.parse(Buffer.from(token.split(".")[1], "base64url").toString("utf8")).exp; return typeof exp === "number" ? exp * 1000 : null; } catch { return null; }
}

/**
 * Where a Space's key stands. `ok` is false when it has expired or cannot be read, `rotate` when it is inside the rotation window.
 * @param {{ home: string, space: string, now?: () => number }} o
 */
export function keyHealth(o) {
  const dir = spaceDir(o.home, o.space); const now = (o.now ?? Date.now)();
  let token = ""; try { token = fs.readFileSync(path.join(dir, "service.key"), "utf8").trim(); } catch { return { ok: false, rotate: true, daysLeft: null, expiresAt: null, why: "the Space's key file cannot be read" }; }
  const exp = keyExpiry(token);
  if (exp === null) return { ok: true, rotate: false, daysLeft: null, expiresAt: null, why: "the key carries no expiry" };
  const daysLeft = Math.floor((exp - now) / 864e5);
  return { ok: exp > now, rotate: daysLeft < KEY_ROTATE_WITHIN_DAYS, daysLeft, expiresAt: new Date(exp).toISOString(), ...(exp <= now ? { why: "the Space's key has expired" } : {}) };
}

/**
 * Make a new key for the Space, check it works, write it over the old one (0600, in one rename so a reader never sees half a key), then revoke the old.
 * Uses the instance admin credential kept for provisioning (admin.secret), never the running key. The store reads the key file on every call, so nothing restarts.
 * @param {{ home: string, space: string, runner?: Runner, now?: () => number, force?: boolean, url?: string, reach?: "alias" | "ip", log?: (line: string) => void }} o
 * @returns {Promise<{ rotated: boolean, expiresAt?: string, why?: string }>}
 */
export async function rotateApiKey(o) {
  const n = names(o.space); const runner = o.runner ?? realRunner(); const dir = spaceDir(o.home, o.space); const log = o.log ?? (() => {}); const now = (o.now ?? Date.now)();
  const h = keyHealth({ home: o.home, space: o.space, now: () => now });
  if (!o.force && !h.rotate) return { rotated: false, why: `${h.daysLeft} days left` };
  const admin = JSON.parse(fs.readFileSync(path.join(dir, "admin.secret"), "utf8"));
  const origin = `http://${n.serverAlias}:3000`;
  const url = o.url ?? await reachUrl({ home: o.home, space: o.space, reach: o.reach ?? "ip" }, runner, n, origin);
  const gq = async (/** @type {string} */ query, /** @type {string | undefined} */ token, /** @type {string | undefined} */ useKey) => {
    const res = await runner.fetch(`${url}/metadata`, { method: "POST", headers: { "content-type": "application/json", origin, ...(token || useKey ? { authorization: `Bearer ${token ?? useKey}` } : {}) }, body: JSON.stringify({ query }) });
    const j = /** @type {any} */ (await res.json());
    if (j.errors) throw new Error(`Records key rotation failed: ${String(j.errors[0]?.message).slice(0, 200)}`);
    return j.data;
  };
  const q = (/** @type {string} */ x) => JSON.stringify(x);
  const lt = await gq(`mutation Rot_loginToken { getLoginTokenFromCredentials(email: ${q(admin.email)}, password: ${q(admin.password)}, origin: ${q(origin)}) { loginToken { token } } }`, undefined, undefined);
  const tk = await gq(`mutation Rot_login { getAuthTokensFromLoginToken(loginToken: ${q(lt.getLoginTokenFromCredentials.loginToken.token)}, origin: ${q(origin)}) { tokens { accessOrWorkspaceAgnosticToken { token } } } }`, undefined, undefined);
  const access = tk.getAuthTokensFromLoginToken.tokens.accessOrWorkspaceAgnosticToken.token;
  const roles = await gq("query Rot_roles { getRoles { id label } }", access, undefined);
  const role = roles.getRoles.find((/** @type {any} */ r) => r.label === KEY_ROLE) ?? roles.getRoles.find((/** @type {any} */ r) => r.label === "Admin") ?? roles.getRoles[0];
  const exp = new Date(now + KEY_LIFE_DAYS * 864e5).toISOString();
  const ak = await gq(`mutation Rot_key { createApiKey(input: { name: "vyre-gateway", expiresAt: ${q(exp)}, roleId: ${q(role.id)} }) { id } }`, access, undefined);
  const tok = await gq(`mutation Rot_token { generateApiKeyToken(apiKeyId: ${q(ak.createApiKey.id)}, expiresAt: ${q(exp)}) { token } }`, access, undefined);
  const fresh = tok.generateApiKeyToken.token;
  await gq("query Rot_check { objects(paging: { first: 1 }) { edges { node { id } } } }", undefined, fresh); // the new key must work before it replaces the old
  const keyFile = path.join(dir, "service.key"); const prev = (() => { try { return JSON.parse(fs.readFileSync(path.join(dir, "key.json"), "utf8")); } catch { return {}; } })();
  fs.writeFileSync(`${keyFile}.new`, fresh, { mode: 0o600 }); fs.renameSync(`${keyFile}.new`, keyFile); fs.chmodSync(keyFile, 0o600);
  writePrivate(path.join(dir, "key.json"), JSON.stringify({ apiKeyId: ak.createApiKey.id, expiresAt: exp, rotatedAt: new Date(now).toISOString(), previous: prev.apiKeyId ?? null }));
  if (prev.apiKeyId) { try { await gq(`mutation Rot_revoke { revokeApiKey(input: { id: ${q(prev.apiKeyId)} }) { id } }`, access, undefined); } catch (e) { log(`the old key could not be revoked (it will expire on its own): ${/** @type {Error} */ (e).message}`); } }
  log(`key rotated; new expiry ${exp}`);
  return { rotated: true, expiresAt: exp };
}

/** The role the gateway's key takes. Admin until the narrowest role that works has been researched (docs/work/records.md). */
export const KEY_ROLE = "Admin";
