// core/modules/agent-reach.js: which `reach: person` tools the person's assistant may call. The user's rule (4 Oct 2026): an assistant can do what its person can, under that
// person's narrowed grants, so a person-reach tool is OPEN to an assistant unless there is a written reason to keep it the person's (PERSON_ONLY, one reason each, from a short
// set: it needs the person's Face ID or presence, it controls the person's own machine, it widens an assistant's own authority, it is the person's stop or steer over the
// assistant). ASK_FIRST tools are open but held for a one-tap task, like send, post and pay. A person-reach tool in none of the three lists is refused to an assistant until it
// is classified: the test that walks every manifest (kernel/retrofit/agent-reach.test.js) fails on it, so a new tool cannot slip in open or closed by default.
// Reviewed entries kept open on purpose: glass.take (the user's ruling that screen use is hands-free after one grant; the person's stop, hands.pause and chrome.pause, stays
// person-only, so the person can always take it back).
// Safe only because the claim is assigned by the daemon from the session's own socket (L-1), never self-declared on the person's own socket.

/** @type {ReadonlyMap<string, string>} */
export const PERSON_ONLY = new Map([
  ["memory.sealscan", "the person's own audit of where sensitive-looking values sit in memory: counts only, but it is the person's to ask"],
  ["vault.provider.set", "needs the person's Face ID or presence: changes which provider holds the Space's secrets"],
  ["vault.provider.remove", "needs the person's Face ID or presence: changes which provider holds the Space's secrets"],
  ["wink.server.pairing", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.server.pair.answer", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.server.release", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.server.reset.begin", "only the person at the server's own console: resetting a server"],
  ["wink.server.reset.confirm", "only the person at the server's own console: resetting a server"],
  ["network.wink.join", "changes this computer's own network: bringing a link up"],
  ["network.wink.leave", "changes this computer's own network: taking a link down"],
  ["wink.phone.pairing", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.phone.pair.answer", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.phone.wait", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge.accept", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge.drive", "needs the person's Face ID or presence: pairing and devices"],
  ["flows.approve", "needs the person's Face ID or presence: approving a Flow gives it authority"],
  ["flows.pause", "the person's stop over automation: an assistant must not be able to resume what its person paused"],
  ["flows.resume", "the person's stop over automation: an assistant must not be able to resume what its person paused"],
  ["flows.kit.remove", "changes the Space's shape and revokes grants"],
  ["spaces.invites.confirm", "needs the person's presence: confirms an invite, which grants access"],
  ["files.drive.access", "widens access: makes a share read-write for the paired Mac; its own code already says never an agent"],
  ["threads.mode", "an assistant must not change its own permission mode: that widens its own authority"],
  ["bridges.accept", "would let an assistant widen its own authority: accepting a bridge approves the assistant's own proposal"],
  ["bridges.revoke", "would let an assistant widen its own authority: accepting a bridge approves the assistant's own proposal"],
  ["chrome.install", "installs software on the person's machine"],
  ["chrome.interject", "the person's steer over the assistant"],
  ["chrome.pause", "the person's stop over the assistant"],
  ["chrome.resume", "the person's stop over the assistant: an assistant must not resume itself"],
  ["computers.egress.set", "controls the person's own machine: its network and hand-back"],
  ["computers.handback.set", "controls the person's own machine: its network and hand-back"],
  ["computers.member.add", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.dispose", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.remove", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.rotate", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.resume", "controls the person's own machine"],
  ["computers.tailnet.set", "controls the person's own machine: its network and hand-back"],
  ["connectors.scope", "widens what a connector may reach"],
  ["gate.said.add", "would let an assistant widen its own authority: records the person's own words as approval"],
  ["github.connect", "needs the person's Face ID or presence: signs an account in or out"],
  ["github.connect.cancel", "needs the person's Face ID or presence: signs an account in or out"],
  ["github.remove", "needs the person's Face ID or presence: signs an account in or out"],
  ["goals.accept", "would let an assistant widen its own authority: accepting a goal approves the assistant's own proposal"],
  ["google.open", "needs the person's Face ID or presence: starts a sign-in"],
  ["hands.grant.add", "would let an assistant widen its own authority: grants computer-use"],
  ["hands.grant.remove", "would let an assistant widen its own authority: grants computer-use"],
  ["hands.pause", "the person's stop over the assistant: an assistant must not resume itself"],
  ["hands.resume", "the person's stop over the assistant: an assistant must not resume itself"],
  ["hooks.enable", "would let an assistant widen its own authority: turns on code that runs on the person's machine"],
  ["link.companion.approve", "needs the person's Face ID or presence: pairing and devices"],
  ["link.companion.remove", "needs the person's Face ID or presence: pairing and devices"],
  ["link.pair", "needs the person's Face ID or presence: pairing and devices"],
  ["link.pair.deny", "needs the person's Face ID or presence: pairing and devices"],
  ["link.signout", "needs the person's Face ID or presence: pairing and devices"],
  ["link.unpair", "needs the person's Face ID or presence: pairing and devices"],
  ["names.domain.serve", "needs the person's Face ID or presence: the person's name and domain"],
  ["names.recover", "needs the person's Face ID or presence: the person's name and domain"],
  ["names.release", "needs the person's Face ID or presence: the person's name and domain"],
  ["network.guests.add", "needs the person's Face ID or presence: who may reach the home"],
  ["network.guests.enable", "needs the person's Face ID or presence: who may reach the home"],
  ["network.guests.remove", "needs the person's Face ID or presence: who may reach the home"],
  ["presence.person.revoke", "needs the person's Face ID or presence: ends or revokes the person's own sessions"],
  ["presence.session.close", "needs the person's Face ID or presence: ends or revokes the person's own sessions"],
  ["publish.decide", "would let an assistant widen its own authority: publishing decisions"],
  ["publish.domain.remove", "would let an assistant widen its own authority: publishing decisions"],
  ["publish.retire", "would let an assistant widen its own authority: publishing decisions"],
  ["relay.devices.ask-trust", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.devices.remove", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.devices.trust", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.disable", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.enable", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.join", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.pair.ticket", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.setup.claim", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.setup.claim-token", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.web.pin", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.web.release", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["runner.lock", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.move", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.start", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.stop", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["sessions.accounts.remove", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.accounts.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.limits.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.mode.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.models.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.prompt.revert", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.prompt.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.routes.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.setup", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.usage.resume", "resumes spending after a cap"],
  ["spaces.cancel", "cancels a Space move"],
  ["spaces.compute.accept", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.compute.allow", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.create", "needs the person's Face ID or presence: makes a Space and its root key"],
  ["spaces.identity.alias", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.alias.add", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.code.replace", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.create", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.entry.add", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.entry.remove", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.approve", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.begin", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.code", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.finish", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.invites.accept", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.invites.create", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.invites.revoke", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.add", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.extend", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.remove", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.set-role", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.transfer", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.resume", "runs a Space move"],
  ["spaces.server.install", "controls the person's own machine: installs a server"],
  ["team.charter.revert", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.charter.set", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.default.set", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.delete", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.disable", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.enable", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["term.attach", "controls the person's own machine: opens and drives a terminal on it"],
  ["term.close", "controls the person's own machine: opens and drives a terminal on it"],
  ["term.open", "controls the person's own machine: opens and drives a terminal on it"],
  ["threads.shell", "controls the person's own machine: a shell on it"],
  ["vault.account.lock", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.agent.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.approve", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connect", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.grant", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.update", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.device.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.device.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.add", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.deny", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.refresh", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.remove", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.request", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.lock", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.offboard", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.pass.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.revert", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.rotate", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.ssh.forget", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.vaults.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["wink.access", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.approve", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.cancel", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.ack", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.open", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.decline", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.device.key", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.invite", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.offer.set", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.pair.server", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.pair.targets", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.phone.open", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.phone.scan", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.relay.apply", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.remove", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.adopt", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.code", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.confirm", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.retarget", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.share", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.pair", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.pick", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.remove", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["work.engineer.approve", "would let an assistant widen its own authority: approves the assistant's own proposal"],
  ["work.know.accept", "would let an assistant widen its own authority: approves the assistant's own proposal"],
]);

/** @type {ReadonlySet<string>} */
export const OPEN = new Set([
  "vault.provider.status",
  "artifacts.activity.log",
  "artifacts.mention.search",
  "bridges.get",
  "bridges.kit.plan",
  "bridges.list",
  "bridges.merge.links",
  "bridges.propose-projection",
  "bridges.propose-reference",
  "bridges.propose-view",
  "chrome.plan.edit",
  "chrome.voice",
  "computers.egress.status",
  "computers.handback.status",
  "computers.rename",
  "computers.tailnet.status",
  "files.drive.address",
  "files.drive.mount",
  "files.drive.open",
  "files.drive.unmount",
  "files.drive.unshare",
  "files.mentions.search",
  "files.receive",
  "github.mcp.sync",
  "github.project",
  "github.project.add-repo",
  "github.project.detect",
  "github.star",
  "github.star.status",
  "glass.close",
  "glass.open",
  "glass.release",
  "glass.take",
  "glass.targets",
  "link.companion.list",
  "link.rename",
  "mentions.kinds",
  "mentions.search",
  "names.domain.check",
  "network.funnel.status",
  "network.guests.check",
  "network.guests.list",
  "planner.settings",
  "presence.person.status",
  "projects.add-threads",
  "projects.move",
  "projects.remove-threads",
  "projects.watchers.add",
  "projects.watchers.remove",
  "relay.devices.list",
  "relay.devices.path",
  "relay.devices.rename",
  "sessions.mention.search",
  "spaces.assess-computer",
  "spaces.compute.status",
  "spaces.get",
  "spaces.identity.contact.key",
  "spaces.identity.entries",
  "spaces.identity.resolve",
  "spaces.identity.status",
  "spaces.identity.sync",
  "spaces.invites.list",
  "spaces.invites.preview",
  "spaces.list",
  "spaces.members.list",
  "spaces.move.plan",
  "spaces.roles.names",
  "spaces.status",
  "stream.keep",
  "stream.mark-read",
  "stream.open",
  "stream.pin",
  "stream.react",
  "stream.send",
  "system.rename",
  "team.duties.run-now",
  "term.list",
  "threads.branch",
  "threads.continue-here",
  "threads.edit",
  "threads.edit-retry",
  "threads.kill-task",
  "threads.remember",
  "threads.retry",
  "threads.unqueue",
  "vault.emergency.status",
  "voice.listen",
  "voice.settings",
  "voice.speak",
  "voice.status",
  "watchers.delete",
  "watchers.resume",
  "watchers.run",
  "wink.card",
  "wink.code.status",
  "wink.offers",
  "wink.pair.status",
  "wink.storage.card",
  "wink.storage.discover",
  "wink.storage.offers",
  "wink.storage.status",
  "work.engineer.revise",
  "work.engineer.talk",
  "work.team.add",
]);

/** @type {ReadonlyMap<string, string>} */
export const ASK_FIRST = new Map([
  ["artifacts.public.set", "leaves the Space: publishes an artifact"],
  ["files.deliver", "leaves the Space: delivers a file"],
  ["files.drive.offer", "leaves the Space: offers a file"],
  ["files.drive.share", "leaves the Space: shares a file"],
  ["files.drive.url", "leaves the Space: makes a link"],
  ["files.send", "leaves the Space: sends a file"],
  ["agents.delete", "destructive"],
  ["bridges.kit.export", "leaves the Space"],
  ["bridges.kit.install", "changes the Space's shape"],
  ["hooks.close", "changes what reaches the Space from outside"],
  ["hooks.open", "opens the Space to the outside"],
]);
