// core/modules/agent-reach.js: which `reach: person` tools the person's assistant may call. The user's rule (4 Oct 2026): an assistant can do what its person can, under that
// person's narrowed grants, so a person-reach tool is OPEN to an assistant unless there is a written reason to keep it the person's (PERSON_ONLY, one reason each, from a short
// set: it needs the person's Face ID or presence, it controls the person's own machine, it widens an assistant's own authority, it is the person's stop or steer over the
// assistant). ASK_FIRST tools are open but held for a one-tap task, like send, post and pay. A person-reach tool in none of the three lists is refused to an assistant until it
// is classified: the test that walks every manifest (kernel/retrofit/agent-reach.test.js) fails on it, so a new tool cannot slip in open or closed by default.
// Reviewed entries kept open on purpose: glass.take (the user's ruling that screen use is hands-free after one grant; the person's stop, hands.pause and chrome.pause, stays
// person-only, so the person can always take it back).
// Safe only because the claim is assigned by the daemon from the session's own socket (L-1), never self-declared on the person's own socket.

/** @type {ReadonlyMap<string, string>} */
export const PERSON_ONLY = new Map([
  ["spaces.identity.republish", "republishes the person's identity list: the person's own act"],
  ["signin.ask", "needs the person's Face ID or presence: it asks the phone to sign the command line in, from a terminal login only"],
  ["signin.pending", "needs the person's Face ID or presence: the card the phone signs"],
  ["signin.answer", "needs the person's Face ID or presence: the person's approval of a sign-in"],
  ["signin.status", "needs the person's Face ID or presence: it hands the credential only to the terminal that asked"],
  ["signin.dev", "development builds only: a person session for the walk, from a caller already counted as the owner"],
  ["signin.end", "the person's own sign-out of their terminal"],
  ["recall.sealscan", "the person's own audit of where sensitive-looking values sit in memory: counts only, but it is the person's to ask"],
  ["recall.sealscrub", "scrubs sensitive-looking values out of memory: the person's own act"],
  ["files.drive.restore", "restores a Drive version: admin and owner, with the person's own act"],
  ["records.define", "changes the Space's types: the person's own act (an assistant proposes through a Kit or a task)"],
  ["records.reveal", "reveals a sealed value: needs the person's Face ID"],
  ["records.forget", "forgets a record for good: the person's own act with their presence (an assistant proposes with records.forget.propose)"],
  ["records.dev-seed", "a development-build seed for the walk, never an assistant's"],
  ["rules.define", "writes a standing rule: the person's own act"],
  ["rules.enable", "turns a standing rule on: the person's own act"],
  ["rules.disable", "turns a standing rule off: the person's own act"],
  ["rules.remove", "removes a standing rule: the person's own act"],
  ["rules.accept", "accepts a proposed rule: the person's own act"],
  ["rules.dismiss", "dismisses a proposed rule: the person's own act"],
  ["spaces.presence.begin", "the person's own presence enrolment"],
  ["spaces.presence.recover", "the person's own presence recovery"],
  ["spaces.presence.sync", "the person's own presence list"],
  ["spaces.devices.spaces", "the person's own devices"],
  ["spaces.devices.list", "the person's own devices"],
  ["spaces.devices.lend", "the person's own devices"],
  ["spaces.host-here", "hosts a space on this server: the owner's own act"],
  ["spaces.retire-here", "takes back a space on this server: the owner's own act"],
  ["spaces.devices.lend.status", "the person's own devices"],
  ["spaces.devices.remove", "the person's own devices"],
  ["spaces.devices.restore", "the person's own devices"],
  ["spaces.devices.enrol", "the person's own devices"],
  ["spaces.devices.set", "the person's own devices"],
  ["spaces.setup.save", "the person's own setup"],
  ["spaces.setup.claim", "the person's own setup"],
  ["tasks.decide", "approves or rejects a task with the person's proof"],
  ["approvals.request", "builds the proof request for an act the person will sign: the person's own surfaces"],
  ["approvals.ask", "asks the person's phone to approve an act the asking session cannot prove: the person's own surfaces only"],
  ["approvals.pending", "what is waiting for the person's approval, shown on their phone"],
  ["approvals.answer", "the person's own answer, with their proof"],
  ["approvals.status", "hands the approving proof back to the session that asked, once"],
  ["modules.list.reset", "drops the accepted first-party module list for a rollback: the owner with their presence"],
  ["modules.list.reset.ask", "asks the owner's phone to approve a rollback"],
  ["modules.list.reset.pending", "the rollback approval waiting for the owner"],
  ["modules.list.reset.answer", "the owner's answer to a rollback, with their proof"],
  ["modules.list.reset.status", "hands the rollback outcome to the updater that asked"],
  ["memory.sealscan", "the person's own audit of where sensitive-looking values sit in memory: counts only, but it is the person's to ask"],
  ["vault.provider.set", "needs the person's Face ID or presence: changes which provider holds the Space's secrets"],
  ["vault.provider.remove", "needs the person's Face ID or presence: changes which provider holds the Space's secrets"],
  ["wink.server.pairing", "needs the person's Face ID or presence: pairing and devices"],
  ["work.project.create", "makes a Project: a Drive folder and a record under the person's authority, which an assistant must not mint at will"],
  ["work.session.move", "moves a session to another Project, and so changes which reach it has (project access and scoping key off it): the person's own act"],
  ["files.drive.link.list", "shows the links that give outsiders access to a file: the person's own view"],
  ["files.drive.link.revoke", "takes an outsider's link away: the person's own decision about who reaches a file"],
  ["wink.server.probe", "the person's own device calls out to a server it paired: a network call as the person's device"],
  ["pluginagent.grant", "would let an assistant widen its own authority: lets Claude Code on a computer read memory and every project's sessions"],
  ["pluginagent.revoke", "the person's own decision about what Claude Code on a computer may reach"],
  ["pluginagent.decline", "the person's own decision about what Claude Code on a computer may reach"],
  ["pluginagent.on", "the person's own decision about what Claude Code on a computer may reach"],
  ["presence.person.renew-allow", "needs the person's presence: lifts the lock on a device that answered its sign-in wrongly"],
  ["spaces.members.add-agent", "would let an assistant widen its own authority: adds an assistant to the Space"],
  ["stream.open-peer", "controls the person's own device wire: only over the peer wire, for a paired device"],
  ["team.charter.accept", "the person's own act: a teammate's charter becomes a version as the person's decision"],
  ["wink.server.pair.answer", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.server.release", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.server.reset.begin", "only the person at the server's own console: resetting a server"],
  ["wink.server.reset.confirm", "only the person at the server's own console: resetting a server"],
  ["network.wink.join", "changes this computer's own network: bringing a link up"],
  ["network.wink.leave", "changes this computer's own network: taking a link down"],
  ["wink.server.status", "the server's own console: who owns it and which device paired it; a model session has no part in pairing"],
  ["wink.phone.pairing", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.phone.pair.answer", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.phone.wait", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge.accept", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge.drive", "needs the person's Face ID or presence: pairing and devices"],
  ["flows.approve", "needs the person's Face ID or presence: approving a Flow gives it authority"],
  ["flows.pause", "the person's stop over automation: an assistant must not be able to resume what its person paused"],
  ["flows.resume", "the person's stop over automation: an assistant must not be able to resume what its person paused"],
  ["flows.kit.remove", "changes the Space's shape and revokes grants"],
  ["spaces.invites.confirm", "needs the person's presence: confirms an invite, which grants access"],
  ["files.drive.access", "widens access: makes a share read-write for the paired Mac; its own code already says never an agent"],
  ["threads.mode", "an assistant must not change its own permission mode: that widens its own authority"],
  ["bridges.accept", "would let an assistant widen its own authority: accepting a bridge approves the assistant's own proposal"],
  ["bridges.revoke", "would let an assistant widen its own authority: accepting a bridge approves the assistant's own proposal"],
  ["chrome.install", "installs software on the person's machine"],
  ["chrome.interject", "the person's steer over the assistant"],
  ["chrome.pause", "the person's stop over the assistant"],
  ["chrome.resume", "the person's stop over the assistant: an assistant must not resume itself"],
  ["computers.egress.set", "controls the person's own machine: its network and hand-back"],
  ["computers.handback.set", "controls the person's own machine: its network and hand-back"],
  ["computers.member.add", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.dispose", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.remove", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.rotate", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.resume", "controls the person's own machine"],
  ["computers.tailnet.set", "controls the person's own machine: its network and hand-back"],
  ["connectors.scope", "widens what a connector may reach"],
  ["connectors.declare", "makes a vault credential: the person's own act, with their own key"],
  ["gate.said.add", "would let an assistant widen its own authority: records the person's own words as approval"],
  ["github.connect", "needs the person's Face ID or presence: signs an account in or out"],
  ["github.connect.cancel", "needs the person's Face ID or presence: signs an account in or out"],
  ["github.remove", "needs the person's Face ID or presence: signs an account in or out"],
  ["goals.accept", "would let an assistant widen its own authority: accepting a goal approves the assistant's own proposal"],
  ["google.open", "needs the person's Face ID or presence: starts a sign-in"],
  ["hands.grant.add", "would let an assistant widen its own authority: grants computer-use"],
  ["hands.grant.remove", "would let an assistant widen its own authority: grants computer-use"],
  ["hands.pause", "the person's stop over the assistant: an assistant must not resume itself"],
  ["hands.resume", "the person's stop over the assistant: an assistant must not resume itself"],
  ["hooks.enable", "would let an assistant widen its own authority: turns on code that runs on the person's machine"],
  ["link.companion.approve", "needs the person's Face ID or presence: pairing and devices"],
  ["link.companion.remove", "needs the person's Face ID or presence: pairing and devices"],
  ["link.pair", "needs the person's Face ID or presence: pairing and devices"],
  ["link.pair.deny", "needs the person's Face ID or presence: pairing and devices"],
  ["link.signout", "needs the person's Face ID or presence: pairing and devices"],
  ["link.unpair", "needs the person's Face ID or presence: pairing and devices"],
  ["names.domain.serve", "needs the person's Face ID or presence: the person's name and domain"],
  ["names.release", "needs the person's Face ID or presence: the person's name and domain"],
  ["network.guests.add", "needs the person's Face ID or presence: who may reach the home"],
  ["network.guests.enable", "needs the person's Face ID or presence: who may reach the home"],
  ["network.guests.remove", "needs the person's Face ID or presence: who may reach the home"],
  ["presence.person.revoke", "needs the person's Face ID or presence: ends or revokes the person's own sessions"],
  ["presence.session.close", "needs the person's Face ID or presence: ends or revokes the person's own sessions"],
  ["publish.decide", "would let an assistant widen its own authority: publishing decisions"],
  ["publish.domain.remove", "would let an assistant widen its own authority: publishing decisions"],
  ["publish.retire", "would let an assistant widen its own authority: publishing decisions"],
  ["relay.devices.ask-trust", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.devices.remove", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.devices.trust", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.disable", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.enable", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.join", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.pair.ticket", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.setup.claim", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.setup.claim-token", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.web.pin", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.web.release", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["runner.lock", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.move", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.start", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.stop", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["sessions.accounts.remove", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.accounts.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.limits.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.mode.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.models.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.prompt.revert", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.prompt.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.routes.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.setup", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.usage.resume", "resumes spending after a cap"],
  ["spaces.cancel", "cancels a Space move"],
  ["spaces.compute.accept", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.compute.allow", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.create", "needs the person's Face ID or presence: makes a Space and its root key"],
  ["spaces.identity.alias", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.alias.add", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.code.replace", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.create", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.entry.add", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.entry.remove", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.approve", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.begin", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.code", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.finish", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.invites.accept", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.invites.create", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.invites.revoke", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.add", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.extend", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.remove", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.set-role", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.transfer", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.resume", "runs a Space move"],
  ["spaces.server.install", "controls the person's own machine: installs a server"],
  ["team.charter.revert", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.charter.set", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.default.set", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.delete", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.disable", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.enable", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["term.attach", "controls the person's own machine: opens and drives a terminal on it"],
  ["term.close", "controls the person's own machine: opens and drives a terminal on it"],
  ["term.open", "controls the person's own machine: opens and drives a terminal on it"],
  ["threads.shell", "controls the person's own machine: a shell on it"],
  ["vault.account.lock", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.agent.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.approve", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connect", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.grant", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.update", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.device.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.device.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.add", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.deny", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.refresh", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.remove", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.request", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.lock", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.offboard", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.pass.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.revert", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.rotate", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.ssh.forget", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.vaults.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["wink.access", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.approve", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.cancel", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.ack", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.open", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.redeem", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.decline", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.device.key", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.invite", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.offer.set", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.pair.server", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.pair.targets", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.phone.open", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.phone.scan", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.relay.apply", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.remove", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.adopt", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.code", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.confirm", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.retarget", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.share", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.pair", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.pick", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.remove", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["work.engineer.approve", "would let an assistant widen its own authority: approves the assistant's own proposal"],
  ["work.know.accept", "would let an assistant widen its own authority: approves the assistant's own proposal"],
]);

/** @type {ReadonlySet<string>} */
export const OPEN = new Set([
  "pluginagent.pending",
  "presence.person.locked",
  // what is connected (which services have a credential, which Google accounts are signed in) and the recipe to log one mailbox: the person's own, and the person's proven assistant under their grants; never a guest or an unproven caller
  "connectors.declared",
  "connectors.logging",
  "files.drive.space.list",
  "files.drive.space.read",
  "records.linked",
  "records.roles",
  "records.holders",
  "records.kits.library",
  "records.kits.get",
  "system.build",
  "files.drive.upload",
  "files.drive.versions",
  "records.me",
  "records.actors",
  "records.types",
  "records.list",
  "records.get",
  "records.reference",
  "records.create",
  "records.update",
  "records.seal-put",
  "records.forget.propose",
  "records.sees-as",
  "records.events",
  "rules.list",
  "rules.get",
  "rules.test",
  "rules.propose",
  "tasks.list",
  "tasks.get",
  "tasks.request",
  "tasks.move",
  "tasks.submit",
  "vault.provider.status",
  "artifacts.activity.log",
  "artifacts.mention.search",
  "bridges.get",
  "bridges.kit.plan",
  "bridges.list",
  "bridges.merge.links",
  "bridges.propose-projection",
  "bridges.propose-reference",
  "bridges.propose-view",
  "chrome.plan.edit",
  "chrome.voice",
  "computers.egress.status",
  "computers.handback.status",
  "computers.rename",
  "computers.tailnet.status",
  "files.drive.address",
  "files.drive.mount",
  "files.drive.open",
  "files.drive.unmount",
  "files.drive.unshare",
  "files.mentions.search",
  "files.receive",
  "github.mcp.sync",
  "github.project",
  "github.project.add-repo",
  "github.project.detect",
  "github.star",
  "github.star.status",
  "glass.close",
  "glass.open",
  "glass.release",
  "glass.take",
  "glass.targets",
  "link.companion.list",
  "link.rename",
  "mentions.kinds",
  "mentions.search",
  "names.domain.check",
  "network.funnel.status",
  "network.guests.check",
  "network.guests.list",
  "planner.settings",
  "presence.person.status",
  "projects.add-threads",
  "projects.move",
  "projects.remove-threads",
  "projects.watchers.add",
  "projects.watchers.remove",
  "relay.devices.list",
  "relay.devices.path",
  "relay.devices.rename",
  "sessions.mention.search",
  "spaces.assess-computer",
  "spaces.compute.status",
  "spaces.get",
  "spaces.identity.contact.key",
  "spaces.identity.entries",
  "spaces.identity.resolve",
  "spaces.identity.status",
  "spaces.identity.sync",
  "spaces.invites.list",
  "spaces.invites.preview",
  "spaces.list",
  "spaces.members.list",
  "spaces.identity.devices",
  "spaces.move.plan",
  "spaces.roles.names",
  "spaces.status",
  "stream.keep",
  "stream.mark-read",
  "stream.open",
  "stream.pin",
  "stream.react",
  "stream.send",
  "system.rename",
  "team.duties.run-now",
  "term.list",
  "threads.branch",
  "threads.continue-here",
  "threads.edit",
  "threads.edit-retry",
  "threads.kill-task",
  "threads.remember",
  "threads.retry",
  "threads.unqueue",
  "vault.emergency.status",
  "voice.listen",
  "voice.settings",
  "voice.speak",
  "voice.status",
  "watchers.delete",
  "watchers.resume",
  "watchers.run",
  "wink.card",
  "wink.code.status",
  "wink.offers",
  "wink.pair.status",
  "wink.storage.card",
  "wink.storage.discover",
  "wink.storage.offers",
  "wink.storage.status",
  "work.engineer.revise",
  "work.engineer.talk",
  "work.team.add",
]);

/** @type {ReadonlyMap<string, string>} */
export const ASK_FIRST = new Map([
  ["artifacts.public.set", "leaves the Space: publishes an artifact"],
  ["files.deliver", "leaves the Space: delivers a file"],
  ["files.drive.offer", "leaves the Space: offers a file"],
  ["files.drive.share", "leaves the Space: shares a file"],
  ["files.drive.url", "leaves the Space: makes a link"],
  ["files.send", "leaves the Space: sends a file"],
  ["agents.delete", "destructive"],
  ["files.drive.link.create", "leaves the Space: makes a link that gives outsiders access to a file"],
  ["threads.delete", "destructive: deletes a thread for good"],
  ["threads.rewind", "destructive: rewinds a thread, and with restore its files, to an earlier turn"],
  ["bridges.kit.export", "leaves the Space"],
  ["bridges.kit.install", "changes the Space's shape"],
  ["hooks.close", "changes what reaches the Space from outside"],
  ["hooks.open", "opens the Space to the outside"],
]);

// The two caller classes the relay listener labels that are not the person's (BR-2). Each has a short, explicit list, one reason per tool; a tool on no list does not exist for the class,
// whatever its `callers` says, and whatever its reach is. Both lists are checked against their sources by test/reach-classes.test.js.

/**
 * `web:<id>`: a browser on the relay that has not been confirmed (a pairing that is waiting, or a legacy one-step browser row). It reaches only what it needs to finish confirming.
 * @type {ReadonlyMap<string, string>}
 */
export const WEB_REACH = new Map([
  ["wink.phone.wait", "the waiting pairing polls for the owner's confirmation"],
  ["wink.server.adopt", "the pairing's last step, taking the box as its server once confirmed"],
  ["relay.devices.ask-trust", "a legacy browser asks to be trusted, about itself only"],
  ["relay.devices.list", "a legacy browser reads its own row"],
  ["relay.web.release", "a legacy browser lets its own row go"],
]);

/**
 * `setup:<id>`: the setup page before the box is claimed. Exactly what the relay's setup gate (core/relay/setup.js SETUP_TOOLS and SETUP_TOOL_FAMILIES) lets through, plus the tools a
 * shipped module declares under `setupTools` (sessions: sign in to the AI). The relay's gate still holds the channel to its own list first; this is the registry's second check.
 * @type {ReadonlyMap<string, string>}
 */
export const SETUP_REACH = new Map([
  ["relay.setup.status", "the page reads its own setup session"],
  ["relay.setup.claim-token", "the page claims the box with its code"],
  ["names.check", "checks that a name is free"],
  ["names.claim", "claims the box's name"],
  ["names.status", "reads the name's state"],
  ["names.domain.check", "checks the person's own domain"],
  ["link.health", "reads whether the box is reachable"],
  ["system.info", "reads what machine this is"],
  ["onboard.machine", "reads the machine's setup state"],
  ["network.tailscale.login", "starts the tailnet sign-in"],
  ["network.tailscale.status", "reads the tailnet state"],
  ["network.tailscale.peers", "reads the tailnet's machines"],
  ["sessions.accounts.signin", "signs in to the person's AI (a module's setupTools)"],
  ["sessions.accounts.key", "saves the person's AI key (a module's setupTools)"],
]);
