// core/modules/agent-reach.js: which `reach: person` tools the person's assistant may call. The user's rule (4 Oct 2026): an assistant can do what its person can, under that
// person's narrowed grants, so a person-reach tool is OPEN to an assistant unless there is a written reason to keep it the person's (PERSON_ONLY, one reason each, from a short
// set: it needs the person's Face ID or presence, it controls the person's own machine, it widens an assistant's own authority, it is the person's stop or steer over the
// assistant). ASK_FIRST tools are open but held for a one-tap task, like send, post and pay. A person-reach tool in none of the three lists is refused to an assistant until it
// is classified: the test that walks every manifest (kernel/retrofit/agent-reach.test.js) fails on it, so a new tool cannot slip in open or closed by default.
// Reviewed entries kept open on purpose: glass.take (the user's ruling that screen use is hands-free after one grant; the person's stop, hands.pause and chrome.pause, stays
// person-only, so the person can always take it back).
// Safe only because the claim is assigned by the daemon from the session's own socket (L-1), never self-declared on the person's own socket.

import { SETUP_REASONS } from "../../lib/setup-gate.js";

/** @type {ReadonlyMap<string, string>} */
export const PERSON_ONLY = new Map([
  ["spaces.time-zone.set", "sets the time zone a space's clocks read: the person's own act (lead, 0.2.9)"],
  ["spaces.storage.put", "writes the person's own per-member storage: the person's own act until an assistant's write is decided (lead, 0.2.9)"],
  ["spaces.storage.put-if", "writes the person's own per-member storage if unchanged: the person's own act (lead, 0.2.9)"],
  ["spaces.storage.delete", "deletes from the person's own per-member storage: the person's own act (lead, 0.2.9)"],
  ["runner.places", "where the person's own chats run (the lent computer of each): the person's own view"],
  ["runner.placement", "where one of the person's own chats runs and why it moved: the person's own view"],
  ["runner.why-not", "why one of the person's own chats is not running on their computer: the person's own view"],
  ["runner.here", "what runs on the person's own computer and what it uses: the person's own view"],
  ["runner.folders.available", "the folders of the person's ready computers a chat can be given (ids and labels, never a path): the person's own view"],
  ["runner.settings", "the person's own computer's limits for running sessions: the person's own view (the assistant reads them with settings.get)"],
  ["stream.typing", "says the person is typing in a chat they are in: the person's own surface"],
  ["stream.catchup", "what the person missed in a chat they are in: the person's own surface reads it"],
  ["threads.roll", "rolls the person's own session over to a fresh window: the person's own act"],
  ["threads.rolls", "lists the person's own session rollovers: the person's own view"],
  ["threads.roll-session", "rolls a Claude Code session in the person's own terminal: a person's surface only"],
  ["system.modules", "lists the modules on the person's own box and their state: the person's own view"],
  ["work.chat.keys.begin", "the person's device lends a chat's key to this server: the person's own device act"],
  ["work.chat.keys.finish", "finishes the person's device lending a chat's key: the person's own device act"],
  ["work.chat.keys.lock", "the person locks a chat's key on this server again: the person's own act"],
  ["work.chat.keys.status", "whether a chat's key is unlocked here: the person's own view"],
  ["spaces.upgrade.plan", "part of the person's own move of their Personal space to My Cloud: the person's own act, with their presence"],
  ["spaces.upgrade.run", "moves the person's whole Personal space to My Cloud and freezes it: needs the person's presence, the person's own act"],
  ["spaces.upgrade.receipt", "part of the person's own move to My Cloud: the device asks it with the person's own chain"],
  ["spaces.upgrade.wrap-key", "part of the person's own move to My Cloud: it hands over a signed key sealed values are carried to"],
  ["spaces.moves.evidence", "part of the person's own project move to another space: the person's own act, with their presence"],
  ["spaces.moves.receive", "part of the person's own project move to another space: the person's own act, with their presence"],
  ["spaces.moves.receipt", "part of the person's own project move to another space: the person's own act"],
  ["spaces.moves.finish", "finishes the person's own project move and clears or keeps the original: the person's own act"],
  ["spaces.personal-host.set", "chooses where the person's own encrypted items live: the person's own act"],
  ["spaces.storage.set-cap", "sets a member's storage cap: an owner's own act, an assistant never widens its own budget"],
  ["spaces.members.add-agent", "gives an assistant a place in a space: it widens an assistant's own authority, the person's own act"],
  ["spaces.identity.republish", "republishes the person's identity list: the person's own act"],
  ["signin.ask", "needs the person's Face ID or presence: it asks the phone to sign the command line in, from a terminal login only"],
  ["signin.pending", "needs the person's Face ID or presence: the card the phone signs"],
  ["signin.answer", "needs the person's Face ID or presence: the person's approval of a sign-in"],
  ["signin.status", "needs the person's Face ID or presence: it hands the credential only to the terminal that asked"],
  ["signin.dev", "development builds only: a person session for the walk, from a caller already counted as the owner"],
  ["signin.end", "the person's own sign-out of their terminal"],
  ["recall.sealscan", "the person's own audit of where sensitive-looking values sit in memory: counts only, but it is the person's to ask"],
  ["recall.sealscrub", "scrubs sensitive-looking values out of memory: the person's own act"],
  ["files.drive.restore", "restores a Drive version: admin and owner, with the person's own act"],
  ["records.define", "changes the Space's types: the person's own act (an assistant proposes through a Kit or a task)"],
  ["records.reveal", "reveals a sealed value: needs the person's Face ID"],
  ["records.forget", "forgets a record for good: the person's own act with their presence (an assistant proposes with records.forget.propose)"],
  ["records.dev-seed", "a development-build seed for the walk, never an assistant's"],
  ["rules.define", "writes a standing rule: the person's own act"],
  ["rules.enable", "turns a standing rule on: the person's own act"],
  ["rules.disable", "turns a standing rule off: the person's own act"],
  ["rules.remove", "removes a standing rule: the person's own act"],
  ["rules.accept", "accepts a proposed rule: the person's own act"],
  ["rules.dismiss", "dismisses a proposed rule: the person's own act"],
  ["spaces.presence.begin", "the person's own presence enrolment"],
  ["spaces.presence.recover", "the person's own presence recovery"],
  ["spaces.presence.sync", "the person's own presence list"],
  ["spaces.devices.spaces", "the person's own devices"],
  ["spaces.devices.list", "the person's own devices"],
  ["spaces.devices.lend", "the person's own devices"],
  ["spaces.host-here", "hosts a space on this server: the owner's own act"],
  ["spaces.retire-here", "takes back a space on this server: the owner's own act"],
  ["spaces.devices.lend.status", "the person's own devices"],
  ["spaces.devices.remove", "the person's own devices"],
  ["spaces.devices.restore", "the person's own devices"],
  ["spaces.devices.enrol", "the person's own devices"],
  ["spaces.devices.set", "the person's own devices"],
  ["spaces.setup.save", "the person's own setup"],
  ["spaces.setup.claim", "the person's own setup"],
  ["tasks.decide", "approves or rejects a task with the person's proof"],
  ["approvals.request", "builds the proof request for an act the person will sign: the person's own surfaces"],
  ["approvals.ask", "asks the person's phone to approve an act the asking session cannot prove: the person's own surfaces only"],
  ["approvals.pending", "what is waiting for the person's approval, shown on their phone"],
  ["approvals.answer", "the person's own answer, with their proof"],
  ["approvals.answer-group", "the person's own answer to a group of held calls, each approved item with its own proof"],
  ["approvals.item-view", "the person reads every value of one held call, in pages, before approving it"],
  ["approvals.edit-item", "the person changes the words of one held call before approving it"],
  ["approvals.status", "hands the approving proof back to the session that asked, once"],
  ["modules.list.reset", "drops the accepted first-party module list for a rollback: the owner with their presence"],
  ["modules.list.reset.ask", "asks the owner's phone to approve a rollback"],
  ["modules.list.reset.pending", "the rollback approval waiting for the owner"],
  ["modules.list.reset.answer", "the owner's answer to a rollback, with their proof"],
  ["modules.list.reset.status", "hands the rollback outcome to the updater that asked"],
  ["memory.identity.enroll", "seals the person's identity memory behind their devices' keys: the person's own act"],
  ["memory.identity.move", "moves the person's sealed identity memory to another server: the person's own act"],
  ["memory.identity.grant", "needs the person's Face ID or presence: the one yes that lets their assistant read their private memory on a server"],
  ["memory.identity.revoke", "the person's stop: takes the grant back and locks their private memory; an assistant must not undo it"],
  ["memory.identity.unlock.finish", "needs the person's device: the phone's answer to an unlock request, made with the device key the person holds"],
  ["memory.personal.status", "the person's own storage: how much of their sealed personal records the server holds"],
  ["memory.personal.set-cap", "the space owner's own limit on each member's personal storage"],
  ["memory.backup.status", "the person's own encrypted backup: where it is kept and how it stands"],
  ["memory.backup.run", "the person's own encrypted backup of their personal memory: their act"],
  ["memory.backup.restore", "the person's own restore of their encrypted backup: their act, with their device"],
  ["memory.sealscan", "the person's own audit of where sensitive-looking values sit in memory: counts only, but it is the person's to ask"],
  ["vault.provider.set", "needs the person's Face ID or presence: changes which provider holds the Space's secrets"],
  ["vault.provider.remove", "needs the person's Face ID or presence: changes which provider holds the Space's secrets"],
  ["wink.server.pairing", "needs the person's Face ID or presence: pairing and devices"],
  ["work.project.create", "makes a Project: a Drive folder and a record under the person's authority, which an assistant must not mint at will"],
  ["files.drive.link.list", "shows the links that give outsiders access to a file: the person's own view"],
  ["files.drive.link.revoke", "takes an outsider's link away: the person's own decision about who reaches a file"],
  ["wink.server.probe", "the person's own device calls out to a server it paired: a network call as the person's device"],
  ["pluginagent.grant", "would let an assistant widen its own authority: lets Claude Code on a computer read memory and every project's sessions"],
  ["pluginagent.revoke", "the person's own decision about what Claude Code on a computer may reach"],
  ["pluginagent.decline", "the person's own decision about what Claude Code on a computer may reach"],
  ["pluginagent.on", "the person's own decision about what Claude Code on a computer may reach"],
  ["presence.person.renew-allow", "needs the person's presence: lifts the lock on a device that answered its sign-in wrongly"],
  ["spaces.members.add-agent", "would let an assistant widen its own authority: adds an assistant to the Space"],
  ["stream.open-peer", "controls the person's own device wire: only over the peer wire, for a paired device"],
  ["team.charter.accept", "the person's own act: a teammate's charter becomes a version as the person's decision"],
  ["wink.server.pair.answer", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.server.release", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.server.reset.begin", "only the person at the server's own console: resetting a server"],
  ["wink.server.reset.confirm", "only the person at the server's own console: resetting a server"],
  ["network.wink.join", "changes this computer's own network: bringing a link up"],
  ["network.wink.leave", "changes this computer's own network: taking a link down"],
  ["wink.server.status", "the server's own console: who owns it and which device paired it; a model session has no part in pairing"],
  ["wink.phone.pairing", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.phone.pair.answer", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.phone.wait", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.phone.enrolled", "the owner's app reports a phone's enrolment onto the name's list: pairing and devices, never a model's"],
  ["wink.storage.bridge", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge.accept", "needs the person's Face ID or presence: pairing and devices"],
  ["wink.storage.bridge.drive", "needs the person's Face ID or presence: pairing and devices"],
  ["flows.approve", "needs the person's Face ID or presence: approving a Flow gives it authority"],
  ["work.template.golive", "puts a template version live: the template's owner or an admin in their own name; an assistant proposes it (flows.propose what: template) and the owner approves on a card"],
  ["flows.pause", "the person's stop over automation: an assistant must not be able to resume what its person paused"],
  ["flows.resume", "the person's stop over automation: an assistant must not be able to resume what its person paused"],
  ["flows.kit.remove", "changes the Space's shape and revokes grants"],
  ["spaces.invites.confirm", "needs the person's presence: confirms an invite, which grants access"],
  ["files.drop.register", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.unregister", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.targets", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.begin", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.put", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.finish", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.cancel", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.pending", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.meta", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.get", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drop.ack", "VyreDrop seals a file to the person's own device key: only the person's own surfaces register a target, send, receive or acknowledge one"],
  ["files.drive.access", "widens access: makes a share read-write for the paired Mac; its own code already says never an agent"],
  ["threads.mode", "an assistant must not change its own permission mode: that widens its own authority"],
  ["bridges.accept", "would let an assistant widen its own authority: accepting a bridge approves the assistant's own proposal"],
  ["bridges.revoke", "would let an assistant widen its own authority: accepting a bridge approves the assistant's own proposal"],
  ["chrome.install", "installs software on the person's machine"],
  ["chrome.interject", "the person's steer over the assistant"],
  ["chrome.pause", "the person's stop over the assistant"],
  ["chrome.resume", "the person's stop over the assistant: an assistant must not resume itself"],
  ["computers.egress.set", "controls the person's own machine: its network and hand-back"],
  ["computers.handback.set", "controls the person's own machine: its network and hand-back"],
  ["computers.member.add", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.dispose", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.remove", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.member.rotate", "needs the person's Face ID or presence: who may use a computer"],
  ["computers.resume", "controls the person's own machine"],
  ["computers.tailnet.set", "controls the person's own machine: its network and hand-back"],
  ["connectors.site.connect", "makes a website Connection from what was learned: the person's own act"],
  ["connectors.site.sync", "changes which learned operations a website Connection exposes: the person's own act"],
  ["connectors.site.rollback", "puts a learned operation back to an earlier version: the person's own act"],
  ["connectors.site.limits.set", "would let an assistant widen its own authority: the pace and caps that protect an account"],
  ["connectors.site.resume", "the person's go-ahead after a site stopped at a challenge: only they can clear it"],
  ["link.ops.allow", "needs the person's Face ID or presence: pairing and devices (what the box may run in their Chrome)"],
  ["link.ops.revoke", "needs the person's Face ID or presence: pairing and devices (what the box may run in their Chrome)"],
  ["link.ops.list", "needs the person's Face ID or presence: pairing and devices (what the box may run in their Chrome)"],
  ["vault.tagged", "the person's own view of where a # tag has lent a login: conversation ids and hosts, never a value"],
  ["vault.untag", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["link.computer.allow", "would let an assistant widen its own authority: what the box may do on this Mac"],
  ["link.computer.revoke", "needs the person's Face ID or presence: pairing and devices (what the box may do on this Mac)"],
  ["link.computer.list", "needs the person's Face ID or presence: pairing and devices (what the box may do on this Mac)"],
  ["connectors.scope", "widens what a connector may reach"],
  ["connectors.declare", "makes a vault credential: the person's own act, with their own key"],
  ["appmods.install", "installing or running third-party code on the server is the owner's act"],
  ["appmods.remove", "installing or running third-party code on the server is the owner's act"],
  ["appmods.start", "installing or running third-party code on the server is the owner's act"],
  ["appmods.stop", "installing or running third-party code on the server is the owner's act"],
  ["appmods.open", "gives a browser a signed-in session on the app"],
  ["appmods.logs", "an app's logs can carry its users' data"],
  ["views.act", "a view action is the person's click; its outward acts are still held"],
  ["views.shown", "the chat's own question of what a thread was shown"],
  ["views.preview", "resolves a proposed screen's data as the person, for the owner's before and after"],
  ["design.proposals", "the owner's list of proposed screen changes, with what each reads and runs"],
  ["design.decide", "the yes or no to a proposed screen is the screen owner's alone"],
  ["design.screen.remove", "removing a space screen is the person's act"],
  ["brand.set", "the space's identity is saved by a person: an agent drafts it and the person says yes"],
  ["design.css.status", "the owner's view of custom styling and why one was turned off"],
  ["design.css.verify", "re-checking custom CSS turns one off: the person's call"],
  ["connectors.connection.create", "connects an app: writes a vault credential with the person's own key"],
  ["connectors.connection.update", "changes what a Connection reaches and rebuilds its credential: the person's own act"],
  ["connectors.connection.proposals", "the person reads what an assistant proposed before saying yes"],
  ["connectors.connection.approve", "the person's yes to a proposed Connection: makes it"],
  ["connectors.connection.decline", "the person's no to a proposed Connection"],
  ["connectors.connection.rebuild", "rewrites the Connection's vault credential from its record: the person's own act"],
  ["connectors.connection.delete", "removes a Connection and its vault credential: the person's own act"],
  ["github.owners", "lists the organisations the person's GitHub account belongs to: their own screen picks the owner of a new repo"],
  ["github.repo.create", "creates a repo on the person's GitHub account and sends a folder there: their own act, with their yes"],
  ["gate.said.add", "would let an assistant widen its own authority: records the person's own words as approval"],
  ["github.connect", "needs the person's Face ID or presence: signs an account in or out"],
  ["github.connect.cancel", "needs the person's Face ID or presence: signs an account in or out"],
  ["github.remove", "needs the person's Face ID or presence: signs an account in or out"],
  ["goals.accept", "would let an assistant widen its own authority: accepting a goal approves the assistant's own proposal"],
  ["google.open", "needs the person's Face ID or presence: starts a sign-in"],
  ["hands.grant.add", "would let an assistant widen its own authority: grants computer-use"],
  ["hands.grant.remove", "would let an assistant widen its own authority: grants computer-use"],
  ["hands.pause", "the person's stop over the assistant: an assistant must not resume itself"],
  ["hands.resume", "the person's stop over the assistant: an assistant must not resume itself"],
  ["hooks.enable", "would let an assistant widen its own authority: turns on code that runs on the person's machine"],
  ["link.companion.approve", "needs the person's Face ID or presence: pairing and devices"],
  ["link.companion.remove", "needs the person's Face ID or presence: pairing and devices"],
  ["link.pair", "needs the person's Face ID or presence: pairing and devices"],
  ["link.pair.deny", "needs the person's Face ID or presence: pairing and devices"],
  ["link.signout", "needs the person's Face ID or presence: pairing and devices"],
  ["link.unpair", "needs the person's Face ID or presence: pairing and devices"],
  ["sidebar.stored", "the settings hub's own store for the sidebar lists: the person's settings act"],
  ["names.serve", "needs the person's Face ID or presence: the person's name and domain"],
  ["names.unserve", "needs the person's Face ID or presence: the person's name and domain"],
  ["presence.person.revoke", "needs the person's Face ID or presence: ends or revokes the person's own sessions"],
  ["publish.decide", "would let an assistant widen its own authority: publishing decisions"],
  ["publish.domain.remove", "would let an assistant widen its own authority: publishing decisions"],
  ["publish.retire", "would let an assistant widen its own authority: publishing decisions"],
  ["relay.devices.ask-trust", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.devices.remove", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.devices.trust", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.disable", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.enable", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.join", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.pair.ticket", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.web.pin", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["relay.web.release", "needs the person's Face ID or presence: relay pairing, devices and who may reach the home"],
  ["runner.lock", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.settings.set", "controls the person's own machine: its limits for running sessions (the assistant changes them with settings.request, on the person's own words)"],
  ["runner.pause-all", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.resume-all", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.move", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.folders", "the paths of the folders on the person's own machine they approved for chats: the person's own view"],
  ["runner.folders.allow", "controls the person's own machine: which of its folders a chat may work in (the one yes)"],
  ["runner.folders.remove", "controls the person's own machine: which of its folders a chat may work in"],
  ["runner.preview", "opens a card for a dev server on the person's own machine: the person's own act"],
  ["runner.start", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["runner.stop", "controls the person's own machine: starts, stops, locks and moves sessions on it"],
  ["sessions.accounts.remove", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.accounts.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.limits.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.mode.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.models.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.prompt.revert", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.prompt.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.routes.set", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.setup", "would let an assistant widen its own authority: the assistant's own prompt, mode, limits and accounts"],
  ["sessions.usage.resume", "resumes spending after a cap"],
  ["spaces.cancel", "cancels a Space move"],
  ["spaces.compute.accept", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.compute.allow", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.create", "needs the person's Face ID or presence: makes a Space and its root key"],
  ["spaces.bundle.enrol", "the owner gives their recovery code: a code is the person's own secret, never a model's"],
  ["spaces.bundle.export", "writes the Space bundle, which holds every sealed value of the Space under the owner's key: the owner's own act"],
  ["spaces.bundle.status", "tells whether the Space bundle is set up: the owner's own view"],
  ["vault.health.dismiss", "hides the vault health row on Now: the person's own say over what they are nagged about"],
  ["spaces.identity.alias", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.alias.add", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.code.replace", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.create", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.entry.add", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.entry.remove", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.approve", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.begin", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.code", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.identity.recover.finish", "needs the person's Face ID or presence: identity list and recovery changes"],
  ["spaces.invites.accept", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.invites.create", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.invites.revoke", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.add", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.extend", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.remove", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.set-role", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.members.transfer", "needs the person's Face ID or presence: grants, roles and offers"],
  ["spaces.resume", "runs a Space move"],
  ["spaces.server.install", "controls the person's own machine: installs a server"],
  ["team.charter.revert", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.charter.set", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.default.set", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.delete", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.disable", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["team.duties.enable", "would let an assistant widen its own authority: sets the assistant's own charter and duties"],
  ["term.attach", "controls the person's own machine: opens and drives a terminal on it"],
  ["term.close", "controls the person's own machine: opens and drives a terminal on it"],
  ["term.open", "controls the person's own machine: opens and drives a terminal on it"],
  ["threads.shell", "controls the person's own machine: a shell on it"],
  ["vault.account.lock", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.agent.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.approve", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connect", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.grant", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.mcp.pass.create", "needs the person's Face ID or presence: it hands credentials to an outside agent"],
  ["vault.mcp.items", "the person's own view of which credentials can be shared with an outside agent and where each may call: hosts, never a key"],
  ["vault.mcp.reveal.allow", "needs the person's fresh yes: it lets an outside agent see one value, once"],
  ["vault.mcp.reveal.clear", "answers an outside agent's ask to see a value: the owner's own decision"],
  ["vault.connections.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.connections.update", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.device.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.device.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.add", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.deny", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.refresh", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.remove", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.emergency.request", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.lock", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.offboard", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.pass.revoke", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.revert", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.rotate", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.ssh.forget", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["vault.vaults.sync", "needs the person's Face ID or presence: secrets, devices and vault access"],
  ["wink.access", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.approve", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.cancel", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.ack", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.open", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.code.redeem", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.decline", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.device.key", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.invite", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.offer.set", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.pair.server", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.pair.targets", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.phone.open", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.phone.scan", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.relay.apply", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.remove", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.adopt", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.setup-offer", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.code", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.confirm", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.server.retarget", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.share", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.pair", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.pick", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["wink.storage.remove", "needs the person's Face ID or presence: pairing, devices, offers and sharing"],
  ["work.know.accept", "would let an assistant widen its own authority: approves the assistant's own proposal"],
  ["threads.undo-edit", "puts a file back from what the person's own surface saw the session do: the person's own act, and the session is told"],
  ["outside.register", "gives an outside agent a way into the Space: it widens what reaches the person's data, the person's own act with their approval"],
  ["outside.token", "makes a new token for an outside agent: the person's own act with their approval"],
  ["outside.grant", "gives an outside agent reach to records, memory or files: it widens authority, the person's own act with their approval"],
  ["outside.ungrant", "takes reach back from an outside agent: the person's own act"],
  ["outside.list", "the person's own outside agents and what each may reach: the person's own view"],
  ["outside.revoke", "ends an outside agent: the person's own act"],
  ["attachments.put", "adds a file to a chat as the person: it keeps the person's own file in the chat's sealed folder, the person's own act"],
  ["attachments.list", "the files added to a chat the person is in: the person's own view"],
  ["ask.answer", "answers a question card in the person's own words: an assistant answering would decide for the person"],
  ["ask.cancel", "puts a question card away: the person's own act, the agent is told it was cancelled"],
  ["previews.keep", "looks after a preview as its maker or an admin, read from the person's own session; the body admits a person surface only (assistant management: BACKLOG 0.3.2)"],
  ["previews.restart", "looks after a preview as its maker or an admin, read from the person's own session; the body admits a person surface only"],
  ["previews.stop", "looks after a preview as its maker or an admin, read from the person's own session; the body admits a person surface only"],
  ["previews.remove", "looks after a preview as its maker or an admin, read from the person's own session; the body admits a person surface only"],
  ["previews.log", "the process log of a preview, for its maker or an admin, read from the person's own session; the body admits a person surface only"],
  ["previews.share", "opens a preview to a project or the whole Space, as its maker or an admin from the person's own session: the person's own act"],
  ["previews.url", "makes the one-time ticket that opens a preview in the person's own browser: the person's own act"],
  ["previews.signin-done", "says the person has signed in on a computer: their own hands on their own keyboard"],
  ["previews.reply", "the person's typed answer to a stuck run: their own words"],
  ["previews.frame", "the person's own view of a computer's live screen"],
  ["previews.thumb", "the picture on a preview card, drawn for the person's own screen"],
  ["approvals.local-yes", "needs the person's Face ID or presence: gives the yes for a card on this computer (Touch ID, or a code written to their own terminal)"],
  ["flows.test.remove", "removes a saved test case, which loosens what approving a Flow requires: an assistant adds cases, only the person removes one"],
  ["flows.rollback", "needs the person's Face ID or presence: going back to an earlier Flow version approves it again, and an approval is never inherited"],
  ["models.eval-approve", "spends on the owner's own key: the person's yes to an eval, with a hard cap, never an assistant's on its own proposal"],
  ["models.eval-decline", "the owner's own no to evaluating a model: its body refuses anything but a person"],
  ["models.eval-record", "the owner's runner reports a score with the owner's own key: its body refuses anything but a person"],
  ["link.sleep", "the Mac's own app says the lid is shutting: the person's own machine, callers are the Mac's cli, local and capsule only"],
  ["link.wake", "the Mac's own app says it woke: the person's own machine, callers are the Mac's cli, local and capsule only"],
]);

/** @type {ReadonlySet<string>} */
export const OPEN = new Set([
  "update.whats-new", "update.whats-new-seen", // the release notes of the running version, once per person: the assistant says them in the notes' own words and marks them seen; nothing but a seen mark is written
  "flows.settle", "flows.advance", // answer a run that needs attention, and move a record past its stage gate early: the kernel holds the call to the person's own chain (a stage gate to its owner or an admin, with a reason on the ledger); a value for a skipped step stays the person's
  "views.list", "views.get", // reads the screens a module declares; the data they show is fetched as the viewer
  "spaces.servers", "spaces.storage.get", "spaces.storage.list", "spaces.storage.usage", // the person's own server list and reads of their own per-member storage: the kernel's grants and the call's own chain decide
  "pluginagent.pending",
  "presence.person.locked",
  // what is connected (which services have a credential, which Google accounts are signed in) and the recipe to log one mailbox: the person's own, and the person's proven assistant under their grants; never a guest or an unproven caller
  "connectors.declared",
  "connectors.logging",
  "files.drive.space.list",
  "files.drive.space.read",
  "records.linked",
  "records.roles",
  "records.holders",
  "records.kits.library",
  "records.kits.get",
  "system.build",
  "files.drive.upload",
  "files.drive.versions",
  "records.me",
  "records.actors",
  "records.types",
  "records.list",
  "records.get",
  "records.reference",
  "records.create",
  "records.update",
  "records.seal-put",
  "records.forget.propose",
  "records.sees-as",
  "records.events",
  "rules.list",
  "rules.get",
  "rules.test",
  "rules.propose",
  "tasks.list",
  "tasks.get",
  "tasks.request",
  "tasks.move",
  "tasks.submit",
  "vault.provider.status",
  "artifacts.activity.log",
  "artifacts.mention.search",
  "bridges.get",
  "bridges.kit.plan",
  "bridges.list",
  "bridges.merge.links",
  "bridges.propose-projection",
  "bridges.propose-reference",
  "bridges.propose-view",
  "chrome.plan.edit",
  "chrome.voice",
  "computers.egress.status",
  "computers.handback.status",
  "computers.rename",
  "computers.tailnet.status",
  "files.drive.address",
  "files.drive.mount",
  "files.drive.open",
  "files.drive.unmount",
  "files.drive.unshare",
  "files.mentions.search",
  "files.receive",
  "github.mcp.sync",
  "github.project",
  "github.project.add-repo",
  "github.project.detect",
  "github.star",
  "github.star.status",
  "glass.close",
  "glass.open",
  "glass.release",
  "glass.take",
  "glass.targets",
  "link.companion.list",
  "link.rename",
  "mentions.kinds",
  "mentions.search",
  "planner.settings",
  "presence.person.status",
  "projects.add-threads",
  "projects.remove-threads",
  "projects.watchers.add",
  "projects.watchers.remove",
  "relay.devices.list",
  "relay.devices.path",
  "relay.devices.rename",
  "sessions.mention.search",
  "spaces.assess-computer",
  "spaces.compute.status",
  "spaces.get",
  "spaces.identity.contact.key",
  "spaces.identity.entries",
  "spaces.identity.resolve",
  "spaces.identity.status",
  "spaces.identity.sync",
  "spaces.invites.list",
  "spaces.invites.preview",
  "spaces.list",
  "spaces.members.list",
  "spaces.identity.devices",
  "spaces.move.plan",
  "spaces.roles.names",
  "spaces.status",
  "stream.keep",
  "stream.mark-read",
  "stream.open",
  "stream.pin",
  "stream.react",
  "stream.send",
  "system.rename",
  "team.duties.run-now",
  "term.list",
  "threads.branch",
  "threads.continue-here",
  "threads.edit",
  "threads.edit-retry",
  "threads.kill-task",
  "threads.remember",
  "threads.retry",
  "threads.unqueue",
  "vault.emergency.status",
  "voice.listen",
  "voice.settings",
  "voice.speak",
  "voice.status",
  "watchers.delete",
  "watchers.resume",
  "watchers.run",
  "wink.card",
  "wink.code.status",
  "wink.offers",
  "wink.pair.status",
  "wink.storage.card",
  "wink.storage.discover",
  "wink.storage.offers",
  "wink.storage.status",
  "work.team.add",
]);

/** @type {ReadonlyMap<string, string>} */
export const ASK_FIRST = new Map([
  ["stream.second-opinion", "adds a paid model to the chat and spends on the person's account"],
  ["artifacts.public.set", "leaves the Space: publishes an artifact"],
  ["files.deliver", "leaves the Space: delivers a file"],
  ["files.drive.offer", "leaves the Space: offers a file"],
  ["files.drive.share", "leaves the Space: shares a file"],
  ["files.drive.url", "leaves the Space: makes a link"],
  ["files.send", "leaves the Space: sends a file"],
  ["agents.delete", "destructive"],
  ["sidebar.team", "changes what everyone in the Space sees in their sidebar: held for an owner or admin's yes"],
  ["files.drive.link.create", "leaves the Space: makes a link that gives outsiders access to a file"],
  ["threads.delete", "destructive: deletes a thread for good"],
  ["threads.rewind", "destructive: rewinds a thread, and with restore its files, to an earlier turn"],
  ["bridges.kit.export", "leaves the Space"],
  ["bridges.kit.install", "changes the Space's shape"],
  ["hooks.close", "changes what reaches the Space from outside"],
  ["hooks.open", "opens the Space to the outside"],
  ["appmods.domain.add", "opens an app's public pages to the outside at the person's own domain"],
  ["appmods.domain.remove", "takes the person's own domain from an app, so its public pages stop answering at that address"],
]);

// The two caller classes the relay listener labels that are not the person's (BR-2). Each has a short, explicit list, one reason per tool; a tool on no list does not exist for the class,
// whatever its `callers` says, and whatever its reach is. Both lists are checked against their sources by test/reach-classes.test.js.

/**
 * `web:<id>`: a browser on the relay that has not been confirmed (a pairing that is waiting, or a legacy one-step browser row). It reaches only what it needs to finish confirming.
 * @type {ReadonlyMap<string, string>}
 */
export const WEB_REACH = new Map([
  ["wink.phone.wait", "the waiting pairing polls for the owner's confirmation"],
  ["wink.server.adopt", "the pairing's last step, taking the box as its server once confirmed"],
  ["relay.devices.ask-trust", "a legacy browser asks to be trusted, about itself only"],
  ["relay.devices.list", "a legacy browser reads its own row"],
  ["relay.web.release", "a legacy browser lets its own row go"],
]);

/**
 * `setup:<id>`: the setup page before the box is claimed. Exactly what the relay's setup gate (core/relay/setup.js SETUP_TOOLS and SETUP_TOOL_FAMILIES; the reasons are SETUP_REASONS there) lets through, plus the tools a
 * shipped module declares under `setupTools` (sessions: sign in to the AI). The relay's gate still holds the channel to its own list first; this is the registry's second check.
 * @type {ReadonlyMap<string, string>}
 */
export const SETUP_REACH = new Map([...SETUP_REASONS]);
