// Generated by scripts/gen-tokens from docs/design/one-app/tokens.json. Do not edit; change the JSON and run it.
// The Capsule reads these through Theme.swift; the app and the Deck read the same JSON.

import SwiftUI

public enum Tokens {
    public struct Colors: Sendable {
        public let bg: Color
        public let panel: Color
        public let hover: Color
        public let rule: Color
        public let ruleStrong: Color
        public let text: Color
        public let text2: Color
        public let label: Color
        public let primaryBg: Color
        public let primaryHover: Color
        public let primaryInk: Color
        public let focus: Color
        public let signalWash: Color
        public let delWash: Color
        public let beacon: Color
        public let codeBg: Color
        public let scrim: Color
        public let markWire: Color
        public let markDot: Color
    }

    public static let dark = Colors(
        bg: Color(.sRGB, red: 14 / 255, green: 13 / 255, blue: 12 / 255, opacity: 1),
        panel: Color(.sRGB, red: 22 / 255, green: 21 / 255, blue: 19 / 255, opacity: 1),
        hover: Color(.sRGB, red: 30 / 255, green: 28 / 255, blue: 26 / 255, opacity: 1),
        rule: Color(.sRGB, red: 43 / 255, green: 41 / 255, blue: 38 / 255, opacity: 1),
        ruleStrong: Color(.sRGB, red: 58 / 255, green: 55 / 255, blue: 51 / 255, opacity: 1),
        text: Color(.sRGB, red: 241 / 255, green: 238 / 255, blue: 230 / 255, opacity: 1),
        text2: Color(.sRGB, red: 179 / 255, green: 174 / 255, blue: 164 / 255, opacity: 1),
        label: Color(.sRGB, red: 140 / 255, green: 135 / 255, blue: 125 / 255, opacity: 1),
        primaryBg: Color(.sRGB, red: 198 / 255, green: 243 / 255, blue: 107 / 255, opacity: 1),
        primaryHover: Color(.sRGB, red: 212 / 255, green: 248 / 255, blue: 138 / 255, opacity: 1),
        primaryInk: Color(.sRGB, red: 14 / 255, green: 13 / 255, blue: 12 / 255, opacity: 1),
        focus: Color(.sRGB, red: 198 / 255, green: 243 / 255, blue: 107 / 255, opacity: 1),
        signalWash: Color(.sRGB, red: 198 / 255, green: 243 / 255, blue: 107 / 255, opacity: 0.12),
        delWash: Color(.sRGB, red: 140 / 255, green: 135 / 255, blue: 125 / 255, opacity: 0.14),
        beacon: Color(.sRGB, red: 184 / 255, green: 164 / 255, blue: 255 / 255, opacity: 1),
        codeBg: Color(.sRGB, red: 18 / 255, green: 17 / 255, blue: 16 / 255, opacity: 1),
        scrim: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.62),
        markWire: Color(.sRGB, red: 241 / 255, green: 238 / 255, blue: 230 / 255, opacity: 1),
        markDot: Color(.sRGB, red: 198 / 255, green: 243 / 255, blue: 107 / 255, opacity: 1)
    )

    public static let paper = Colors(
        bg: Color(.sRGB, red: 244 / 255, green: 241 / 255, blue: 234 / 255, opacity: 1),
        panel: Color(.sRGB, red: 251 / 255, green: 250 / 255, blue: 246 / 255, opacity: 1),
        hover: Color(.sRGB, red: 238 / 255, green: 234 / 255, blue: 226 / 255, opacity: 1),
        rule: Color(.sRGB, red: 220 / 255, green: 215 / 255, blue: 204 / 255, opacity: 1),
        ruleStrong: Color(.sRGB, red: 201 / 255, green: 195 / 255, blue: 183 / 255, opacity: 1),
        text: Color(.sRGB, red: 20 / 255, green: 19 / 255, blue: 17 / 255, opacity: 1),
        text2: Color(.sRGB, red: 74 / 255, green: 70 / 255, blue: 63 / 255, opacity: 1),
        label: Color(.sRGB, red: 107 / 255, green: 102 / 255, blue: 93 / 255, opacity: 1),
        primaryBg: Color(.sRGB, red: 20 / 255, green: 19 / 255, blue: 17 / 255, opacity: 1),
        primaryHover: Color(.sRGB, red: 74 / 255, green: 70 / 255, blue: 63 / 255, opacity: 1),
        primaryInk: Color(.sRGB, red: 244 / 255, green: 241 / 255, blue: 234 / 255, opacity: 1),
        focus: Color(.sRGB, red: 70 / 255, green: 112 / 255, blue: 12 / 255, opacity: 1),
        signalWash: Color(.sRGB, red: 70 / 255, green: 112 / 255, blue: 12 / 255, opacity: 0.1),
        delWash: Color(.sRGB, red: 107 / 255, green: 102 / 255, blue: 93 / 255, opacity: 0.1),
        beacon: Color(.sRGB, red: 91 / 255, green: 63 / 255, blue: 196 / 255, opacity: 1),
        codeBg: Color(.sRGB, red: 240 / 255, green: 237 / 255, blue: 229 / 255, opacity: 1),
        scrim: Color(.sRGB, red: 20 / 255, green: 19 / 255, blue: 17 / 255, opacity: 0.34),
        markWire: Color(.sRGB, red: 20 / 255, green: 19 / 255, blue: 17 / 255, opacity: 1),
        markDot: Color(.sRGB, red: 20 / 255, green: 19 / 255, blue: 17 / 255, opacity: 1)
    )

    /// The attention colour when the person picks another than beacon (violet).
    public static let attentionAlt: [String: (dark: Color, paper: Color)] = [
        "teal": (Color(.sRGB, red: 95 / 255, green: 212 / 255, blue: 196 / 255, opacity: 1), Color(.sRGB, red: 11 / 255, green: 110 / 255, blue: 102 / 255, opacity: 1))
    ]

    public struct Status: Equatable, Sendable {
        public let key: String, mark: String, color: String, word: String
    }
    /// Most urgent first: a row shows the first that applies. The keys are a stable contract.
    public static let status: [Status] = [
        Status(key: "needsYou", mark: "dot", color: "beacon", word: "needs you"),
        Status(key: "failed", mark: "crossed-circle", color: "text2", word: "failed"),
        Status(key: "running", mark: "ring", color: "focus", word: "running"),
        Status(key: "unread", mark: "dot", color: "text", word: "unread"),
        Status(key: "done", mark: "hollow-dot", color: "label", word: "done")
    ]

    public enum Radius {
        public static let chip: CGFloat = 4
        public static let field: CGFloat = 8
        public static let button: CGFloat = 8
        public static let buttonTouch: CGFloat = 10
        public static let card: CGFloat = 12
        public static let cardPhone: CGFloat = 10
        public static let sheet: CGFloat = 14
        public static let bubble: CGFloat = 12
        public static let full: CGFloat = 999
    }

    public enum Control {
        public static let xs: CGFloat = 28
        public static let sm: CGFloat = 32
        public static let touch: CGFloat = 44
        public static let touchLg: CGFloat = 54
    }

    public static let space: [CGFloat] = [0, 2, 4, 8, 12, 16, 24, 32, 48, 64]

    /// Durations in milliseconds, and the easing curve's control points.
    public enum Motion {
        public static let tap: Double = 120
        public static let panel: Double = 220
        public static let sheet: Double = 280
        public static let reveal: Double = 150
        public static let hold: Double = 600
        public static let undo: Double = 4000
        public static let ease: [Double] = [0.25, 0.1, 0.25, 1]
    }

    /// [size, line height] in points, desktop and the Capsule.
    public enum TypeScale {
        public static let meta: (size: CGFloat, line: CGFloat) = (12, 16)
        public static let base: (size: CGFloat, line: CGFloat) = (13, 18)
        public static let read: (size: CGFloat, line: CGFloat) = (15, 22)
        public static let title: (size: CGFloat, line: CGFloat) = (20, 26)
        public static let hero: (size: CGFloat, line: CGFloat) = (28, 34)
    }

    /// [size, line height] in points on a phone: the read and title steps are two larger.
    public enum PhoneTypeScale {
        public static let meta: (size: CGFloat, line: CGFloat) = (12, 16)
        public static let base: (size: CGFloat, line: CGFloat) = (13, 18)
        public static let read: (size: CGFloat, line: CGFloat) = (17, 24)
        public static let title: (size: CGFloat, line: CGFloat) = (22, 28)
        public static let hero: (size: CGFloat, line: CGFloat) = (28, 34)
    }

    /// Sizes JetBrains Mono may use, in points.
    public static let monoSizes: [CGFloat] = [12, 13]

    public static let fontSans = "Instrument Sans"
    public static let fontMono = "JetBrains Mono"
}
