// @ts-check
// What the root host helper (box/vyre `space-helper`) learns about app modules. It runs this file inside the recorded vyre image, as an unprivileged user with no network and a read-only
// filesystem, and reads stdout only. Two commands:
//
//   node host-plan.js list            one line per catalog app, fields separated by one space (`-` is empty); root checks every field again before it keeps the line
//   node host-plan.js compose <name>  the compose file for one app (root lints it against the list line before it runs it)
//
// Both come from the catalog manifests and manifest.js, the same checks the docker-direct driver uses. Nothing here is a request from a person or from the daemon.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { checkAppModule } from "./manifest.js";

const CATALOG = path.join(path.dirname(fileURLToPath(import.meta.url)), "catalog");

/** The checked catalog, by name. A manifest that fails its check is left out, as in the daemon. */
export function catalogOf(dir = CATALOG) {
  /** @type {Map<string, any>} */ const out = new Map();
  for (const f of fs.readdirSync(dir).filter(x => x.endsWith(".json")).sort()) {
    try {
      const m = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
      if (checkAppModule(m).length === 0) out.set(m.name, m);
    } catch { /* left out */ }
  }
  return out;
}

const words = (/** @type {string[]} */ a) => (a.length ? a.join("+") : "-");

/**
 * The list lines: `name image port memoryMb cpus pids hookPort script exec outputs healthPath healthOk startS`. A manifest with no hook port is not listed (a box starts only apps that have one).
 * @param {Map<string, any>} [cat]
 */
export function listLines(cat = catalogOf()) {
  const out = [];
  for (const m of cat.values()) {
    const a = m.app;
    if (!a.hookPort) continue;
    const b = a.bootstrap;
    out.push([m.name, a.image, a.port, a.limits.memoryMb, a.limits.cpus, a.limits.pids, a.hookPort,
      b ? b.script : "-", b ? words(b.exec) : "-", b ? words(b.outputs.map((/** @type {any} */ o) => o.name)) : "-",
      a.health.path, words(a.health.ok.map(String)), a.health.startS || 120].join(" "));
  }
  return out;
}

/** The address of the app as the daemon reaches it on the app's network. */
export const originOf = (/** @type {string} */ name, /** @type {number} */ port) => `http://vyre-app-${name}:${port}`;

/** A compose value: double-quoted, characters that compose could read as something else are refused. @param {string} v */
function q(v) {
  if (!/^[A-Za-z0-9_./:@+= -]*$/.test(v)) throw new Error(`a value the generator will not write: ${v.slice(0, 40)}`);
  return `"${v}"`;
}

/** @param {string} name @param {Map<string, any>} [cat] */
export function composeFile(name, cat = catalogOf()) {
  const m = cat.get(name);
  if (!m || !m.app.hookPort) throw new Error(`no app called ${name}`);
  const a = m.app;
  const p = `vyre-app-${name}`;
  const env = Object.entries(a.env || {}).map(([k, v]) => {
    // Only {origin} and {name} are known here: a box has no hook url or key at the time the app starts (root makes those for the setup step).
    const f = String(v).replace(/\{([a-z_]+)\}/g, (_x, k2) => (k2 === "origin" ? originOf(name, a.port) : k2 === "name" ? name : (() => { throw new Error(`${k} uses {${k2}}, which a box does not fill`); })()));
    return `      ${k}: ${q(f)}`;
  });
  for (const s of a.secrets || []) env.push(`      ${s.env}: \${${s.env}}`);
  const lines = ["# Generated by Vyre (core/appmods/host-plan.js)", `name: ${p}`, "services:", "  app:", `    image: ${a.image}`, `    container_name: ${p}`, '    restart: "no"',
    `    mem_limit: ${a.limits.memoryMb}m`, `    memswap_limit: ${a.limits.memoryMb}m`, `    cpus: ${a.limits.cpus}`, `    pids_limit: ${a.limits.pids}`,
    "    cap_drop:", "      - ALL", "    security_opt:", "      - no-new-privileges:true", "    init: true", "    networks:", "      - net"];
  if ((a.volumes || []).length) { lines.push("    volumes:"); for (const v of a.volumes) lines.push(`      - ${v.name}:${v.path}`); }
  if (env.length) { lines.push("    environment:", ...env); }
  lines.push("networks:", "  net:", "    internal: true");
  if ((a.volumes || []).length) { lines.push("volumes:"); for (const v of a.volumes) lines.push(`  ${v.name}:`, `    name: ${p}_${v.name}`); }
  return lines.join("\n") + "\n";
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const [cmd, name] = process.argv.slice(2);
  if (cmd === "list") process.stdout.write(listLines().join("\n") + (listLines().length ? "\n" : ""));
  else if (cmd === "compose" && name) process.stdout.write(composeFile(name));
  else { process.stderr.write("host-plan.js list | compose <name>\n"); process.exit(2); }
}
