// @ts-check
// What root learns about a published server on a host-helper server (core/appmods/host-pub.js): the request judged by the daemon's own rules, and the compose file root lints and runs.
import "../../scripts/mac-test-guard.mjs";
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { spawnSync } from "node:child_process";
import { check, compose, run } from "./host-pub.js";

/** `check` reads the Dockerfile at /ctx: the test hands it one through a module-level read stand-in. */
const withDockerfile = (/** @type {string} */ text, /** @type {() => any} */ f) => {
  const real = fs.readFileSync;
  /** @type {any} */ (fs).readFileSync = (/** @type {any} */ p, /** @type {any} */ ...r) => (p === "/ctx/Dockerfile" ? (text === null ? (() => { throw new Error("none"); })() : text) : real(p, ...r));
  try { return f(); } finally { fs.readFileSync = real; }
};
const ok = ["northwind", "8080", "512", "0.5", "256", "/", "200+404", "60"];

test("check: a good request and Dockerfile are ok; every refusal is the daemon's own sentence, so the helper and the module cannot disagree", () => {
  withDockerfile("FROM node:22-alpine\nEXPOSE 8080\n", () => assert.equal(check(ok), "ok"));
  withDockerfile("FROM node:22-alpine\n", () => assert.equal(check(ok), "ok"));
  withDockerfile("FROM evil.example/x\n", () => assert.match(check(ok), /^refused: the Dockerfile starts from evil\.example\/x/));
  withDockerfile("# syntax=evil/x\nFROM alpine\n", () => assert.match(check(ok), /^refused: the Dockerfile names its own build frontend/));
  withDockerfile("FROM alpine\nCOPY --from=evil.example/x /a /a\n", () => assert.match(check(ok), /^refused: the Dockerfile takes files from/));
  withDockerfile(null, () => assert.match(check(ok), /no Dockerfile/));
  withDockerfile("FROM alpine\n", () => {
    assert.match(check(["documents", ...ok.slice(1)]), /^refused: documents is the name of an app that ships with Vyre/);
    assert.match(check(["pdf", ...ok.slice(1)]), /^refused: pdf is the name/);
    assert.match(check(["www", ...ok.slice(1)]), /^refused: www is a name Vyre keeps/);
    assert.match(check(["northwind", "8080", "4096", "0.5", "256", "/", "200", "60"]), /memoryMb is at most 2048/);
    assert.match(check(["northwind", "0", "512", "0.5", "256", "/", "200", "60"]), /^refused: app\.port/);
    assert.match(check(["northwind", "8080", "512", "0.5", "256", "/", "200", "9999"]), /start time is 1 to 600/);
    assert.match(check(["northwind", "8080", "512", "0.5", "256", "health", "200", "60"]), /^refused: app\.health\.path/);
  });
});

test("compose: the shape root's lint accepts: one service, read-only root, one data volume, secrets by name, one internal network, nothing published", () => {
  const c = compose(["northwind", "vyre-pub/northwind:0123456789abcdef", "8080", "512", "0.5", "256", "GREETING+STRIPE_KEY"]);
  for (const want of ["# Generated by Vyre (core/appmods/host-pub.js)", "name: vyre-app-northwind", "    image: vyre-pub/northwind:0123456789abcdef", "    container_name: vyre-app-northwind", '    restart: "no"', "    mem_limit: 512m",
    "    memswap_limit: 512m", "    cpus: 0.5", "    pids_limit: 256", "    read_only: true", "    tmpfs:\n      - /tmp:rw,size=64m,mode=1777", "    cap_drop:\n      - ALL", "      - no-new-privileges:true",
    "    volumes:\n      - data:/data", "      GREETING: ${GREETING}", "      STRIPE_KEY: ${STRIPE_KEY}", "networks:\n  net:\n    internal: true", "volumes:\n  data:\n    name: vyre-app-northwind_data"]) assert.ok(c.includes(want), want);
  assert.ok(!/ports:|privileged|cap_add|network_mode|\/var\/run|docker\.sock/.test(c));
  assert.ok(!compose(["northwind", "img:1", "8080", "512", "0.5", "256", "-"]).includes("environment:"), "no secrets, no environment");
  assert.throws(() => compose(["northwind", "img:1", "8080", "512", "0.5", "256", "lower"]), /not a name an environment variable/);
  assert.throws(() => compose(["documents", "img:1", "8080", "512", "0.5", "256", "-"]), /ships with Vyre/);
});

test("the command line the helper uses: run(argv) prints, anything else is an error and prints nothing", () => {
  assert.match(run(["compose", "northwind", "img:1", "8080", "512", "0.5", "256", "-"]), /^# Generated by Vyre/);
  assert.throws(() => run(["compose", "x"]), /host-pub\.js/);
  assert.throws(() => run(["rm"]), /host-pub\.js/);
  const r = spawnSync(process.execPath, ["--input-type=module", "-e", 'import("/opt/none")'], { encoding: "utf8" });
  assert.notEqual(r.status, 0);
});
