// @ts-check
// What the root host helper (box/vyre `space-helper`) learns about a site's server a person published (team/contracts/builder.md, the container path on a server that runs apps through its host
// helper). Like host-plan.js it runs inside the recorded vyre image, as an unprivileged user with no network and a read-only filesystem, and its stdout is all root reads. Two commands:
//
//   check <name> <port> <memMb> <cpus> <pids> <healthPath> <healthOk> <startS>   the request root claimed, judged by the daemon's own rules (published.js, container.js): the manifest it would
//                                                                                 make, and the Dockerfile in /ctx, read-only. Prints `ok` or `refused: <reason>`.
//   compose <name> <image> <port> <memMb> <cpus> <pids> <secrets>                the compose file for the server (secrets are NAMES joined by +, or -); root lints it before it runs it.
//
// Nothing here is a request from a person or the daemon: root passes only values it checked against its own patterns first.
import fs from "node:fs";
import { checkDockerfile } from "../../lib/publish/dockerfile.js";
import { publishedManifest, checkPublished } from "./published.js";
import { catalogOf } from "./host-plan.js";

const ID0 = "dep_0000000000000000";
const IMG0 = "sha256:" + "0".repeat(64);

/** @param {string[]} a name port memMb cpus pids healthPath healthOk startS */
function manifestOf(a) {
  const [name, port, mem, cpus, pids, hpath, hok, hstart] = a;
  return publishedManifest({ id: ID0, name, version: 1, runtime: { kind: "image", image: IMG0, port: Number(port), health: { path: hpath, ok: String(hok).split("+").map(Number) } },
    limits: { memoryMb: Number(mem), cpus: Number(cpus), pids: Number(pids) } }, { catalogNames: [...catalogOf().keys()], public: true });
}

/** @param {string[]} a @returns {string} */
export function check(a) {
  try {
    const m = manifestOf(a);
    const problems = checkPublished(m);
    if (problems.length) return `refused: ${problems.map(p => `${p.path}: ${p.message}`).join("; ")}`;
    const hs = Number(a[7]);
    if (!(Number.isInteger(hs) && hs >= 1 && hs <= 600)) return "refused: the start time is 1 to 600 seconds";
    let text; try { text = fs.readFileSync(`${process.env.VYRE_PUB_CTX || "/ctx"}/Dockerfile`, "utf8"); } catch { return "refused: the folder has no Dockerfile at its top"; }
    if (text.length > 262144) return "refused: the Dockerfile is too long";
    checkDockerfile(text, { allow: [] });
    return "ok";
  } catch (e) { return `refused: ${String(/** @type {Error} */ (e).message).replace(/[\r\n]+/g, " ").slice(0, 300)}`; }
}

/**
 * The compose file of a published server: one service, the image root tagged, the limits it checked, a read-only root with a tmpfs /tmp, one named data volume, its granted secrets by name from root's
 * own env file, one internal network. No port, no host path, no capability, no webhook door.
 * @param {string[]} a name image port memMb cpus pids secrets
 */
export function compose(a) {
  const [name, image, port, mem, cpus, pids, secrets] = a;
  const m = manifestOf([name, port, mem, cpus, pids, "/", "200", "60"]);
  const p = `vyre-app-${name}`;
  const names = secrets && secrets !== "-" ? secrets.split("+") : [];
  for (const s of names) if (!/^[A-Z][A-Z0-9_]{0,63}$/.test(s)) throw new Error(`${s} is not a name an environment variable can have`);
  const lines = ["# Generated by Vyre (core/appmods/host-pub.js)", `name: ${p}`, "services:", "  app:", `    image: ${image}`, `    container_name: ${p}`, '    restart: "no"',
    `    mem_limit: ${m.app.limits.memoryMb}m`, `    memswap_limit: ${m.app.limits.memoryMb}m`, `    cpus: ${m.app.limits.cpus}`, `    pids_limit: ${m.app.limits.pids}`,
    "    read_only: true", "    tmpfs:", "      - /tmp:rw,size=64m,mode=1777", "    cap_drop:", "      - ALL", "    security_opt:", "      - no-new-privileges:true", "    init: true", "    logging:", "      driver: json-file", "      options:", '        max-size: "10m"', '        max-file: "3"', "    networks:", "      - net",
    "    volumes:", "      - data:/data"];
  if (names.length) { lines.push("    environment:"); for (const s of names) lines.push(`      ${s}: \${${s}}`); }
  lines.push("networks:", "  net:", "    internal: true", "volumes:", "  data:", `    name: ${p}_data`);
  return lines.join("\n") + "\n";
}

/** The one entry the helper calls: `run(argv)` prints what the command answers. @param {string[]} argv */
export function run(argv) {
  const [cmd, ...a] = argv;
  if (cmd === "check" && a.length === 8) return check(a) + "\n";
  if (cmd === "compose" && a.length === 7) return compose(a);
  throw new Error("host-pub.js check|compose");
}
