// @ts-check
// What the root host helper reads out of the vyre image (core/appmods/host-plan.js): the catalog list and one compose file per app. The helper lints the compose file again against the list line
// (test/space-helper-apps.test.js); here the generator itself: what it writes, and what it refuses to write.
import "../../scripts/mac-test-guard.mjs";
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { spawnSync } from "node:child_process";
import { catalogOf, listLines, composeFile, originOf } from "./host-plan.js";

const documents = () => JSON.parse(fs.readFileSync(new URL("./catalog/documents.json", import.meta.url), "utf8"));

test("list: one line per app with a hook port, thirteen fields, from the checked manifests", () => {
  const lines = listLines();
  assert.equal(lines.length, 2);
  const f = lines.find(l => l.startsWith("documents ")).split(" ");
  assert.equal(f.length, 13);
  const m = documents();
  assert.deepEqual(f, [m.name, m.app.image, "3000", "1536", "1.5", "512", "43001", "docuseal-bootstrap.rb", "bin/rails+runner", "api_token+login_password", "/", "200+302", "120"]);
  // an app with no hook port is not listed: a box starts only apps that have one
  const cat = new Map([["x", { ...m, name: "x", app: { ...m.app, hookPort: undefined } }]]);
  assert.deepEqual(listLines(cat), []);
  // an app with no setup prints dashes
  const bare = { ...m, app: { ...m.app, bootstrap: undefined } };
  assert.deepEqual(listLines(new Map([["documents", bare]]))[0].split(" ").slice(7, 10), ["-", "-", "-"]);
});

test("compose: the shape the helper's lint accepts, nothing it does not", () => {
  const c = composeFile("documents");
  assert.match(c, /^# Generated by Vyre/);
  assert.match(c, /^name: vyre-app-documents$/m);
  assert.match(c, /^    container_name: vyre-app-documents$/m);
  assert.match(c, /^    restart: "no"$/m);
  assert.match(c, /^    cap_drop:\n      - ALL$/m);
  assert.match(c, /^    security_opt:\n      - no-new-privileges:true$/m);
  assert.match(c, /^    mem_limit: 1536m$/m);
  assert.match(c, /^    memswap_limit: 1536m$/m);
  assert.match(c, /^      - data:\/data\/docuseal$/m);
  assert.match(c, /^      APP_URL: "http:\/\/vyre-app-documents:3000"$/m);
  assert.match(c, /^      SECRET_KEY_BASE: \$\{SECRET_KEY_BASE\}$/m);
  assert.match(c, /^  net:\n    internal: true$/m);
  assert.match(c, /^  data:\n    name: vyre-app-documents_data$/m);
  assert.ok(!/privileged|ports:|network_mode|cap_add|env_file|pid:|user:/.test(c));
  assert.equal(originOf("documents", 3000), "http://vyre-app-documents:3000");
});

test("compose: an unknown app, an app with no hook port, a placeholder a box does not fill, and a value compose could read as something else are refused", () => {
  assert.throws(() => composeFile("nothere"), /no app called/);
  const m = documents();
  const mk = (/** @type {any} */ app) => new Map([["documents", { ...m, app: { ...m.app, ...app } }]]);
  assert.throws(() => composeFile("documents", mk({ hookPort: undefined })), /no app called/);
  assert.throws(() => composeFile("documents", mk({ env: { A: "{hook_url}" } })), /which a box does not fill/);
  assert.throws(() => composeFile("documents", mk({ env: { A: "$(id)" } })), /will not write/);
  assert.throws(() => composeFile("documents", mk({ env: { A: "x`y" } })), /will not write/);
  assert.throws(() => composeFile("documents", mk({ env: { A: "x\ny" } })), /will not write/);
});

test("the command line: `list` and `compose <name>` print, anything else is a usage error and prints nothing", () => {
  const run = (/** @type {string[]} */ ...a) => spawnSync(process.execPath, [new URL("./host-plan.js", import.meta.url).pathname, ...a], { encoding: "utf8" });
  assert.equal(run("list").stdout.trim().split("\n").length, 2);
  assert.match(run("compose", "documents").stdout, /^# Generated by Vyre/);
  const bad = run("compose", "nothere");
  assert.notEqual(bad.status, 0);
  assert.equal(bad.stdout, "");
  const none = run();
  assert.equal(none.status, 2);
  assert.equal(none.stdout, "");
});

test("the catalog the helper reads is the daemon's: every manifest that passes its check, none that fails", () => {
  assert.deepEqual([...catalogOf().keys()], ["documents", "pdf"]);
});

test("the PDF converter is listed and composed like any app: its flags are environment values, it has no volume and no setup", () => {
  const line = listLines().find(l => l.startsWith("pdf ")) || "";
  const f = line.split(" ");
  assert.equal(f.length, 13);
  assert.deepEqual([f[0], f[2], f[3], f[4], f[5], f[6], f[7], f[8], f[9], f[10], f[11], f[12]], ["pdf", "3000", "1024", "1", "256", "43002", "-", "-", "-", "/health", "200", "90"]);
  const c = composeFile("pdf");
  assert.match(c, /^    image: gotenberg\/gotenberg:8\.37\.0@sha256:[0-9a-f]{64}$/m);
  assert.match(c, /^      CHROMIUM_DISABLE_ROUTES: "true"$/m);
  assert.match(c, /^      API_TIMEOUT: "120s"$/m);
  assert.doesNotMatch(c, /volumes:\n      - /);
  assert.match(c, /^  net:\n    internal: true$/m, "on an internal network: it has no way out");
});
