// @ts-check
// The Deck's palette comes from the one app's tokens: deck/css/tokens.css is generated by
// scripts/gen-tokens from docs/design/one-app/tokens.json, every page links it before deck.css
// (and config's /theme.css after both, so a user's colours win), and every colour deck.css names
// is defined by one of the two.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const DECK = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO = path.resolve(DECK, "..");
const read = (/** @type {string} */ f) => fs.readFileSync(path.join(DECK, f), "utf8");

test("tokens: every page links tokens.css, then deck.css, then config's theme.css", () => {
  for (const page of ["index.html", "onboard/index.html", "onboard/passkey/index.html"]) {
    const html = read(page);
    const at = (/** @type {string} */ href) => html.indexOf(`<link rel="stylesheet" href="${href}">`);
    assert.ok(at("/css/tokens.css") > 0, `${page} links tokens.css`);
    assert.ok(at("/css/tokens.css") < at("/css/deck.css"), `${page}: tokens.css before deck.css`);
    assert.ok(at("/css/deck.css") < at("/theme.css"), `${page}: config's colours last, so they win`);
  }
});

test("tokens: the service worker keeps tokens.css at install", () => {
  const m = /const SHELL = \[([\s\S]*?)\];/.exec(read("sw.js"));
  assert.ok(m && m[1].includes('"/css/tokens.css"'));
});

/** Every custom property a stylesheet declares. @param {string} css */
const declared = css => new Set([...css.matchAll(/(?:^|[;{\s])--([a-zA-Z0-9-]+)\s*:/g)].map(m => m[1]));

test("tokens: every var() deck.css paints a colour with is defined in tokens.css or deck.css", () => {
  const deck = read("css/deck.css"), tokens = read("css/tokens.css");
  const defined = new Set([...declared(deck), ...declared(tokens)]);
  const COLOUR_PROP = /^(--[a-z0-9-]+|color|background(-color)?|border(-(top|right|bottom|left))?(-color)?|outline(-color)?|fill|stroke|box-shadow|text-decoration(-color)?|caret-color|accent-color|column-rule(-color)?)$/;
  /** @type {string[]} */ const missing = [];
  let seen = 0;
  const body = deck.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const m of body.matchAll(/([a-zA-Z-]+)\s*:\s*([^;{}]*var\([^;{}]*)/g)) {
    if (!COLOUR_PROP.test(m[1])) continue;
    // var(--x) with no fallback must be defined; var(--x, fallback) may rely on the fallback.
    for (const v of m[2].matchAll(/var\(--([a-zA-Z0-9-]+)\s*(,)?/g)) {
      seen++;
      if (!v[2] && !defined.has(v[1])) missing.push(`${m[1]}: var(--${v[1]})`);
    }
  }
  assert.ok(seen > 100, `found the colour uses (${seen})`);
  assert.deepEqual(missing, []);
});

test("tokens: deck.css leaves the token roles to tokens.css (no second copy that could drift)", () => {
  const tokens = declared(read("css/tokens.css"));
  const root = /^:root \{([\s\S]*?)^\}/m.exec(read("css/deck.css"));
  const paper = /^:root\[data-theme="paper"\] \{([\s\S]*?)^\}/m.exec(read("css/deck.css"));
  assert.ok(root && paper);
  for (const [name, m] of [[":root", root], ["paper", paper]]) {
    const again = [...declared(m[1])].filter(k => tokens.has(k));
    assert.deepEqual(again, [], `deck.css ${name} redeclares ${again.join(", ")}`);
  }
});

test("tokens: deck/css/tokens.css is what scripts/gen-tokens renders from tokens.json", () => {
  // Only the Deck's output: gen-tokens also renders the app's tokens.ts, which lives with the app.
  execFileSync(process.execPath, [path.join(REPO, "scripts/gen-tokens"), "--check", "--css", "deck/css/tokens.css"],
    { cwd: REPO, stdio: "pipe" });
});

/** Every file under deck/ a raw-name check reads: stylesheets, scripts and pages, not vendor code. */
const deckSources = () => {
  /** @type {string[]} */ const out = [];
  const walk = (/** @type {string} */ dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) { if (e.name !== "vendor" && e.name !== "node_modules") walk(p); continue; }
      if (/\.(css|js|html)$/.test(e.name) && !e.name.endsWith(".test.js")) out.push(p);
    }
  };
  walk(DECK);
  return out;
};

test("tokens: the Deck's raw palette and radii are gone; every use goes through a token role", () => {
  // --signal-wash, --beacon-ink, --beacon-dot and --beacon-badge-ink are tokens and stay.
  const RAW = /--(graphite|carbon|raised|ash|stone|bone|signal|signal-hover|signal-ink|signal-ink-text|beacon|r-[1-4])(?![\w-])/g;
  /** @type {string[]} */ const found = [];
  let files = 0;
  for (const f of deckSources()) {
    files++;
    fs.readFileSync(f, "utf8").split("\n").forEach((line, i) => {
      for (const m of line.matchAll(RAW)) found.push(`${path.relative(DECK, f)}:${i + 1} ${m[0]}`);
    });
  }
  assert.ok(files > 50, `read the Deck's sources (${files})`);
  assert.deepEqual(found, []);
});

test("tokens: deck.css does not define the radius tokens (they come from tokens.css, with fallbacks until then)", () => {
  const radius = [...declared(read("css/deck.css"))].filter(k => k.startsWith("radius-"));
  assert.deepEqual(radius, []);
});

test("tokens: the fixed --swatch-* colours are defined once in deck.css and drawn only by the Computer preview", () => {
  const swatches = [...declared(read("css/deck.css"))].filter(k => k.startsWith("swatch-"));
  assert.ok(swatches.length > 0);
  for (const f of deckSources()) {
    const rel = path.relative(DECK, f);
    if (rel === path.join("css", "deck.css")) continue;
    assert.doesNotMatch(fs.readFileSync(f, "utf8"), /--swatch-[\w-]+\s*:/, `${rel} defines a swatch`);
    if (rel !== path.join("css", "views", "agents.css")) assert.doesNotMatch(fs.readFileSync(f, "utf8"), /var\(--swatch-/, `${rel} uses a swatch`);
  }
});
