// @ts-check
// The Deck's palette comes from the one app's tokens: deck/css/tokens.css is generated by
// scripts/gen-tokens from docs/design/one-app/tokens.json, every page links it before deck.css
// (and config's /theme.css after both, so a user's colours win), and every colour deck.css names
// is defined by one of the two.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const DECK = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO = path.resolve(DECK, "..");
const read = (/** @type {string} */ f) => fs.readFileSync(path.join(DECK, f), "utf8");

test("tokens: every page links tokens.css, then deck.css, then config's theme.css", () => {
  for (const page of ["index.html", "onboard/index.html", "onboard/passkey/index.html"]) {
    const html = read(page);
    const at = (/** @type {string} */ href) => html.indexOf(`<link rel="stylesheet" href="${href}">`);
    assert.ok(at("/css/tokens.css") > 0, `${page} links tokens.css`);
    assert.ok(at("/css/tokens.css") < at("/css/deck.css"), `${page}: tokens.css before deck.css`);
    assert.ok(at("/css/deck.css") < at("/theme.css"), `${page}: config's colours last, so they win`);
  }
});

test("tokens: the service worker keeps tokens.css at install", () => {
  const m = /const SHELL = \[([\s\S]*?)\];/.exec(read("sw.js"));
  assert.ok(m && m[1].includes('"/css/tokens.css"'));
});

/** Every custom property a stylesheet declares. @param {string} css */
const declared = css => new Set([...css.matchAll(/(?:^|[;{\s])--([a-zA-Z0-9-]+)\s*:/g)].map(m => m[1]));

test("tokens: every var() deck.css paints a colour with is defined in tokens.css or deck.css", () => {
  const deck = read("css/deck.css"), tokens = read("css/tokens.css");
  const defined = new Set([...declared(deck), ...declared(tokens)]);
  const COLOUR_PROP = /^(--[a-z0-9-]+|color|background(-color)?|border(-(top|right|bottom|left))?(-color)?|outline(-color)?|fill|stroke|box-shadow|text-decoration(-color)?|caret-color|accent-color|column-rule(-color)?)$/;
  /** @type {string[]} */ const missing = [];
  let seen = 0;
  const body = deck.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const m of body.matchAll(/([a-zA-Z-]+)\s*:\s*([^;{}]*var\([^;{}]*)/g)) {
    if (!COLOUR_PROP.test(m[1])) continue;
    // var(--x) with no fallback must be defined; var(--x, fallback) may rely on the fallback.
    for (const v of m[2].matchAll(/var\(--([a-zA-Z0-9-]+)\s*(,)?/g)) {
      seen++;
      if (!v[2] && !defined.has(v[1])) missing.push(`${m[1]}: var(--${v[1]})`);
    }
  }
  assert.ok(seen > 100, `found the colour uses (${seen})`);
  assert.deepEqual(missing, []);
});

test("tokens: deck.css leaves the token roles to tokens.css (no second copy that could drift)", () => {
  const tokens = declared(read("css/tokens.css"));
  const root = /^:root \{([\s\S]*?)^\}/m.exec(read("css/deck.css"));
  const paper = /^:root\[data-theme="paper"\] \{([\s\S]*?)^\}/m.exec(read("css/deck.css"));
  assert.ok(root && paper);
  for (const [name, m] of [[":root", root], ["paper", paper]]) {
    const again = [...declared(m[1])].filter(k => tokens.has(k));
    assert.deepEqual(again, [], `deck.css ${name} redeclares ${again.join(", ")}`);
  }
});

test("tokens: deck/css/tokens.css is what scripts/gen-tokens renders from tokens.json", () => {
  // Only the Deck's output: gen-tokens also renders the app's tokens.ts, which lives with the app.
  execFileSync(process.execPath, [path.join(REPO, "scripts/gen-tokens"), "--check", "--css", "deck/css/tokens.css"],
    { cwd: REPO, stdio: "pipe" });
});
