// @ts-check
// Red-team refusals for presence (0.2 PLAN row 12): the keys that count as a person being there, and the proofs that use them. Each
// test ATTEMPTS the attack against the real Presence class in a temp database and asserts the refusal. No daemon, no browser, no real
// device material: every key here is generated by the test. Named "redteam P-<ID>: <attack> is refused".
// IDs: P-M7 (reviews/vault.md M7, the RSA branch), P-CAP (a Capsule key is ES256 and nothing else), P-PROOF (replay, age, binding),
// P-CODE (one-time codes), P-GRANT (the first-passkey grant), P-SESSION (a session proves only what and where it should).

import { test } from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import path from "node:path";
import { Presence, inputHash } from "../../core/presence/index.js";
import { open } from "../../core/store/index.js";
import { tempHome } from "../helpers.js";

const APPROVE = { tool: "gate.approve", input: { id: "a1" } };
const OTHER = { tool: "gate.approve", input: { id: "b2" } };
const WHO = "tailnet:alex@example.com";
const spki = k => k.export({ format: "der", type: "spki" }).toString("base64url");
const rsa = (modulusLength = 2048, publicExponent = 65537) => crypto.generateKeyPairSync("rsa", { modulusLength, publicExponent });
const p256 = () => crypto.generateKeyPairSync("ec", { namedCurve: "P-256" });
const message = (tool, input, ts, nonce) => Buffer.from(`vyre-presence-v1\n${tool}\n${inputHash(input)}\n${ts}\n${nonce}`);

function setup(t, opts = {}) {
  const db = open(path.join(tempHome(t), "vyre.db"));
  t.after(() => db.close());
  let clock = 1_000_000;
  const p = new Presence({ db, platform: "linux", touchid: null, webauthn: null, now: () => clock, ...opts });
  return { p, db, now: () => clock, tick: ms => { clock += ms; } };
}

/** A signer for an enrolled key: ES256 (DER) for P-256, RS256 for RSA. */
function signer(method, id, pair) {
  const isRsa = pair.privateKey.asymmetricKeyType === "rsa";
  return (call, ts, nonce = crypto.randomBytes(12).toString("base64url")) => ({
    method, key: id, ts: String(ts), nonce,
    sig: crypto.sign("sha256", message(call.tool, call.input, ts, nonce), isRsa ? pair.privateKey : { key: pair.privateKey, dsaEncoding: "der" }).toString("base64url"),
  });
}

test("redteam P-M7: an RSA device key that is too small, has a weak exponent or the wrong alg is refused at enrollment", t => {
  const { p } = setup(t);
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spki(rsa(1024).publicKey), alg: -257 }), /2048|bits|small/i, "1024-bit RSA");
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spki(rsa(2048, 3).publicKey), alg: -257 }), /65537|exponent/i, "exponent 3");
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spki(rsa().publicKey), alg: -7 }), /P-256/, "an RSA key claiming ES256");
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spki(p256().publicKey), alg: -257 }), /RSA/, "an EC key claiming RS256");
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: spki(rsa().publicKey) }), /alg/, "no alg at all");
  assert.equal(p.keys().length, 0, "nothing was enrolled");
});

test("redteam P-M7b: an alg changed under an enrolled key never verifies, in either direction", async t => {
  const { p, db, now } = setup(t);
  const ec = p256(), rk = rsa();
  const e = p.enroll({ kind: "device", name: "phone", public_key: spki(ec.publicKey), alg: -7 });
  const r = p.enroll({ kind: "device", name: "laptop", public_key: spki(rk.publicKey), alg: -257 });
  db.prepare("UPDATE presence_keys SET alg = -257 WHERE id = ?").run(e.id);
  db.prepare("UPDATE presence_keys SET alg = -7 WHERE id = ?").run(r.id);
  for (const [id, pair] of [[e.id, ec], [r.id, rk]]) {
    const v = await p.verify({ ...APPROVE, caller: WHO, proof: signer("device", id, pair)(APPROVE, now()) });
    assert.equal(v.ok, false, `${id}: a signature under the wrong alg is refused`);
  }
});

test("redteam P-M7c: a JWK with private members, or a blob that carries primes, is refused as a public key", t => {
  const { p } = setup(t);
  const jwk = rsa().privateKey.export({ format: "jwk" });
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: JSON.stringify(jwk), alg: -257 }), /private/i, "a full private JWK");
  const { d: _d, p: _p, q: _q, dp: _dp, dq: _dq, qi: _qi, ...pub } = jwk;
  assert.ok(p.enroll({ kind: "device", name: "ok", public_key: JSON.stringify(pub), alg: -257 }).id, "its public half enrolls (control)");
  assert.throws(() => p.enroll({ kind: "device", name: "x", public_key: JSON.stringify({ ...pub, d: "AQAB" }), alg: -257 }), /private/i, "a public JWK plus one private member");
  assert.equal(p.keys().length, 1);
});

test("redteam P-CAP: a Capsule key is P-256 ES256 and nothing else, even written straight into the database", t => {
  const { p, db } = setup(t);
  const ed = crypto.generateKeyPairSync("ed25519");
  assert.throws(() => p.enroll({ kind: "capsule", name: "c", public_key: spki(ed.publicKey), alg: -8 }), /P-256|-7/, "an Ed25519 Capsule key");
  assert.throws(() => p.enroll({ kind: "capsule", name: "c", public_key: spki(rsa().publicKey), alg: -257 }), /P-256|-7/, "an RSA Capsule key");
  const ins = (id, alg) => db.prepare("INSERT INTO presence_keys (id, kind, name, public_key, alg, sign_count, created) VALUES (?,?,?,?,?,0,?)").run(id, "capsule", "c", spki(p256().publicKey), alg, 1);
  assert.throws(() => ins("raw-1", -8), /alg -7/);
  assert.throws(() => ins("raw-2", -257), /alg -7/);
  assert.throws(() => ins("raw-3", null), /alg -7/);
});

test("redteam P-PROOF: a signed proof cannot be replayed, used late, used for another call, or presented by another key", async t => {
  const { p, now, tick } = setup(t);
  const pair = p256(), other = p256();
  const a = p.enroll({ kind: "device", name: "phone", public_key: spki(pair.publicKey), alg: -7 });
  const b = p.enroll({ kind: "device", name: "tablet", public_key: spki(other.publicKey), alg: -7 });
  const sign = signer("device", a.id, pair);
  const good = sign(APPROVE, now());
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: good })).ok, true, "control: an honest proof works once");
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: good })).ok, false, "a replay of the same nonce");
  assert.equal((await p.verify({ ...OTHER, caller: WHO, proof: sign(APPROVE, now()) })).ok, false, "a proof for call A used for call B");
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: sign(APPROVE, now() - 61_000) })).ok, false, "too old");
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: sign(APPROVE, now() + 3_600_000) })).ok, false, "from the future");
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: { ...signer("device", b.id, pair)(APPROVE, now()) } })).ok, false, "signed by one key, claimed as another");
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: { ...sign(APPROVE, now()), method: "capsule" } })).ok, false, "a device key presented as the Capsule's");
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: { ...sign(APPROVE, now()), key: "no-such-key" } })).ok, false, "an unknown key id");
  const flipped = sign(APPROVE, now());
  const sig = Buffer.from(flipped.sig, "base64url"); sig[sig.length - 1] ^= 1;
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: { ...flipped, sig: sig.toString("base64url") } })).ok, false, "a flipped signature bit");
  tick(1);
});

test("redteam P-CODE: a one-time code enrolls once, never approves anything else, and dies at its ttl", async t => {
  const { p, tick } = setup(t);
  const c = p.mintCode();
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, proof: { method: "code", code: c.code } })).ok, false, "a code cannot approve a send");
  assert.equal((await p.verify({ tool: "vault.reveal", input: { name: "x" }, caller: WHO, proof: { method: "code", code: c.code } })).ok, false, "nor reveal a secret");
  const enroll = { tool: "presence.enroll", input: { kind: "device" }, caller: WHO };
  assert.equal((await p.verify({ ...enroll, proof: { method: "code", code: "WRONGCODE" } })).ok, false, "a wrong code");
  assert.equal((await p.verify({ ...enroll, proof: { method: "code", code: c.code } })).ok, true, "control: the right tool, once");
  assert.equal((await p.verify({ ...enroll, proof: { method: "code", code: c.code } })).ok, false, "a second use");
  const late = p.mintCode();
  tick(11 * 60_000);
  assert.equal((await p.verify({ ...enroll, proof: { method: "code", code: late.code } })).ok, false, "past ten minutes");
  assert.throws(() => p.mintCode({ ttl: 3_600_000 }), /10 minutes/, "no code lives longer than ten minutes");
  assert.throws(() => p.mintCode({ length: 4 }), /6 to 16/, "no short code");
});

test("redteam P-GRANT: the first-passkey grant enrolls one passkey for its own address, once, for its own device, before it expires", async t => {
  const { p, tick } = setup(t);
  const g = p.mintGrant({ stableId: "node-a" }, "alex.vyre.run");
  const enroll = (input, grant = g.grant, peer = { stableId: "node-a" }) => p.verify({ tool: "presence.enroll", input, caller: WHO, peer, proof: { method: "grant", grant } });
  assert.equal((await p.verify({ ...APPROVE, caller: WHO, peer: { stableId: "node-a" }, proof: { method: "grant", grant: g.grant } })).ok, false, "a grant cannot approve a send");
  assert.equal((await enroll({ kind: "device", rp_id: "alex.vyre.run" })).ok, false, "not a device key");
  assert.equal((await enroll({ kind: "capsule", rp_id: "alex.vyre.run" })).ok, false, "not a Capsule key");
  assert.equal((await enroll({ kind: "passkey", rp_id: "evil.example.test" })).ok, false, "not another address");
  assert.equal((await enroll({ kind: "passkey", rp_id: "alex.vyre.run" }, g.grant, { stableId: "node-b" })).ok, false, "not another device");
  assert.equal((await enroll({ kind: "passkey", rp_id: "alex.vyre.run" }, "wrong")).ok, false, "not a guessed grant");
  assert.equal((await enroll({ kind: "passkey", rp_id: "alex.vyre.run" })).ok, true, "control: the right kind, address and device");
  assert.equal((await enroll({ kind: "passkey", rp_id: "alex.vyre.run" })).ok, false, "a second use");
  const old = p.mintGrant({ stableId: "node-a" }, "alex.vyre.run");
  tick(6 * 60_000);
  assert.equal((await enroll({ kind: "passkey", rp_id: "alex.vyre.run" }, old.grant)).ok, false, "past five minutes");
});

test("redteam P-SESSION: a session proves only a tool that allows it, only on its own device, only with its secret, and ends when closed", async t => {
  const { p } = setup(t);
  const s = p.openSession({ method: "device", keyId: "k1", peer: { stableId: "phone" } });
  const proof = { method: "session", id: s.session, secret: s.secret };
  const allows = { presence: { session: () => true } };
  const reveal = { tool: "vault.reveal", input: { name: "x" }, caller: "deck" };
  assert.equal((await p.verify({ ...reveal, def: allows, peer: { stableId: "phone" }, proof })).ok, true, "control: its own device, the Deck, an item that allows it");
  assert.equal((await p.verify({ ...reveal, def: allows, peer: { stableId: "laptop" }, proof })).ok, false, "another device");
  assert.equal((await p.verify({ ...reveal, def: allows, peer: { stableId: "phone" }, proof: { ...proof, secret: "wrong" } })).ok, false, "a wrong secret");
  assert.equal((await p.verify({ ...reveal, def: { presence: { session: () => false } }, peer: { stableId: "phone" }, proof })).ok, false, "an item that wants its own proof every time");
  assert.equal((await p.verify({ ...reveal, caller: "cli", def: allows, peer: { stableId: "phone" }, proof })).ok, false, "a vault reveal from a terminal");
  assert.equal((await p.verify({ tool: "vault.put", input: { name: "x" }, caller: "deck", def: allows, peer: { stableId: "phone" }, proof })).ok, false, "a tool that is not session-eligible");
  assert.throws(() => p.openSession({ method: "code" }), /after Touch ID|device key|passkey/, "a code never opens a session");
  assert.throws(() => p.openSession({ method: "tty" }), /after Touch ID|device key|passkey/, "nor a terminal code");
  assert.ok(p.closeSession(s.session));
  assert.equal((await p.verify({ ...reveal, def: allows, peer: { stableId: "phone" }, proof })).ok, false, "after it is closed");
});
