// The lists a surface needs that an owner decides (FOUNDATION A5: a surface never keeps its own copy): generated here from the owner, so a surface imports a file that cannot drift.
//   web/js/one-yes-ops.generated.js            the Deck cannot import lib/, so the tools a yes may be reused for are written out from lib/one-yes-ops.js
//   apps/app/src/real/space-tools.generated.js every tool whose input takes a `space`, read from docs/reference/tools.md (itself generated from the tools' own schemas)
// `node scripts/gen-surface-lists.mjs` writes them; test/surface-lists.test.js fails when a written file is not what this makes.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { REUSE_OPS } from "../../lib/one-yes-ops.js";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/** The tools whose input names a `space`, from the generated tool reference. @param {string} md */
export function spaceTools(md) {
  const out = [];
  for (const part of md.split("\n### `").slice(1)) {
    const name = part.slice(0, part.indexOf("`"));
    const input = /- Input:\n((?:  - .*\n)+)/.exec(part);
    if (input && /^ {2}- `space` /m.test(input[1])) out.push(name);
  }
  return out.sort();
}

/** @returns {Record<string, string>} file (from the repo root) -> its content */
export function files() {
  const md = fs.readFileSync(path.join(ROOT, "docs/reference/tools.md"), "utf8");
  const head = (/** @type {string} */ what) => `// GENERATED by scripts/gen-surface-lists.mjs: ${what}. Do not edit; run the script.\n`;
  return {
    "web/js/one-yes-ops.generated.js": `${head("the tools a yes may be reused for, from lib/one-yes-ops.js")}export const REUSE_OPS = ${JSON.stringify(REUSE_OPS)};\n`,
    "apps/app/src/real/space-tools.generated.js": `${head("every tool whose input takes a space, from docs/reference/tools.md")}export const TOOLS_WITH_SPACE = ${JSON.stringify(spaceTools(md), null, 1)};\n`,
  };
}
