// @ts-check
// Renders docs/design/one-app/tokens.json for each surface: Swift for the Capsule, TypeScript for
// the Expo app, CSS custom properties for the Deck. Pure functions of the JSON, so the outputs are
// byte-for-byte stable and a test can say when one is stale.
import fs from "node:fs";
import path from "node:path";

export const TOKENS = "docs/design/one-app/tokens.json";

/** @param {string} root */
export function load(root) {
  return JSON.parse(fs.readFileSync(path.join(root, TOKENS), "utf8"));
}

/** "#0E0D0C" or "rgba(1,2,3,0.5)" as [r, g, b, a] (0 to 255, alpha 0 to 1). */
export function rgba(value) {
  const hex = /^#([0-9a-f]{6})$/i.exec(value);
  if (hex) return [0, 2, 4].map(i => parseInt(hex[1].slice(i, i + 2), 16)).concat(1);
  const fn = /^rgba?\(([^)]+)\)$/i.exec(value);
  if (!fn) throw new Error(`not a colour: ${value}`);
  const p = fn[1].split(",").map(s => Number(s.trim()));
  return [p[0], p[1], p[2], p.length > 3 ? p[3] : 1];
}

const num = n => (Number.isInteger(n) ? String(n) : String(n));
const swiftColor = v => { const [r, g, b, a] = rgba(v); return `Color(.sRGB, red: ${r} / 255, green: ${g} / 255, blue: ${b} / 255, opacity: ${num(a)})`; };
const HEAD = "Generated by scripts/gen-tokens from docs/design/one-app/tokens.json. Do not edit; change the JSON and run it.";

/** The Capsule's Swift file. */
export function swift(t) {
  const keys = Object.keys(t.color.dark);
  const colors = theme => keys.map(k => `        ${k}: ${swiftColor(t.color[theme][k])}`).join(",\n");
  const alt = Object.entries(t.color.attentionAlt)
    .map(([name, v]) => `        "${name}": (${swiftColor(v.dark)}, ${swiftColor(v.paper)})`).join(",\n");
  const status = t.status.order.map(k => {
    const s = t.status[k];
    return `        Status(key: "${k}", mark: "${s.mark}", color: "${s.color}", word: "${s.word}")`;
  }).join(",\n");
  const enumOf = (name, obj, type = "CGFloat") =>
    `    public enum ${name} {\n${Object.entries(obj).map(([k, v]) => `        public static let ${k}: ${type} = ${num(v)}`).join("\n")}\n    }`;
  const typeScale = Object.entries(t.type.desktop)
    .map(([k, [size, line]]) => `        public static let ${k}: (size: CGFloat, line: CGFloat) = (${size}, ${line})`).join("\n");
  const phoneScale = Object.entries(t.type.phone)
    .map(([k, [size, line]]) => `        public static let ${k}: (size: CGFloat, line: CGFloat) = (${size}, ${line})`).join("\n");
  const { ease, ...motion } = t.motion;
  return `// ${HEAD}
// The Capsule reads these through Theme.swift; the app and the Deck read the same JSON.

import SwiftUI

public enum Tokens {
    public struct Colors: Sendable {
${keys.map(k => `        public let ${k}: Color`).join("\n")}
    }

    public static let dark = Colors(
${colors("dark")}
    )

    public static let paper = Colors(
${colors("paper")}
    )

    /// The attention colour when the person picks another than beacon (violet).
    public static let attentionAlt: [String: (dark: Color, paper: Color)] = [
${alt}
    ]

    public struct Status: Equatable, Sendable {
        public let key: String, mark: String, color: String, word: String
    }
    /// Most urgent first: a row shows the first that applies. The keys are a stable contract.
    public static let status: [Status] = [
${status}
    ]

${enumOf("Radius", t.radius)}

${enumOf("Control", t.control)}

    public static let space: [CGFloat] = [${t.space.join(", ")}]

    /// Durations in milliseconds, and the easing curve's control points.
    public enum Motion {
${Object.entries(motion).map(([k, v]) => `        public static let ${k}: Double = ${num(v)}`).join("\n")}
        public static let ease: [Double] = [${ease.join(", ")}]
    }

    /// [size, line height] in points, desktop and the Capsule.
    public enum TypeScale {
${typeScale}
    }

    /// [size, line height] in points on a phone: the read and title steps are two larger.
    public enum PhoneTypeScale {
${phoneScale}
    }

    /// Sizes JetBrains Mono may use, in points.
    public static let monoSizes: [CGFloat] = [${t.type.mono.join(", ")}]

    public static let fontSans = "${t.font.sans}"
    public static let fontMono = "${t.font.mono}"
}
`;
}

/** The Expo app's tokens.ts (apps/app/src/theme/tokens.ts): the JSON as a frozen `as const`
 * object, minus the note, plus `attention(scheme, alt)` so the violet/teal choice stays one key. */
export function ts(t) {
  const { $schema, note, ...rest } = t;
  void $schema; void note;
  return `// Generated by scripts/gen-tokens from ${TOKENS}. Do not edit; change the JSON and run it.

export const tokens = ${JSON.stringify(rest, null, 2)} as const;

export type Scheme = "dark" | "paper";
export type Colors = typeof tokens.color.dark;

/** The attention colour: beacon (violet) by default, or an alternative such as teal. */
export function attention(scheme: Scheme, alt?: keyof typeof tokens.color.attentionAlt): string {
  return alt ? tokens.color.attentionAlt[alt][scheme] : tokens.color[scheme].beacon;
}
`;
}

/** The Deck's roles as custom properties, under the selectors deck.css uses (:root is dark, and
 * :root[data-theme="paper"] swaps the roles). Names are the Deck's: --text-2, --rule-strong,
 * --beacon-ink and --beacon-dot for the attention colour, --beacon-badge-ink for a badge's count. */
export function css(t) {
  const kebab = k => k.replace(/[A-Z0-9]/g, (c, i) => (i ? "-" : "") + c.toLowerCase());
  const roles = theme => {
    const c = t.color[theme];
    const out = Object.entries(c).filter(([k]) => k !== "beacon").map(([k, v]) => [kebab(k), v]);
    out.push(["beacon-ink", c.beacon], ["beacon-dot", c.beacon], ["beacon-badge-ink", c.primaryInk]);
    out.push(["float", t.shadow[theme]]);
    return out.map(([k, v]) => `  --${k}: ${v};`).join("\n");
  };
  return `/* ${HEAD} */

:root {
${roles("dark")}
  --sans: '${t.font.sans}', 'Helvetica Neue', Arial, sans-serif;
  --mono: '${t.font.mono}', ui-monospace, Menlo, monospace;
  color-scheme: dark;
}
:root[data-theme="paper"] {
${roles("paper")}
  color-scheme: light;
}
`;
}
