#!/bin/sh
# Build the native Capsule with swiftc alone: no Xcode project, no package manager, no network.
#
#   build.sh test [filter]   compile the sources with Tests/ and run them
#   build.sh app             compile Vyre.app into .build/ (bundle, plist, signature: see below)
#
# Two files are written at build time and never committed, so no team edits a shared list:
#   Registry.generated.swift   every class marked `// capsule-extension: Name` under
#                              Sources/Extensions/ (the seam in Sources/Kit/Extension.swift)
#   main.swift (tests only)    every suite marked `// capsule-suite: name` under Tests/
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
out="${VYRE_CAPSULE_BUILD:-$here/.build}"
mode="${1:-app}"
target="$(uname -m)-apple-macosx14.0"
[ "$(uname -s)" = Darwin ] || { echo "the Capsule builds only on macOS" >&2; exit 1; }
command -v swiftc >/dev/null 2>&1 || { echo "swiftc not found. Install the Xcode command line tools: xcode-select --install" >&2; exit 1; }
mkdir -p "$out/gen"

# The extension registry.
reg="$out/gen/Registry.generated.swift"
{
  echo "// Generated by build.sh from the capsule-extension markers. Do not edit."
  echo "@MainActor let extensionTypes: [CapsuleExtension.Type] = ["
  grep -rhoE '^// capsule-extension: [A-Za-z_][A-Za-z0-9_]*' "$here/Sources/Extensions" 2>/dev/null | awk '{print "    " $3 ".self,"}' | sort -u
  echo "]"
} > "$reg"

# Every source but the app's entry point, in a stable order.
sources() { find "$here/Sources" -name '*.swift' ! -path "*/Host/main.swift" | LC_ALL=C sort; }

case "$mode" in
  test)
    main="$out/gen/tests/main.swift"
    mkdir -p "$(dirname "$main")"
    {
      echo "// Generated by build.sh from the capsule-suite markers. Do not edit."
      printf "runSuites(["
      grep -rhoE '^// capsule-suite: [A-Za-z_][A-Za-z0-9_]*' "$here/Tests" | awk '{printf "%s, ", $3}'
      echo "])"
    } > "$main"
    bin="$out/capsule-tests"
    # shellcheck disable=SC2046
    swiftc -Onone -target "$target" -o "$bin" $(sources) "$reg" $(find "$here/Tests" -name '*.swift' | LC_ALL=C sort) "$main"
    shift || true
    VYRE_CAPSULE_TEST=1 "$bin" "$@"
    ;;
  app)
    app="$out/Vyre.app"
    mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
    # shellcheck disable=SC2046
    swiftc -O -target "$target" -o "$app/Contents/MacOS/Vyre" $(sources) "$reg" "$here/Sources/Host/main.swift"
    # The plist: LSUIElement (menu bar, no Dock icon), usage strings for permissions asked on
    # first use, and whatever extensions add in Sources/Extensions/<name>/Info.plist.part.
    version="$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' "$here/../../../package.json" 2>/dev/null | head -1)"
    {
      cat <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>sh.vyre.capsule</string>
  <key>CFBundleName</key><string>Vyre</string>
  <key>CFBundleDisplayName</key><string>Vyre</string>
  <key>CFBundleExecutable</key><string>Vyre</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>${version:-0.0.0}</string>
  <key>CFBundleVersion</key><string>${version:-0.0.0}</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSSupportsAutomaticTermination</key><false/>
  <key>NSContactsUsageDescription</key><string>Vyre lists the people you search for, on this Mac only.</string>
  <key>NSCalendarsFullAccessUsageDescription</key><string>Vyre shows your events when you search for them, on this Mac only.</string>
  <key>NSRemindersFullAccessUsageDescription</key><string>Vyre shows and adds reminders when you ask, on this Mac only.</string>
  <key>NSAppleEventsUsageDescription</key><string>Vyre runs the Mac commands you pick, such as Empty Trash or Toggle Dark Mode.</string>
PLIST
      find "$here/Sources/Extensions" -name Info.plist.part -exec cat {} \; 2>/dev/null
      printf '</dict>\n</plist>\n'
    } > "$app/Contents/Info.plist"
    # One stable identity keeps Accessibility and Input Monitoring grants across updates. The
    # identifier pins the designated requirement; VYRE_SIGN_IDENTITY names a local certificate
    # when there is one, otherwise the signature is ad hoc.
    codesign --force --sign "${VYRE_SIGN_IDENTITY:--}" --identifier sh.vyre.capsule "$app" >/dev/null
    echo "built $app"
    ;;
  *) echo "usage: build.sh test [filter] | app" >&2; exit 2 ;;
esac
