// Generated by scripts/gen-tokens from tokens.v3 in lib/theme/tokens.json. Do not edit; change the JSON and run it.

export const V3 = {
  "note": "The six-primitives direction (team/0.3/tokens-v3.json, ui-primitives.md): what a space and a person may configure, and the allowed values. Resolution is defaults, then the space, then the person. Contrast is computed, never chosen. The Deck reads it through deck/ui/theme.js, which writes the custom properties below onto the root element.",
  "accents": {
    "violet": {
      "label": "Violet",
      "dark": "#B8A4FF",
      "paper": "#5B3FC4"
    },
    "amber": {
      "label": "Amber",
      "dark": "#E3B26B",
      "paper": "#9A6410"
    },
    "sky": {
      "label": "Sky",
      "dark": "#8FB7E8",
      "paper": "#2F6AA8"
    },
    "sage": {
      "label": "Sage",
      "dark": "#A9CF9B",
      "paper": "#3F7A30"
    },
    "rose": {
      "label": "Rose",
      "dark": "#E8A0C0",
      "paper": "#A8386A"
    }
  },
  "contrast": {
    "text": 4.5,
    "nonText": 3,
    "grounds": {
      "dark": "#141311",
      "paper": "#F4F1EA"
    }
  },
  "density": {
    "default": "default",
    "steps": {
      "compact": {
        "space": 0.8,
        "control": 30,
        "controlSm": 26,
        "row": 44,
        "body": [
          13,
          18
        ]
      },
      "default": {
        "space": 1,
        "control": 36,
        "controlSm": 30,
        "row": 56,
        "body": [
          14,
          20
        ]
      },
      "comfortable": {
        "space": 1.2,
        "control": 42,
        "controlSm": 34,
        "row": 64,
        "body": [
          15,
          22
        ]
      }
    }
  },
  "font": {
    "default": "sans",
    "stacks": {
      "sans": {
        "label": "Instrument Sans",
        "css": "'Instrument Sans', 'Helvetica Neue', Arial, sans-serif"
      },
      "system": {
        "label": "System",
        "css": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
      },
      "serif": {
        "label": "Serif",
        "css": "'Iowan Old Style', 'Palatino Linotype', Georgia, serif"
      }
    }
  },
  "corners": {
    "default": "default",
    "steps": {
      "sharp": 0.4,
      "default": 1,
      "round": 1.5
    },
    "applies": [
      "chip",
      "field",
      "button",
      "row",
      "card",
      "sheet"
    ]
  },
  "spaceSteps": [
    1,
    2,
    3,
    4,
    5,
    6,
    8,
    10,
    12
  ],
  "person": {
    "theme": [
      "dark",
      "paper",
      "system"
    ],
    "density": [
      null,
      "compact",
      "default",
      "comfortable"
    ],
    "reducedMotion": [
      false,
      true
    ],
    "largerText": [
      false,
      true
    ]
  },
  "fixed": [
    "ok",
    "warn",
    "err",
    "washes of those",
    "type scale ratios",
    "elevation levels",
    "icon family",
    "focus ring"
  ],
  "components": [
    "button",
    "iconButton",
    "chip",
    "field",
    "switch",
    "segmented",
    "tabs",
    "avatar",
    "row",
    "card",
    "askCard",
    "banner",
    "sheet",
    "menu",
    "toast",
    "table",
    "stageSteps",
    "timelineItem",
    "emptyState"
  ],
  "fieldKinds": [
    "text",
    "number",
    "money",
    "date",
    "choice",
    "stage",
    "actor",
    "link",
    "file",
    "address",
    "phone",
    "email",
    "richText",
    "rating",
    "sealed"
  ],
  "views": [
    "list",
    "board",
    "calendar",
    "recordPage",
    "dashboard"
  ]
};
