// Generated by scripts/gen-tokens from docs/design/one-app/tokens.json. Do not edit; change the JSON and run it.

export const tokens = {
  "color": {
    "dark": {
      "bg": "#0E0D0C",
      "panel": "#161513",
      "hover": "#1E1C1A",
      "rule": "#2B2926",
      "ruleStrong": "#3A3733",
      "text": "#F1EEE6",
      "text2": "#B3AEA4",
      "label": "#8C877D",
      "primaryBg": "#F1EEE6",
      "primaryHover": "#FFFFFF",
      "primaryInk": "#0E0D0C",
      "focus": "#F1EEE6",
      "signalWash": "rgba(241,238,230,0.12)",
      "delWash": "rgba(140,135,125,0.14)",
      "beacon": "#B8A4FF",
      "codeBg": "#121110",
      "scrim": "rgba(0,0,0,0.62)",
      "markWire": "#F1EEE6",
      "markDot": "#F1EEE6"
    },
    "paper": {
      "bg": "#F4F1EA",
      "panel": "#FBFAF6",
      "hover": "#EEEAE2",
      "rule": "#DCD7CC",
      "ruleStrong": "#C9C3B7",
      "text": "#141311",
      "text2": "#4A463F",
      "label": "#6B665D",
      "primaryBg": "#141311",
      "primaryHover": "#4A463F",
      "primaryInk": "#F4F1EA",
      "focus": "#141311",
      "signalWash": "rgba(20,19,17,0.10)",
      "delWash": "rgba(107,102,93,0.10)",
      "beacon": "#5B3FC4",
      "codeBg": "#F0EDE5",
      "scrim": "rgba(20,19,17,0.34)",
      "markWire": "#141311",
      "markDot": "#141311"
    },
    "attentionAlt": {
      "teal": {
        "dark": "#5FD4C4",
        "paper": "#0B6E66"
      }
    }
  },
  "status": {
    "order": [
      "needsYou",
      "failed",
      "running",
      "unread",
      "done"
    ],
    "needsYou": {
      "mark": "dot",
      "color": "beacon",
      "word": "needs you"
    },
    "failed": {
      "mark": "crossed-circle",
      "color": "text2",
      "word": "failed"
    },
    "running": {
      "mark": "ring",
      "color": "focus",
      "word": "running"
    },
    "unread": {
      "mark": "dot",
      "color": "text",
      "word": "unread"
    },
    "done": {
      "mark": "hollow-dot",
      "color": "label",
      "word": "done"
    }
  },
  "font": {
    "sans": "Instrument Sans",
    "mono": "JetBrains Mono",
    "weight": {
      "regular": "400",
      "strong": "600"
    }
  },
  "type": {
    "desktop": {
      "meta": [
        12,
        16
      ],
      "base": [
        13,
        18
      ],
      "read": [
        15,
        22
      ],
      "title": [
        20,
        26
      ],
      "hero": [
        28,
        34
      ]
    },
    "phone": {
      "meta": [
        12,
        16
      ],
      "base": [
        13,
        18
      ],
      "read": [
        17,
        24
      ],
      "title": [
        22,
        28
      ],
      "hero": [
        28,
        34
      ]
    },
    "mono": [
      12,
      13
    ]
  },
  "space": [
    0,
    2,
    4,
    8,
    12,
    16,
    24,
    32,
    48,
    64
  ],
  "radius": {
    "chip": 4,
    "field": 8,
    "button": 8,
    "buttonTouch": 10,
    "card": 12,
    "cardPhone": 10,
    "sheet": 14,
    "bubble": 12,
    "full": 999
  },
  "control": {
    "xs": 28,
    "sm": 32,
    "touch": 44,
    "touchLg": 54
  },
  "layout": {
    "breakpoints": {
      "compact": 0,
      "medium": 720,
      "wide": 1100,
      "full": 1400
    },
    "rail": 72,
    "list": 320,
    "side": 340,
    "content": 820,
    "gutterPhone": 16,
    "topBar": 56,
    "phoneHeader": 48
  },
  "motion": {
    "tap": 120,
    "panel": 220,
    "sheet": 280,
    "reveal": 150,
    "hold": 600,
    "undo": 4000,
    "ease": [
      0.25,
      0.1,
      0.25,
      1
    ]
  },
  "icon": {
    "grid": 16,
    "stroke": 1.5,
    "sizes": [
      12,
      16,
      20
    ]
  },
  "popover": {
    "dark": "inset 0 1px 0 rgba(241,238,230,0.05), 0 12px 24px -12px rgba(0,0,0,0.55)",
    "paper": "0 12px 24px -12px rgba(20,19,17,0.3)"
  },
  "shadow": {
    "dark": "inset 0 1px 0 rgba(241,238,230,0.06), 0 24px 48px -24px rgba(0,0,0,0.6)",
    "paper": "0 24px 48px -24px rgba(20,19,17,0.28)"
  },
  "v2": {
    "note": "Deck v2 (design-system.md, final: the user approved the prototype, 2 Oct 2026). Its own group so a v1 screen is never touched: the Deck links the generated tokens-v2.css after tokens.css, the Expo app reads tokens.v2, the Capsule reads Tokens.V2. Colour values are dark, then paper. A screen moves to v2 when its pass lands; when none uses v1, the v1 groups retire.",
    "color": {
      "dark": {
        "bg": "#0E0D0C",
        "surface1": "#141311",
        "surface2": "#1A1816",
        "surface3": "#211F1C",
        "edge": "rgba(241,238,230,0.075)",
        "edgeStrong": "rgba(241,238,230,0.14)",
        "edgeTop": "rgba(241,238,230,0.05)",
        "text": "#F1EEE6",
        "text2": "#B3AEA4",
        "label": "#8C877D",
        "faint": "#5F5B54",
        "primary": "#F1EEE6",
        "primaryHover": "#FFFFFF",
        "primaryInk": "#0E0D0C",
        "accent": "#B8A4FF",
        "accentWash": "rgba(184,164,255,0.12)",
        "accentInk": "#0E0D0C",
        "ok": "#6FD3A0",
        "okWash": "rgba(111,211,160,0.12)",
        "warn": "#E6B450",
        "warnWash": "rgba(230,180,80,0.12)",
        "err": "#F08A7A",
        "errWash": "rgba(240,138,122,0.12)",
        "hover": "rgba(241,238,230,0.05)",
        "press": "rgba(241,238,230,0.08)",
        "selected": "rgba(241,238,230,0.09)",
        "codeBg": "#100F0E",
        "scrim": "rgba(0,0,0,0.6)"
      },
      "paper": {
        "bg": "#ECE8DE",
        "surface1": "#F4F1EA",
        "surface2": "#FBFAF6",
        "surface3": "#FFFFFF",
        "edge": "rgba(20,19,17,0.09)",
        "edgeStrong": "rgba(20,19,17,0.18)",
        "edgeTop": "rgba(255,255,255,0.7)",
        "text": "#141311",
        "text2": "#4A463F",
        "label": "#6B665D",
        "faint": "#A39D91",
        "primary": "#141311",
        "primaryHover": "#3A3732",
        "primaryInk": "#F4F1EA",
        "accent": "#5B3FC4",
        "accentWash": "rgba(91,63,196,0.10)",
        "accentInk": "#FFFFFF",
        "ok": "#1F7A4D",
        "okWash": "rgba(31,122,77,0.10)",
        "warn": "#9A5B00",
        "warnWash": "rgba(154,91,0,0.10)",
        "err": "#B3392B",
        "errWash": "rgba(179,57,43,0.09)",
        "hover": "rgba(20,19,17,0.045)",
        "press": "rgba(20,19,17,0.075)",
        "selected": "rgba(20,19,17,0.08)",
        "codeBg": "#EFEBE2",
        "scrim": "rgba(20,19,17,0.32)"
      }
    },
    "font": {
      "weight": [
        400,
        500,
        600
      ],
      "system": "Inter on the web (bundled), SF on Apple, Roboto on Android"
    },
    "type": {
      "desktop": {
        "caption": [
          12,
          16
        ],
        "secondary": [
          13,
          18
        ],
        "body": [
          14,
          20
        ],
        "headline": [
          15,
          20
        ],
        "read": [
          15,
          23
        ],
        "title": [
          18,
          24
        ],
        "page": [
          24,
          30
        ],
        "display": [
          32,
          38
        ],
        "label": 11
      },
      "phone": {
        "caption": [
          12,
          16
        ],
        "secondary": [
          15,
          20
        ],
        "body": [
          16,
          22
        ],
        "headline": [
          17,
          22
        ],
        "read": [
          17,
          25
        ],
        "title": [
          20,
          25
        ],
        "page": [
          28,
          34
        ],
        "display": [
          34,
          41
        ],
        "label": 11
      },
      "platform": {
        "note": "ui-system.md section 2, [size, line height]. The phone table follows the platform: iOS text styles, Android Material roles; wide screens and the web use the web table. Weights 400, 500 and 600 only: titles 600, buttons 500, the rest 400.",
        "ios": {
          "display": [
            34,
            41
          ],
          "page": [
            28,
            34
          ],
          "title": [
            20,
            25
          ],
          "headline": [
            17,
            22
          ],
          "body": [
            16,
            22
          ],
          "read": [
            17,
            25
          ],
          "secondary": [
            15,
            20
          ],
          "caption": [
            12,
            16
          ],
          "label": 11
        },
        "android": {
          "display": [
            36,
            44
          ],
          "page": [
            28,
            36
          ],
          "title": [
            22,
            28
          ],
          "headline": [
            16,
            24
          ],
          "body": [
            16,
            24
          ],
          "read": [
            16,
            24
          ],
          "secondary": [
            14,
            20
          ],
          "caption": [
            12,
            16
          ],
          "label": 11
        },
        "web": {
          "display": [
            32,
            38
          ],
          "page": [
            24,
            30
          ],
          "title": [
            18,
            24
          ],
          "headline": [
            15,
            20
          ],
          "body": [
            14,
            20
          ],
          "read": [
            15,
            23
          ],
          "secondary": [
            13,
            18
          ],
          "caption": [
            12,
            16
          ],
          "label": 11
        }
      },
      "tracking": {
        "title": "-0.012em",
        "page": "-0.02em",
        "display": "-0.025em",
        "label": "0.08em"
      },
      "features": "tnum, cv11"
    },
    "space": [
      0,
      4,
      8,
      12,
      16,
      20,
      24,
      32,
      40,
      48,
      64
    ],
    "radius": {
      "chip": 6,
      "field": 10,
      "button": 10,
      "buttonTouch": 12,
      "row": 10,
      "card": 14,
      "cardPhone": 16,
      "cardHero": 16,
      "cardHeroPhone": 20,
      "sheet": 20,
      "full": 999
    },
    "control": {
      "sm": 30,
      "md": 36,
      "touchSm": 36,
      "touch": 44,
      "touchLg": 54,
      "row": 56,
      "rowPhone": 64
    },
    "layout": {
      "rail": 64,
      "list": 320,
      "side": 340,
      "pageMax": 980,
      "readMax": 720,
      "gutter": 32,
      "gutterPhone": 16
    },
    "motion": {
      "duration": {
        "press": 90,
        "state": 160,
        "panel": 240,
        "sheet": 360,
        "nod": 460
      },
      "easing": {
        "standard": [
          0.2,
          0.7,
          0.2,
          1
        ],
        "inOut": [
          0.4,
          0,
          0.2,
          1
        ],
        "spring": [
          0.34,
          1.4,
          0.64,
          1
        ]
      },
      "spring": {
        "spatial": {
          "fast": {
            "damping": 0.6,
            "stiffness": 800
          },
          "default": {
            "damping": 0.8,
            "stiffness": 380
          },
          "slow": {
            "damping": 0.8,
            "stiffness": 200
          }
        },
        "effects": {
          "fast": {
            "damping": 1,
            "stiffness": 3800
          },
          "default": {
            "damping": 1,
            "stiffness": 1600
          },
          "slow": {
            "damping": 1,
            "stiffness": 800
          }
        }
      },
      "stagger": {
        "step": 24,
        "max": 8
      },
      "hold": 600,
      "undo": 4000,
      "reducedMotion": "stop shine, spring, slide and nod; state changes still show"
    },
    "elevation": {
      "note": "Three levels; nothing else casts a shadow. A layer is [x, y, blur, spread, colour, inset]; a colour that names a role (edgeTop) is that role's value in the scheme.",
      "dark": {
        "e1": [
          [
            0,
            1,
            0,
            0,
            "edgeTop",
            true
          ],
          [
            0,
            1,
            2,
            0,
            "rgba(0,0,0,0.35)",
            false
          ]
        ],
        "e2": [
          [
            0,
            1,
            0,
            0,
            "edgeTop",
            true
          ],
          [
            0,
            8,
            24,
            -8,
            "rgba(0,0,0,0.6)",
            false
          ],
          [
            0,
            2,
            6,
            0,
            "rgba(0,0,0,0.35)",
            false
          ]
        ],
        "e3": [
          [
            0,
            1,
            0,
            0,
            "edgeTop",
            true
          ],
          [
            0,
            28,
            64,
            -20,
            "rgba(0,0,0,0.75)",
            false
          ],
          [
            0,
            6,
            18,
            0,
            "rgba(0,0,0,0.4)",
            false
          ]
        ]
      },
      "paper": {
        "e1": [
          [
            0,
            1,
            0,
            0,
            "edgeTop",
            true
          ],
          [
            0,
            1,
            2,
            0,
            "rgba(20,19,17,0.08)",
            false
          ]
        ],
        "e2": [
          [
            0,
            1,
            0,
            0,
            "edgeTop",
            true
          ],
          [
            0,
            8,
            24,
            -8,
            "rgba(20,19,17,0.18)",
            false
          ],
          [
            0,
            2,
            6,
            0,
            "rgba(20,19,17,0.08)",
            false
          ]
        ],
        "e3": [
          [
            0,
            28,
            64,
            -20,
            "rgba(20,19,17,0.28)",
            false
          ],
          [
            0,
            6,
            18,
            0,
            "rgba(20,19,17,0.10)",
            false
          ]
        ]
      }
    },
    "icon": {
      "grid": 24,
      "size": 20,
      "stroke": 1.6,
      "caps": "round",
      "joins": "round"
    },
    "emblem": {
      "note": "The project emblem (ux-research.md section 5.3): a rounded tile of four cells. Eight bytes of the project's seed (lib/avatar-seed projectBytes) choose everything, so every surface that draws a project draws the same tile. The Deck's renderer is deck/vendor/vyrecode/emblem.js; a test renders this spec and checks it draws the same SVG. Coordinates are in a 120 unit canvas; a cell is 60 units and its shapes are drawn in the cell's own 0 to 60 space.",
      "canvas": 120,
      "cell": 60,
      "corner": 30,
      "inset": 2,
      "cells": [
        [
          0,
          0
        ],
        [
          60,
          0
        ],
        [
          0,
          60
        ],
        [
          60,
          60
        ]
      ],
      "palette": [
        "#A34F3E",
        "#DA932F",
        "#2FDA4B",
        "#2FDA93",
        "#2FDADA",
        "#2F93DA",
        "#B620AA",
        "#BC2F6A"
      ],
      "ink": {
        "dark": "#141311",
        "paper": "#F4F1EA"
      },
      "draft": {
        "dash": [
          9,
          7
        ],
        "stroke": 5,
        "frame": 3,
        "cellOpacity": 0.55
      },
      "rules": [
        "ground = palette[b0 % n]; second = palette[(b0 + 2 + b1 % (n - 2)) % n]",
        "cell i (0 to 3): shape = b[2 + i] % 8; rotation = (b[2 + i] >> 3) % 4 quarter turns about the cell centre, applied only to shapes marked rotates",
        "cell i is filled with second when bit i of b6 is set, otherwise with ink; in a draft the unset cells use ground"
      ],
      "shapes": [
        {
          "kind": "circle",
          "cx": 30,
          "cy": 30,
          "r": 22
        },
        {
          "kind": "path",
          "rotates": true,
          "ops": [
            [
              "M",
              8,
              52
            ],
            [
              "L",
              8,
              8
            ],
            [
              "A",
              44,
              44,
              0,
              0,
              1,
              52,
              52
            ],
            [
              "Z"
            ]
          ]
        },
        {
          "kind": "path",
          "rotates": true,
          "ops": [
            [
              "M",
              8,
              30
            ],
            [
              "A",
              22,
              22,
              0,
              0,
              1,
              52,
              30
            ],
            [
              "Z"
            ]
          ]
        },
        {
          "kind": "rect",
          "x": 10,
          "y": 10,
          "w": 40,
          "h": 40,
          "rx": 7
        },
        {
          "kind": "path",
          "rotates": false,
          "ops": [
            [
              "M",
              30,
              6
            ],
            [
              "L",
              54,
              30
            ],
            [
              "L",
              30,
              54
            ],
            [
              "L",
              6,
              30
            ],
            [
              "Z"
            ]
          ]
        },
        {
          "kind": "ring",
          "cx": 30,
          "cy": 30,
          "r": 18,
          "stroke": 9
        },
        {
          "kind": "path",
          "rotates": true,
          "ops": [
            [
              "M",
              8,
              52
            ],
            [
              "L",
              52,
              52
            ],
            [
              "L",
              8,
              8
            ],
            [
              "Z"
            ]
          ]
        },
        {
          "kind": "rect",
          "x": 20,
          "y": 20,
          "w": 20,
          "h": 20,
          "rx": 10
        }
      ]
    }
  },
  "v3": {
    "note": "The six-primitives direction (team/0.3/tokens-v3.json, ui-primitives.md): what a space and a person may configure, and the allowed values. Resolution is defaults, then the space, then the person. Contrast is computed, never chosen. The Deck reads it through deck/ui/theme.js, which writes the custom properties below onto the root element.",
    "accents": {
      "violet": {
        "label": "Violet",
        "dark": "#B8A4FF",
        "paper": "#5B3FC4"
      },
      "amber": {
        "label": "Amber",
        "dark": "#E3B26B",
        "paper": "#9A6410"
      },
      "sky": {
        "label": "Sky",
        "dark": "#8FB7E8",
        "paper": "#2F6AA8"
      },
      "sage": {
        "label": "Sage",
        "dark": "#A9CF9B",
        "paper": "#3F7A30"
      },
      "rose": {
        "label": "Rose",
        "dark": "#E8A0C0",
        "paper": "#A8386A"
      }
    },
    "contrast": {
      "text": 4.5,
      "nonText": 3,
      "grounds": {
        "dark": "#141311",
        "paper": "#F4F1EA"
      }
    },
    "density": {
      "default": "default",
      "steps": {
        "compact": {
          "space": 0.8,
          "control": 30,
          "controlSm": 26,
          "row": 44,
          "body": [
            13,
            18
          ]
        },
        "default": {
          "space": 1,
          "control": 36,
          "controlSm": 30,
          "row": 56,
          "body": [
            14,
            20
          ]
        },
        "comfortable": {
          "space": 1.2,
          "control": 42,
          "controlSm": 34,
          "row": 64,
          "body": [
            15,
            22
          ]
        }
      }
    },
    "font": {
      "default": "sans",
      "stacks": {
        "sans": {
          "label": "Instrument Sans",
          "css": "'Instrument Sans', 'Helvetica Neue', Arial, sans-serif"
        },
        "system": {
          "label": "System",
          "css": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
        },
        "serif": {
          "label": "Serif",
          "css": "'Iowan Old Style', 'Palatino Linotype', Georgia, serif"
        }
      }
    },
    "corners": {
      "default": "default",
      "steps": {
        "sharp": 0.4,
        "default": 1,
        "round": 1.5
      },
      "applies": [
        "chip",
        "field",
        "button",
        "row",
        "card",
        "cardHero",
        "sheet"
      ]
    },
    "spaceSteps": [
      1,
      2,
      3,
      4,
      5,
      6,
      8,
      10,
      12
    ],
    "person": {
      "theme": [
        "dark",
        "paper",
        "system"
      ],
      "density": [
        null,
        "compact",
        "default",
        "comfortable"
      ],
      "reducedMotion": [
        false,
        true
      ],
      "largerText": [
        false,
        true
      ]
    },
    "fixed": [
      "ok",
      "warn",
      "err",
      "washes of those",
      "type scale ratios",
      "elevation levels",
      "icon family",
      "focus ring"
    ],
    "components": [
      "button",
      "iconButton",
      "chip",
      "field",
      "switch",
      "segmented",
      "tabs",
      "avatar",
      "row",
      "card",
      "askCard",
      "banner",
      "sheet",
      "menu",
      "toast",
      "table",
      "stageSteps",
      "timelineItem",
      "emptyState"
    ],
    "fieldKinds": [
      "text",
      "number",
      "money",
      "date",
      "choice",
      "stage",
      "actor",
      "link",
      "file",
      "address",
      "phone",
      "email",
      "richText",
      "rating",
      "sealed"
    ],
    "views": [
      "list",
      "board",
      "calendar",
      "recordPage",
      "dashboard"
    ]
  }
} as const;

export type Scheme = "dark" | "paper";
export type Colors = typeof tokens.color.dark;

/** The attention colour: beacon (violet) by default, or an alternative such as teal. */
export function attention(scheme: Scheme, alt?: keyof typeof tokens.color.attentionAlt): string {
  return alt ? tokens.color.attentionAlt[alt][scheme] : tokens.color[scheme].beacon;
}
