// Generated by scripts/gen-tokens from docs/design/one-app/tokens.json. Do not edit; change the JSON and run it.

export const tokens = {
  "color": {
    "dark": {
      "bg": "#0E0D0C",
      "panel": "#161513",
      "hover": "#1E1C1A",
      "rule": "#2B2926",
      "ruleStrong": "#3A3733",
      "text": "#F1EEE6",
      "text2": "#B3AEA4",
      "label": "#8C877D",
      "primaryBg": "#F1EEE6",
      "primaryHover": "#FFFFFF",
      "primaryInk": "#0E0D0C",
      "focus": "#F1EEE6",
      "signalWash": "rgba(241,238,230,0.12)",
      "delWash": "rgba(140,135,125,0.14)",
      "beacon": "#B8A4FF",
      "codeBg": "#121110",
      "scrim": "rgba(0,0,0,0.62)",
      "markWire": "#F1EEE6",
      "markDot": "#F1EEE6"
    },
    "paper": {
      "bg": "#F4F1EA",
      "panel": "#FBFAF6",
      "hover": "#EEEAE2",
      "rule": "#DCD7CC",
      "ruleStrong": "#C9C3B7",
      "text": "#141311",
      "text2": "#4A463F",
      "label": "#6B665D",
      "primaryBg": "#141311",
      "primaryHover": "#4A463F",
      "primaryInk": "#F4F1EA",
      "focus": "#141311",
      "signalWash": "rgba(20,19,17,0.10)",
      "delWash": "rgba(107,102,93,0.10)",
      "beacon": "#5B3FC4",
      "codeBg": "#F0EDE5",
      "scrim": "rgba(20,19,17,0.34)",
      "markWire": "#141311",
      "markDot": "#141311"
    },
    "attentionAlt": {
      "teal": {
        "dark": "#5FD4C4",
        "paper": "#0B6E66"
      }
    }
  },
  "status": {
    "order": [
      "needsYou",
      "failed",
      "running",
      "unread",
      "done"
    ],
    "needsYou": {
      "mark": "dot",
      "color": "beacon",
      "word": "needs you"
    },
    "failed": {
      "mark": "crossed-circle",
      "color": "text2",
      "word": "failed"
    },
    "running": {
      "mark": "ring",
      "color": "focus",
      "word": "running"
    },
    "unread": {
      "mark": "dot",
      "color": "text",
      "word": "unread"
    },
    "done": {
      "mark": "hollow-dot",
      "color": "label",
      "word": "done"
    }
  },
  "font": {
    "sans": "Instrument Sans",
    "mono": "JetBrains Mono",
    "weight": {
      "regular": "400",
      "strong": "600"
    }
  },
  "type": {
    "desktop": {
      "meta": [
        12,
        16
      ],
      "base": [
        13,
        18
      ],
      "read": [
        15,
        22
      ],
      "title": [
        20,
        26
      ],
      "hero": [
        28,
        34
      ]
    },
    "phone": {
      "meta": [
        12,
        16
      ],
      "base": [
        13,
        18
      ],
      "read": [
        17,
        24
      ],
      "title": [
        22,
        28
      ],
      "hero": [
        28,
        34
      ]
    },
    "mono": [
      12,
      13
    ]
  },
  "space": [
    0,
    2,
    4,
    8,
    12,
    16,
    24,
    32,
    48,
    64
  ],
  "radius": {
    "chip": 4,
    "field": 8,
    "button": 8,
    "buttonTouch": 10,
    "card": 12,
    "cardPhone": 10,
    "sheet": 14,
    "bubble": 12,
    "full": 999
  },
  "control": {
    "xs": 28,
    "sm": 32,
    "touch": 44,
    "touchLg": 54
  },
  "layout": {
    "breakpoints": {
      "compact": 0,
      "medium": 720,
      "wide": 1100,
      "full": 1400
    },
    "rail": 72,
    "list": 320,
    "side": 340,
    "content": 820,
    "gutterPhone": 16,
    "topBar": 56,
    "phoneHeader": 48
  },
  "motion": {
    "tap": 120,
    "panel": 220,
    "sheet": 280,
    "reveal": 150,
    "hold": 600,
    "undo": 4000,
    "ease": [
      0.25,
      0.1,
      0.25,
      1
    ]
  },
  "icon": {
    "grid": 16,
    "stroke": 1.5,
    "sizes": [
      12,
      16,
      20
    ]
  },
  "popover": {
    "dark": "inset 0 1px 0 rgba(241,238,230,0.05), 0 12px 24px -12px rgba(0,0,0,0.55)",
    "paper": "0 12px 24px -12px rgba(20,19,17,0.3)"
  },
  "shadow": {
    "dark": "inset 0 1px 0 rgba(241,238,230,0.06), 0 24px 48px -24px rgba(0,0,0,0.6)",
    "paper": "0 24px 48px -24px rgba(20,19,17,0.28)"
  }
} as const;

export type Scheme = "dark" | "paper";
export type Colors = typeof tokens.color.dark;

/** The attention colour: beacon (violet) by default, or an alternative such as teal. */
export function attention(scheme: Scheme, alt?: keyof typeof tokens.color.attentionAlt): string {
  return alt ? tokens.color.attentionAlt[alt][scheme] : tokens.color[scheme].beacon;
}
